### ISSUE TITLE
sdl_mixer's PlayChannel error checking is wrong

### ISSUE THREAD

**Issue by Decker108** [veandco/go-sdl2#100]
The current implementation for sdl_mixer's PlayChannel function returns a bool specifying whether the call was successful or not: 

    func (chunk *Chunk) PlayChannel(channel, loops int) bool {
        _channel := (C.int)(channel)
        _chunk := (*C.Mix_Chunk)(unsafe.Pointer(chunk))
        _loops := (C.int)(loops)
        return int(C.Mix_PlayChannelTimed(_channel, _chunk, _loops, -1)) == 0
    }

However, the original docs for sdl_mixer states that the return value is "the channel the sample is played on. On any errors, -1 is returned." (http://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC28)

Perhaps this function could be rewritten to:

    func (chunk *Chunk) PlayChannel(channel, loops int) (int, error) {
        _channel := (C.int)(channel)
        _chunk := (*C.Mix_Chunk)(unsafe.Pointer(chunk))
        _loops := (C.int)(loops)
        retVal := int(C.Mix_PlayChannelTimed(_channel, _chunk, _loops, -1))
        if retVal == -1 {
                return -1, sdl.GetError()
        }
        return retVal, nil
    }

Granted, it might be unnecessary to return the same channel as was input. Either way, comparing to 0 for error checking seems wrong according to the docs.

**Comment by Decker108** [comment]
It seems this applies to a number of other sdl_mixer functions as well, such as AllocateChannels, playChannelTimed, etc. It seems the sdl_mixer devs used a "novel" definition of return values...

**Comment by krux02** [comment]
I updated the SDL_Mixer functions to more ideomatic go, and all functions that return an int that is not simply translateable as error/no-error, it stays as an int  result.

**Comment by krux02** [comment]
I would like to vote this issue as fixed

**Comment by Decker108** [comment]
@krux02 PlayChannel and PlayTimed doesn't return their channel_ values though...

**Comment by Decker108** [comment]
Done!
