### ISSUE TITLE
non-utf8 functions in sdl-ttf

### ISSUE THREAD

**Issue by krux02** [veandco/go-sdl2#114]
I recently saw, that the sdl-ttf wrapper has latin1 and utf8 support. Since go is utf8-only. I suggest to remove the non-utf8 version, since there is no way of providing a string that is encoded in latin1 (in the non ascii compatible range of course)

**Comment by wenerme** [comment]
Currently I need this features, my font encoding is gbk, I can not use the RenderUTF8

**Comment by akovaski** [comment]
How can you using sdl-ttf to display gbk strings? (Which functions do you use?)

Would converting your text strings from gbk to utf-8 not work?
http://golang.org/x/text/encoding
http://golang.org/x/text/encoding/simplifiedchinese

**Comment by wenerme** [comment]
I mean the font only support GBK encoding.

**Comment by akovaski** [comment]
If it's a .ttf font file, then I don't think the encoding should matter.

Can you open this as a new issue?

**Comment by wenerme** [comment]
Some font only support gbk charset, like described [here](https://msdn.microsoft.com/en-us/library/cc194829.aspx). If the font only support gb2312, you can not use UTF8 encoded char to get the glyph.

**Comment by akovaski** [comment]
I get that the font only supports the gbk charset. Where are you seeing that you can't use a utf-8 encoded character to get the glyph?

Also, could you link an example gbk font's ttf file? I would like to test this myself.

**Comment by wenerme** [comment]
In Windows, SIMSUN.ttf (宋体 in Chinese) is a bitmap font and encoded in gb2312. I'm not sure is this font only exists in Chinese Windows system.

**Comment by akovaski** [comment]
I only have simsun.ttc . I imagine it's similar. (Maybe not, who knows)

In any case, it seems to work fine for me: https://gist.github.com/akovaski/e46478f9a911c654ab5a

**Comment by krux02** [comment]
Let me inform you again. In go it is not possible, to have a build in string that is not encoded as utf8. Of course you can force the runtime to take your raw data as a string, but then you have an invalid string, or at least something that is not compatible with anything, or behaves weird in every way. And you talked about Chinese letters. Latin1 does not contain any Chinese letters, it has european symbols only. So it would not help you at all to have this function for chinese letters. If you have a string that prints with fmt.Printf the right thing on the console then you should already have a valid utf8 string. But please make sure, that your source in correctly encoded in utf8.

**Comment by akovaski** [comment]
By the way, I believe the original issue was resolved with commit 498b51e29eb9a0

**Comment by wenerme** [comment]
@akovaski Try this font [simsun.ttf](https://drive.google.com/open?id=0B8v8c6AgISHrMW5NQjY5c1BGTDg&authuser=0)

This is what I got 
![image](https://cloud.githubusercontent.com/assets/1777211/7673437/ef33525c-fd45-11e4-8019-1b38d3d81894.png)

**Comment by wenerme** [comment]
@krux02 My source encoded in UTF8, but I use 
http://golang.org/x/text/encoding
http://golang.org/x/text/encoding/simplifiedchinese
to convert to gbk encoding.

In sdl_ttf here is an [TTF_RenderGlyph_Solid](https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf_46.html#SEC46).But when I convert a utf8 string to gbk, how would I know the bytes pre-char ?

This is easy, we can use the Encoding to encode every rune, so we'll know the glyph index in other encoding

```
        encooder := simplifiedchinese.GBK.NewEncoder();
	s := "ABC 您好"
	var index uint64
	buf := make([]byte, 10)
	rune_buf := make([]byte, 10)
	for _, r := range s {
		if r < utf8.RuneSelf {
			// single byte is ascii
			index = uint64(r)
		}else {
			l := utf8.EncodeRune(rune_buf, r)
			nDst, _, err := encooder.Transform(buf, rune_buf[0:l], true)
			if err != nil {panic(err)}

			// Not sure about the byte order
			switch nDst{
			case 4:
				index = uint64(binary.BigEndian.Uint32(buf))
			case 3:
				index = uint64(buf[2]) | uint64(buf[1])<<8 | uint64(buf[0])<<16
			case 2:
				index = uint64(binary.BigEndian.Uint16(buf))
			default:
				panic("Unexpected length")
			}
		}
		fmt.Printf("index %d\n", index)
	}
```

**Comment by wenerme** [comment]
BTW, should sdl.ttf also add the original [SDL_TTF document](https://www.libsdl.org/projects/SDL_ttf/docs/) link in comment like other functions.

**Comment by akovaski** [comment]
Yea, that font doesn't work for me either. From what I can tell, that font is actually only used for Extension B characters (which are supposed to be rarer).

I don't know how to utilize the ExtB  version, but if you just need simple strings like "ABC 您好" you can use std_ttf like my example above with the main SimSun ttf/ttc file.
![capture](https://cloud.githubusercontent.com/assets/1094022/7674023/2a1fb3c2-fce4-11e4-81c7-14e95161a571.PNG)

**Comment by wenerme** [comment]
That font is uploaded from my windows, in windows, the Chinese default encoding is gbk/gb2312, so I need the correct encoding to get the glyph.May be in you system, the SimSun is utf8, you can upload you font and I'll try.

**Comment by akovaski** [comment]
There should also be a simsun.ttc in your font folder as well. In any case, this link works https://code.google.com/p/way2ctx/downloads/detail?name=simsun.ttc

**Comment by krux02** [comment]
Sorry I don't get it. For what do you need an encoder/decoder care for byte ordering etc? Your string s is a valid utf8 string. sdl_ttf accepts a utf8 string. Put it together, done. Maybe you should fix your font instead‽
