### ISSUE TITLE
SDL2 use golang image

### ISSUE THREAD

**Issue by wenerme** [veandco/go-sdl2#116]
How to make SDL2 use golang image package ?
My image decoder is implemented as an image decoder, I want to reuse this, is this possible ?

**Comment by krux02** [comment]
you have a valid point there, go-sdl2-image could use the golang image package, but it doesn't do that, because it was implemented as a simple wrapper around the C library. But you can avoid using the sdl-image library entirely and just use [CreateRGBSurfaceFrom](https://wiki.libsdl.org/SDL_CreateRGBSurfaceFrom). That function does not copy the pixel data nor does it's pointer to a golang image prevent it's garbage collection, because the pointer itself is not known by the go runtime.

**Comment by wenerme** [comment]
Any example ?

**Comment by krux02** [comment]
No, I am sorry, I do not have an example at the moment that I can just paste here. But you need the Pix array from your image, and cast that to an unsafe.Pointer to give it to the function. then you need to get the format parameters right. most important here, is that you get the size and bytes per pixel right, because otherwise you might get a segmentation fault. when the color masks are wrong you just get funny colors. And you should not loose the reference to your go image.

**Comment by wenerme** [comment]
Here is some thing I tried.

```
func main() {
	if err != nil {panic(err)}
	t2()
}

func t2() {
	//
	//	f, err := os.Open("test.jpg")
	//	if err != nil {panic(err)}
	//	i, _, err := image.Decode(f)
	r, err := http.Get("http://blacktiecreative.org/wp-content/uploads/2014/05/Breaking-Bad-HP-Poster.jpg")
	if err != nil {panic(err)}
	b, err := ioutil.ReadAll(r.Body)
	if err != nil {panic(err)}
	i, _, err := image.Decode(bytes.NewReader(b))
	if err != nil {panic(err)}

	fmt.Println(i.Bounds())
	fmt.Printf("%T\n", i)

	s, err := CreateSurfaceFromImageV2(i)// V2 save correct
	if err != nil {panic(err)}
	fmt.Println(s.PixelNum())

	window, err := sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
	800, 600, sdl.WINDOW_SHOWN)
	if err != nil { panic(err) }
	defer window.Destroy()

	surface, err := window.GetSurface()
	if err != nil { panic(err) }

	if (false) {
		s2, err := sdl.CreateRGBSurface(0, 800, 600, 32, 0, 0, 0, 0);
		if err != nil { panic(err) }
		s2.FillRect(&sdl.Rect{0, 0, 100, 100}, 0xFF888888)
		s2.FillRect(&sdl.Rect{100, 100, 100, 100}, 0xFF000088)
		tmp := image.NewRGBA(image.Rect(0, 0, 800, 600))
		tmp.Pix = s2.Pixels()
		saveTemp(tmp) // Save correct, but UpdateSurface unexpected signal during runtime execution
	}


	// Blit Not works, why ?
	surface.Blit(&sdl.Rect{0, 0, 800, 600}, s, &sdl.Rect{0, 0, 800, 600})
	surface.FillRect(&sdl.Rect{0, 0, 100, 100}, 0xFF888888)
	fmt.Printf("%#v\n", surface.Format)
	window.UpdateSurface()
	{
		tmp := image.NewRGBA(image.Rect(0, 0, 800, 600))
		tmp.Pix = surface.Pixels()
		//		saveTemp(tmp) // Save correct
	}

	sdl.Delay(1500)
	sdl.Quit()
}

func CreateSurfaceFromImageV2(i image.Image) (*sdl.Surface, error) {
	rgba := image.NewRGBA(i.Bounds())
	w, h := i.Bounds().Max.X, i.Bounds().Max.Y
	s, err := sdl.CreateRGBSurface(0, int32(w), int32(h), 32, 0, 0, 0, 0);
	if err != nil {return s, err}
	rgba.Pix = s.Pixels()

	for y := 0; y < h; y+=1 {
		for x := 0; x < w; x+=1 {
			c := i.At(x, y)
			rgba.Set(x, y, c)
		}
	}

	tmp := image.NewRGBA(i.Bounds())
	tmp.Pix = s.Pixels()
	fmt.Println("Pixels ", s.Pixels()[0:10], " VS ", rgba.Pix[0:10])
	saveTemp(tmp)// save correct
	s.SaveBMP("s.bmp")// Byte order is incorrect under mac os
	return s, err
}
func CreateSurfaceFromImage(i image.Image) (*sdl.Surface, error) {
	rgba := image.NewRGBA(i.Bounds())
	w, h := i.Bounds().Max.X, i.Bounds().Max.Y
	for y := 0; y < h; y+=1 {
		for x := 0; x < w; x+=1 {
			c := i.At(x, y)
			rgba.Set(x, y, c)
		}
	}
	s, err := sdl.CreateRGBSurfaceFrom(unsafe.Pointer(&rgba.Pix), w, h, 32, len(rgba.Pix), 0, 0, 0, 0)
	if err != nil {return s, err}
	//	tmp := image.NewRGBA(i.Bounds())
	//	tmp.Pix = s.Pixels()
	//	saveTemp(tmp) // save is incorrect
	return s, err
}
```

Conclusion:

1. Surface and RGBA can use same Pixels
2. Can not use CreateRGBSurfaceFrom method
3. Can CreateRGBSurface first, then Create a RGBA, give the Surface Pixels to RGBA(CreateSurfaceFromImageV2), can reuse golang Draw

Question:

1. If enable this, `window.UpdateSurface()` will get error, why ?
```
if (false) {
		s2, err := sdl.CreateRGBSurface(0, 800, 600, 32, 0, 0, 0, 0);
		if err != nil { panic(err) }
```

2. `surface.Blit(&sdl.Rect{0, 0, 800, 600}, s, &sdl.Rect{0, 0, 800, 600})` not works, but save BMP is ok, why ?

**Comment by krux02** [comment]
You definitely can use CreateRGBSurfaceFrom method. The only problem you have, is that the image.Image interface does not give you enough information. What you actually have to do is to do is a type switch of the different implementations of image.Image. And when you have a compatible implementation like image.RGBA, you can just get the uint8 array. Alternatively, you can also get the array with reflection. It is called in all image types just Pix.

**Comment by wenerme** [comment]
Turns out, Image and Surface is all about color mode convert, golang have RGBA.

RGBA match RGBA8888 and RGBX8888, other SDL pixel format have to implement new color.Modle to support.The color issues in above code, the caused by `CreateRGBSurface`,have to create the RGBA8888 and RGBX8888.

**Comment by krux02** [comment]
Don't you just have to find the one color model that is supported in both golang image and go-sdl/img? To my common sense blitting operations can only be fast implemented, if the encoding of the src and target image are the same.

**Comment by wenerme** [comment]
Close this issues now.
