### ISSUE TITLE
Questions;

### ISSUE THREAD

**Issue by joeblew99** [veandco/go-sdl2#119]
does anyone know if SDL2 is available on IOS and Android ?.

I was reading about how SDL was used for IOS and Android here (https://google.github.io/pienoon/pie_noon_guide_engine.html), but i am curious is SDL2 is also available on these mobile platforms.

Golang can compile to Android, and soon IOS.

**Comment by krux02** [comment]
All you need to do to check weather a specific backend is supported, is to download the sourcecode, and check for the platforms that are actually there. And yes SDL2 is available on those platforms.

**Comment by joeblew99** [comment]
Great.

Will give it a shot. Thank you very much

**Comment by krux02** [comment]
Can you please tell how well it turned out with go? Would be nice to read some practical experince.

**Comment by joeblew99** [comment]
For sure. I am setting up ios and android now. Not sure how well that will flow since ios is very raw.

**Comment by Kurkkuo** [comment]
Any new updates?
