### ISSUE TITLE
Types mismatch using texture.Query()

### ISSUE THREAD

**Issue by avdept** [veandco/go-sdl2#120]
I have simple code like

    dst := sdl.Rect{X: x, Y:y, W:0, H:0}

    _, _, dst.W, dst.H, _ = texture.Query()

according to docs interface sdl.Rect requires int32 values, while texture.Query() returns int values. 
Thus i got this error

    ./sdl.go:63: cannot assign to int(dst.W)
    ./sdl.go:63: cannot assign to int(dst.H)

Is it ok, to allocate new temp variables, to later do like

    _, _, w, h, _ = texture.Query()

    dst.W = int32(w)
    dst.H = int32(h)

**Comment by jackyb** [comment]
I pushed a quick change to allow that assignment.

Honestly, we haven't really thought through the types.

**Comment by avdept** [comment]
Thanks. I'm kinda new to golang and sdl2, but where else would i need to use texture.Query() method? ALso in native version, you passing pointers for `width` and `height` arguments, while go version, returning these values instead. What was reason behind this?

**Comment by jackyb** [comment]
It's mostly because we decided to cater to people who are used to Go instead of C.
