### ISSUE TITLE
How can I package my program ?

### ISSUE THREAD

**Issue by Depado** [veandco/go-sdl2#129]
Hi,

I've been wondering whether or not the generated binary was actually a standalone binary. After a quick thinking on that, I realised that it's not possible at the time.

My questions is : How can I distribute my program (mainly on Linux) without the need for the person receiving the program to install the dev libs ? Does anyone have a working example that works "out of the box" ? :)

Thanks for the amazing binding by the way, it works like a charm !

**Comment by krux02** [comment]
the "dev libs" known on debian systems as the packages containing the development headers, are not required for a bundled program. but the SDL libraries are. As far as I know, you should be able to bundle your application with the sdl libraries, and supply a simple run script that does something like this:

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/to/your/libs"
    programName

but honestly I do not think that a dependency to SDL on linux is anything that you should worry about. Just tell the people on linux that SDL is a dependency.

**Comment by jangler** [comment]
I agree that it's no problem on Linux, but Linux isn't the only OS out there. As @krux02 said, it's possible to include the dynamically linked libraries when you distribute your application, but I'd be very interested in being able to statically link the SDL libraries with the executable. In my view, the fact that Go libraries are statically linked into the executable is a major boon, and I hate to lose that by depending on a dynamically linked C library.

**Comment by krux02** [comment]
I am sorry to tell you, I did not find any way to statically link a GO program with an extern C library yet. I tried a lot, but I was never successful.

**Comment by Depado** [comment]
That's what I ended up doing, the bash (shell) script technique that exports the `LD_LIBRARY_PATH` before running the binary. Although it's quite an ugly solution. You're right, on Linux having SDL installed is pretty common, but I wonder if there wouldn't be a better way of packaging the binary for it to have no external dependency. That kind of loses one of the key concepts of Go which are the standalone binaries. But it's ok, I know it's a binding, I was just curious to know if there was a proper way of doing this.

**Comment by Depado** [comment]
@krux02 There seem to be a solution for static linking a C library with a Go program : https://github.com/shadowmint/go-static-linking
http://stackoverflow.com/questions/16747021/how-do-you-statically-link-a-c-library-in-go-using-cgo

Did you give that a shot ? ^^

**Comment by jalan** [comment]
I'm not sure it will be a good idea to create a completely static binary with SDL2, since you would need to statically link SDL2's dependencies as well, which on linux seem to include libdl and libpthread. But you should be able to statically link some libraries. In plain C, to statically link SDL2 but dynamically link its dependencies, I think this works:

```
$ gcc -lSDL2 example.c
$ ldd a.out | grep SDL2 # SDL2 is listed in the dynamic deps
	libSDL2-2.0.so.0 => /usr/lib64/libSDL2-2.0.so.0 (0x00007fc35e324000)
$ gcc example.c /usr/lib64/libSDL2.a -lpthread -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -lpthread -lrt
$ ldd a.out | grep SDL2 # SDL2 is no longer listed in the dynamic deps
$
```

There SHOULD be a way to instruct go to do the final linking the same way, since go lets us pass our own flags to the external linker. But I have yet to discover the right "go build" invocation.

**Comment by Depado** [comment]
@jalan You're right, I never thought of that. Indeed if I link the SDL2 lib I'll also need to link the libpng and all the SDL2 dependencies. On the other hand, is there a way I can list all the dependencies to my binary ?

**Comment by jalan** [comment]
Here's an example of what to change in go-sdl2 to get SDL2 statically linked on linux:

``` diff
diff --git a/sdl/sdl.go b/sdl/sdl.go
index ce96a0b..6110a61 100644
--- a/sdl/sdl.go
+++ b/sdl/sdl.go
@@ -1,7 +1,8 @@
 package sdl
 
 // #cgo windows LDFLAGS: -lSDL2
-// #cgo linux freebsd darwin pkg-config: sdl2
+// #cgo CFLAGS: -I/usr/include/SDL2
+// #cgo LDFLAGS: /usr/lib64/libSDL2.a -lpthread -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -lpthread -lrt
 // #include "sdl_wrapper.h"
 import "C"
```

You would be able to extend this example to statically link most of those other libraries too, everything that's not part of glibc.

**Comment by Depado** [comment]
That's impressive. I'll give it a try :) Thanks a lot !
