### ISSUE TITLE
golang sdl2 png test example not working?

### ISSUE THREAD

**Issue by Triangle345** [veandco/go-sdl2#147]
Every time I run the png test example I get:

<code>
exit status 3221225781
</code>

I installed sdl_image using go-get and have sdl_image shared libraries etc.
However; the bmp test example works just fine for me?  Is this a bug with the example or an issue with my system setup.  All I see is that message above without any other debug.  Hopefully someone can help :)

**Comment by jackyb** [comment]
I added a C version of the example as examples/texture_png.c. Could you try to run it and see if it also crashes?

`gcc texture_png.c -lSDL2 -lSDL2_image`

**Comment by Triangle345** [comment]
All though I was not able to compile the c example I have successfully got the png go example to work. Your comment allowed me to debug some library issues I was having with mingw64.  You need to place all .a files under the mingw64 lib folder and all dlls in the same directory as golang png test executable. 
The image seems to be displayed correctly and everything.

thank you.
