### ISSUE TITLE
CreateRenderer() generates exception on Windows VM

### ISSUE THREAD

**Issue by jangler** [veandco/go-sdl2#149]
Running a 32-bit Windows Vista VM on VirtualBox, `CreateRenderer()` always crashes with output such as the following:

```
Exception 0xc0000005 0x0 0x10 0x6c8037be
PC=0x6c8037be
signal arrived during cgo execution

github.com/veandco/go-sdl2/sdl._Cfunc_SDL_CreateRenderer(0x3c1d20, 0xffffffff, 0x2, 0x0)
    C:/Users/Brandon/go/src/github.com/veandco/go-sdl2/sdl/:1094 +0x3f
github.com/veandco/go-sdl2/sdl.CreateRenderer(0x3c1d20, 0xffffffff, 0x2, 0x1fff0000, 0x0, 0x0)
    C:/Users/Brandon/go/src/github.com/veandco/go-sdl2/sdl/render.go:93 +0x48
main.run(0x0)
    C:/Users/Brandon/go/src/github.com/veandco/go-sdl2/examples/render.go:29 +0x277
main.main()
    C:/Users/Brandon/go/src/github.com/veandco/go-sdl2/examples/render.go:72 +0x21

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    c:/go/src/runtime/asm_386.s:2287 +0x1
eax     0x0
ebx     0x12fd30
ecx     0x77d0e620
edx     0x20
edi     0x3c03e0
esi     0x96010c94
ebp     0x12fd78
esp     0x12fcf0
eip     0x6c8037be
eflags  0x10206
cs      0x1b
fs      0x3b
gs      0x0
exit status 2
```

I tried messing around with the parameters to `CreateRenderer()`, but it doesn't seem to make a difference. I don't have access to a modern, non-virtual Windows environment at the moment, so I can't check whether the environment is a factor.

**Comment by jackyb** [comment]
Going to have to download pirated Windows Vista 32-bit to test this out :P

**Comment by veeableful** [comment]
I installed a Windows Vista 32-bit and latest MinGW as of today under Virtualbox and it seems like it doesn't happen anymore. There _is_ a problem with renderer created with sdl.RENDERER_ACCELERATED but the error messages suggest it's a problem with Virtualbox's OpenGL implementation.

I'll be closing this issue then. If there's someone who still has this issue, feel free to comment!
