### ISSUE TITLE
Long pauses with go1.5beta1 windows/amd64

### ISSUE THREAD

**Issue by ArchRobison** [veandco/go-sdl2#150]
Thanks for writing this package!

I'm having problems with long pauses.  I've put a short demo program on Github at [https://github.com/ArchRobison/Crosshair](https://github.com/ArchRobison/Crosshair).  The program is supposed to display cross-hairs that track the cursor, and indeed does so intermittently, but with pauses on the order of 5-20 seconds on Windows 8.1.

I'm using go1.5beta1 windows/amd64, which is supposed to have very [low latency garbage collection](https://talks.golang.org/2015/go-gc.pdf).

Do you any suggestions on how to avoid the pauses?

**Comment by akovaski** [comment]
Add runtime.LockOSThread() to the beginning of your run() function.

Interestingly enough, your program seems to work as intended with go 1.4.2, but not 1.5 (even with GOMAXPROCS=1)

**Comment by phicode** [comment]
Your program runs fine after adding the following lines to your program:

    func run() int {
        runtime.LockOSThread()
        defer runtime.UnlockOSThread()

        if err := sdl.Init(sdl.INIT_EVERYTHING); err != nil {
                panic(err)
        }
        defer sdl.Quit()
        ......

GODEBUG=gctrace=1 reveals that all GCs terminate in less than 1ms.

**Comment by ArchRobison** [comment]
Thanks to all!  That solved the problem.  Now that I know what to look for, I see SDL is even the motivating example [on the Go wiki](https://github.com/golang/go/wiki/LockOSThread).
