### ISSUE TITLE
Android/iOS/WebGL support

### ISSUE THREAD

**Issue by ip** [veandco/go-sdl2#151]
What needed to implement it? I particularly interested in Android.

**Comment by jackyb** [comment]
You might already be aware of it but [gomobile](https://godoc.org/golang.org/x/mobile/app) is probably the only solution at the moment.

**Comment by ip** [comment]
@jackyb Did anyone try to compile the library for Android? How I could accomplish it?

**Comment by jackyb** [comment]
I haven't tried it but take a look at the talk.

[Go on Mobile](https://talks.golang.org/2015/gophercon-go-on-mobile.slide)
