### ISSUE TITLE
Open GL example doesn't work on OSX

### ISSUE THREAD

**Issue by nikiiv** [veandco/go-sdl2#152]
The opengl example uses github.com/jackyb/go-gl/gl
That doesn't work properly.. the package doesn't compile because darwin uses different flags. I submitted an issue about that in that project. If using the proper c directives it fails to find the proper GL bindings... I guess.. 
I tried modifying the opengl.go file to use https://github.com/go-gl v21.but then it crashes gloriously
o run opengl.go
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x4184d20, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.asmcgocall(0x4020eca, 0xc820051d88)
	/usr/local/go/src/runtime/asm_amd64.s:694 +0x6a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40068f0, 0xc820051df0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820051da8 sp=0xc820051d78
github.com/go-gl/gl/v2.1/gl._Cfunc_glowEnable(0x0, 0xc800000b71)
	github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:12697 +0x35 fp=0xc820051df0 sp=0xc820051da8
github.com/go-gl/gl/v2.1/gl.Enable(0xb71)
	/Users/niki/golang/src/github.com/go-gl/gl/v2.1/gl/package.go:19502 +0x2b fp=0xc820051e08 sp=0xc820051df0
main.main()
	/Users/niki/golang/src/github.com/veandco/go-sdl2/examples/opengl.go:36 +0x248 fp=0xc820051f50 sp=0xc820051e08
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820051fa0 sp=0xc820051f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820051fa8 sp=0xc820051fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2

What can be done so the opengl works on OSX

**Comment by jackyb** [comment]
It's not recommended to use my go-gl package anymore, sorry. I've updated the opengl.go example to use go-gl/gl package.
