### ISSUE TITLE
go-sdl2 frequently crashes in various, seemingly random places (linux x64)

### ISSUE THREAD

**Issue by rookieMP** [veandco/go-sdl2#155]
Let me preface this by saying my code is doing nothing strange with memory; it is a typical Go program. However, go-sdl2 is frequently crashing with strange errors, as if my renderer pointer is somehow becoming invalidated randomly. It's strange. 
Here is a sample stack  trace, although it can appear anywhere 
>fatal error: unexpected signal during runtime execution
>[signal 0xb code=0x1 addr=0x48 pc=0x7fd2e8552a29]
>
>runtime stack:
>runtime: unexpected return pc for runtime.sigpanic called from 0x7fd2e8552a29
>runtime.throw(0x7ceb05)
>	/usr/lib/go/src/pkg/runtime/panic.c:520 +0x69
>runtime: unexpected return pc for runtime.sigpanic called from 0x7fd2e8552a29
>runtime.sigpanic()
>	/usr/lib/go/src/pkg/runtime/os_linux.c:222 +0x3d
>
>goroutine 16 [syscall]:
>runtime.cgocall(0x410350, 0x7fd2f0293808)
>	/usr/lib/go/src/pkg/runtime/cgocall.c:143 +0xe5 fp=0x7fd2f02937f0 sp=0x7fd2f02937a8 github.com/veandco/go-sdl2/sdl._Cfunc_SDL_RenderDrawLine(0x1990170, 0x17f000001ba, 0x17f000001ec, 0x6f)
> github.com/veandco/go-sdl2/sdl/_obj/_cgo_defun.c:2663 +0x31 fp=0x7fd2f0293808 sp=0x7fd2f02937f0
>github.com/veandco/go-sdl2/sdl.(*Renderer).DrawLine(0x1990170, 0x1ba, 0x17f, 0x1ec, 0x17f, 0x0, 0x0)
	/home/map/prog/go/src/github.com/veandco/go-sdl2/sdl/render.go:408 +0x6a fp=0x7fd2f0293830 sp=0x7fd2f0293808
>main.(*Shape).Draw(0xc208062ad8, 0x0, 0x0, 0x1990170)
>	/home/map/prog/go/src/depths/shape.go:95 +0x2bf fp=0x7fd2f0293938 sp=0x7fd2f0293830
>main.(*Stone).Draw(0xc208062ac8, 0x0, 0x0, 0x1990170)
>	/home/map/prog/go/src/depths/stone.go:38 +0x51 fp=0x7fd2f0293960 sp=0x7fd2f0293938
>main.func·005(0x37, 0x7fd2f0422301)
>	/home/map/prog/go/src/depths/world.go:86 +0x9d fp=0x7fd2f02939b0 sp=0x7fd2f0293960
>main.(*AABBTree).QueryBound(0xc2080040c0, 0x7fd2f04223b8, 0xc2080cd360, 0x7fd2f0293af0)
>	/home/map/prog/go/src/depths/aabb.go:474 +0x2b7 fp=0x7fd2f0293a98 sp=0x7fd2f02939b0
>main.(*World).Draw(0xc2080040c0, 0x0, 0x0, 0x320, 0x258, 0x1990170)
>	/home/map/prog/go/src/depths/world.go:88 +0xc6 fp=0x7fd2f0293b18 sp=0x7fd2f0293a98
>main.main()
	/home/map/prog/go/src/depths/main.go:57 +0x9e5 fp=0x7fd2f0293f50 sp=0x7fd2f0293b18

I'll do anything I can to help get this fixed, it is super inconvenient for me.

**Comment by jackyb** [comment]
The usual solution is to use runtime.LockOSThread. https://github.com/golang/go/wiki/LockOSThread

We haven't implemented it yet but for now, you can do it in your main program.
