### ISSUE TITLE
Reading from image.RGBA to sdl.Texture

### ISSUE THREAD

**Issue by acsellers** [veandco/go-sdl2#156]
I figured out the code to update a sdl.Texture from an image.RGBA using the Update function. Would you like me to write a pull request for an example showing that?

```
size := img.Bounds().Size()
tex, _ := renderer.CreateTexture(
  sdl.PIXELFORMAT_ABGR8888,
  sdl.TEXTUREACCESS_STATIC,
  size.X,
  size.Y,
)
tex.Update(
  nil,
  unsafe.Pointer(&img.Pix[0]),
  img.Stride,
)
```

**Comment by jackyb** [comment]
Definitely. We don't have enough examples!
