### ISSUE TITLE
sdl.GL_SwapWindow INSANELY slow

### ISSUE THREAD

**Issue by fmd** [veandco/go-sdl2#159]
Hi everyone, I've been using this repo for a project and I've found that 99% of my program's execution time is spent in sdl.GL_SwapWindow:

![screen shot 2015-09-30 at 00 09 23](https://cloud.githubusercontent.com/assets/2799915/10181159/70410b34-670c-11e5-841a-d25fcb03d123.png)

![screen shot 2015-09-30 at 00 09 35](https://cloud.githubusercontent.com/assets/2799915/10181162/86db15c4-670c-11e5-8952-08a31e672719.png)

![screen shot 2015-09-30 at 00 44 27](https://cloud.githubusercontent.com/assets/2799915/10181163/885b819a-670c-11e5-8440-6c70016e1ff3.png)

Even when my main loop is ONLY running SDL_GL_SwapWindow (Not even rendering anything), the amount of time swapping the window takes stays the same. What's going on?

**Comment by fmd** [comment]
Even when my entire main loop is this:

```
func ProcessOneFrame() {
    //G.Input.Handle()
    t := time.Now()
    sdl.GL_SwapWindow(G.Window.Window)
    fmt.Println(time.Since(t))
    //G.handleTime()
    //G.Window.Clear()
    //G.Renderer.Render()
}
```

The rendering time still looks like this:

![screen shot 2015-09-30 at 00 49 10](https://cloud.githubusercontent.com/assets/2799915/10181214/318a8b3a-670d-11e5-8e9a-69ce442da7b1.png)

Any ideas? I'm honestly not even rendering *anything* at this point.

**Comment by akovaski** [comment]
I can't seem to reproduce your results. Perhaps post an entire program that reproduces the problem?

**Comment by fmd** [comment]
How fast is your SDL_GL_SwapWindow? Mine's faster after restarting the computer (same as glfw examples and a minimal program) but all examples are still between 13ms and 17ms.

Does this just mean that openGL programs in Go will never hit 60fps on my computer? How fast does your computer call SDL_GL_SwapWindow?

**Comment by jackyb** [comment]
Does this still produce the slow timings? What's your environment?
    package main
    
    import (
    	"fmt"
    	"time"
    
    	"github.com/veandco/go-sdl2/sdl"
    )
    
    func main() {
    	sdl.Init(sdl.INIT_EVERYTHING)
    
    	window, err := sdl.CreateWindow("Test", 100, 100, 800, 600, sdl.WINDOW_SHOWN | sdl.WINDOW_OPENGL)
    	if err != nil {
    		fmt.Println("Failed to create window:", err)
    		return
    	}
    	defer window.Destroy()
    
    	running := true
    	for running {
    		for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
    			switch event.(type) {
    			case *sdl.QuitEvent:
    				running = false
    			}
    		}
    
    		t := time.Now()
    		sdl.GL_SwapWindow(window)
    		fmt.Println(time.Since(t))
    
    		sdl.Delay(16)
    	}
    
    	sdl.Quit()
    }

**Comment by fmd** [comment]
In your example there you haven't created an openGL context. What are your results with this program?:

```
package main

import (
    "fmt"
    "time"
    "github.com/go-gl/gl/v2.1/gl"
    "github.com/veandco/go-sdl2/sdl"
)

var window *sdl.Window
var context sdl.GLContext

func initSDL() {
    if err := sdl.Init(sdl.INIT_EVERYTHING); err != nil {
        panic(err)
    }
}

func initGL() {
    if err := gl.Init(); err != nil {
        panic(err)
    }
}

func main() {
    var err error

    initSDL()
    initGL()

    window, err = sdl.CreateWindow("SwapWindow Slow Example",
                                   sdl.WINDOWPOS_UNDEFINED,
                                   sdl.WINDOWPOS_UNDEFINED,
                                   800, 600, sdl.WINDOW_OPENGL)
    if err != nil {
        panic(err)
    }

    context, err = sdl.GL_CreateContext(window)
    if err != nil {
        panic(err)
    }

    gl.ClearColor(0.4,0.0,0.3,1.0)

    projectionMode()
    setViewport(800, 600)

    modelViewMode()
    setModelViewOptions()

    startTime := time.Now()

    for time.Since(startTime) < time.Second * 10 {
        loop()
    }

    sdl.GL_DeleteContext(context)
    window.Destroy()
}

func projectionMode() {
    gl.MatrixMode(gl.PROJECTION)
    gl.LoadIdentity()
}

func setViewport(width int, height int) {
    gl.Viewport(0, 0, int32(width), int32(height))

    gl.Ortho(-float64(width)/2, float64(width)/2,
             -float64(height)/2, float64(height)/2, -1.0, 1.0)
}

func loop() {
    gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
    t := time.Now()
    sdl.GL_SwapWindow(window)
    fmt.Println(time.Since(t))
}

func modelViewMode() {
    gl.MatrixMode(gl.MODELVIEW)
    gl.LoadIdentity()
}

func setModelViewOptions() {
    gl.Enable(gl.TEXTURE_2D)
    gl.Disable(gl.LIGHTING)
    gl.Disable(gl.DITHER)
    gl.Enable(gl.CULL_FACE)
    gl.CullFace(gl.FRONT)
    gl.BlendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)
    gl.Enable(gl.BLEND)
    gl.Enable(gl.ALPHA_TEST)
    gl.DepthFunc(gl.LEQUAL)
    gl.Disable(gl.DEPTH_TEST)
}
```

**Comment by jackyb** [comment]
Seems like if I add sdl.Delay(16) inside loop(), the time it takes to swap window drops down to nanoseconds. I guess SDL probably waits for the screen to refresh behind the scene.

**Comment by jalan** [comment]
> between 13ms and 17ms

Sounds like it's vsync at 60 Hz. Your video driver might ignore calls to `GL_SetSwapInterval`, but maybe you can change that behavior in the driver configuration.

**Comment by fmd** [comment]
@jalan You were right! My Mac OS video driver was forcing vsync. For future people, to fix this: http://stackoverflow.com/questions/12345730/how-to-disable-vsync-on-mac-osx
