### ISSUE TITLE
Can't build -- SDL2 headers not found though installed?

### ISSUE THREAD

**Issue by Russtopia** [veandco/go-sdl2#160]
I installed the SDL2 minGW devel packages (manually from .tgz, not using msys2).. but I get this when trying to 'go get -v github.com/veandco/go-sdl2/sdl' as instructed.

See below for error messages and my MinGW-64 and Go env. I'm probably doing something very dumb but I'm a bit new at Go.. tips appreciated, thanks.

<pre>
russtopia@JUNK /c/Users/Public/Documents/Go/src/github.com/veandco/go-sdl2/sdl (master)
$ go get github.com/veandco/go-sdl2/sdl
# github.com/veandco/go-sdl2/sdl
In file included from C:\Users\Public\Documents\Go\src\github.com\veandco\go-sdl2\sdl\audio.go:3:0:
sdl_wrapper.h:2:23: fatal error: SDL2/SDL.h: No such file or directory
  #include <SDL2/SDL.h>
                       ^
compilation terminated.

russtopia@JUNK /c/Users/Public/Documents/Go/src/github.com/veandco/go-sdl2/sdl (master)
$ echo $GOPATH
C:\Users\Public\Documents\Go\

russtopia@JUNK /c/Users/Public/Documents/Go/src/github.com/veandco/go-sdl2/sdl (master)
$ echo $GOBIN
C:\Users\Public\Documents\Go\/bin

russtopia@JUNK /c/Users/Public/Documents/Go/src/github.com/veandco/go-sdl2/sdl (master)
$ ls /include
SDL2

russtopia@JUNK /c/Users/Public/Documents/Go/src/github.com/veandco/go-sdl2/sdl (master)
$ ls /include/SDL2
SDL.h            SDL_error.h           SDL_loadso.h      SDL_pixels.h    SDL_stdinc.h        SDL_test_fuzzer.h   SDL_version.h
SDL_assert.h     SDL_events.h          SDL_log.h         SDL_platform.h  SDL_surface.h       SDL_test_harness.h  SDL_video.h
SDL_atomic.h     SDL_filesystem.h      SDL_main.h        SDL_power.h     SDL_system.h        SDL_test_images.h   begin_code.h
SDL_audio.h      SDL_gamecontroller.h  SDL_messagebox.h  SDL_quit.h      SDL_syswm.h         SDL_test_log.h      close_code.h
SDL_bits.h       SDL_gesture.h         SDL_mouse.h       SDL_rect.h      SDL_test.h          SDL_test_md5.h
SDL_blendmode.h  SDL_haptic.h          SDL_mutex.h       SDL_render.h    SDL_test_assert.h   SDL_test_random.h
SDL_clipboard.h  SDL_hints.h           SDL_name.h        SDL_revision.h  SDL_test_common.h   SDL_thread.h
SDL_config.h     SDL_joystick.h        SDL_opengl.h      SDL_rwops.h     SDL_test_compare.h  SDL_timer.h
SDL_cpuinfo.h    SDL_keyboard.h        SDL_opengles.h    SDL_scancode.h  SDL_test_crc32.h    SDL_touch.h
SDL_endian.h     SDL_keycode.h         SDL_opengles2.h   SDL_shape.h     SDL_test_font.h     SDL_types.h

russtopia@JUNK /c/Users/Public/Documents/Go/src/github.com/veandco/go-sdl2/sdl (master)
$ go version
go version go1.5 windows/amd64</pre>

**Comment by jackyb** [comment]
Sorry for the late response, had to find a Windows machine. I'm not familiar with Windows either but I managed to get it working by installing both MinGW (just for `make`) and MinGW64. I ran `make native` at the `SDL2-2.0.3` folder and copied the resulting `C:\MinGW\msys\1.0\include\SDL2` folder and libSDL2.* files at `C:\MinGW\msys\1.0\lib` folder into `C:\Program Files\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0\mingw64\x86_64-w64-mingw32\lib`. Your paths might be slightly different.

**Comment by Russtopia** [comment]
Thanks, I will try it out!

On October 10, 2015 12:36:01 AM PDT, Jacky Boen <notifications@github.com> wrote:
>Sorry for the late response, had to find a Windows machine. I'm not
>familiar with Windows either but I managed to get it working by
>installing both MinGW (just for `make`) and MinGW64. I ran `make
>native` at the `SDL2-2.0.3` folder and copied the resulting
>`C:\MinGW\msys\1.0\include\SDL2` folder and libSDL2.* files at
>`C:\MinGW\msys\1.0\lib` folder into `C:\Program
>Files\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0\mingw64\x86_64-w64-mingw32\lib`.
>Your paths might be slightly different.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/veandco/go-sdl2/issues/160#issuecomment-147049186

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
