### ISSUE TITLE
Haptics Support

### ISSUE THREAD

**Issue by tanema** [veandco/go-sdl2#161]
Hello again, 

I have found that you are missing support for [SDL_HapticNumAxes](https://wiki.libsdl.org/SDL_HapticNumAxes) As well as the [HapticEffect struct is just simply an interface](https://github.com/veandco/go-sdl2/blob/master/sdl/haptic.go#L126). The makes it impossible, to set a haptic effects type or any of its associated data.

**Comment by jackyb** [comment]
Hi tanema, thanks for reporting. I have added the missing parts. Could you check if they're working?

**Comment by tanema** [comment]
Hey I see the updates but I won't be able to test them until tomorrow. I will let you know how it goes

**Comment by tanema** [comment]
hey @jackyb, thanks for your quick work it is appreciated. I tried it out today though and there is still a little bit missing. I cannot change the type. I will give you an example of how I normally use this.
for intance if I want to change the effect type in SDL I would have done this

```
effect.type = SDL_HAPTIC_LEFTRIGHT
effect.leftright.length = SDL_HAPTIC_INFINITY
SDL_HapticUpdateEffect(haptic, effect_id, &effect)
SDL_HapticRunEffect(haptic, effect_id, 1)
```

in Go this is all I can do

```
effect.Type() // cannot set type
lr := effect.LeftRight() //this returns the pointer so I am assuming I can update the leftright this way but I havent tested yet
lr.Length = length
haptic.UpdateEffect(effect_, &effect)
haptic.RunEffect(effect_id, 1)
```

I hope this is helpful.

**Comment by jackyb** [comment]
Hi @tanema, sorry for the delay. Just added the method. See if it works for you.

**Comment by tanema** [comment]
It seems to work and all the functionality is great but for some reason my controllers haptics are not registered. SDL GetError() returns "Haptic: There are 0 haptic devices available" so I think this is either a SDL/OSX issue and not a problem with your library. However that also means I cannot fully test it at the moment.
