### ISSUE TITLE
Frame flicker on MacOS

### ISSUE THREAD

**Issue by ArchRobison** [veandco/go-sdl2#162]
I'm having what appears to be an image synchronization problem on MacOS.  I'm wondering if I've done something wrong.  The [example program](https://github.com/ArchRobison/Crosshair/blob/65aa9738d78dabe52ffd25fcd85565bad2ac3cb1/crosshair.go) repeatedly does the following:

1. Read mouse events
2. Fills a texture with red.
3. Overwrites the texture with black and white.
4. Copies and presents the texture to the screen.

I should just see black and white since the red is completely overwritten, and indeed the program works as expected on Windows.  

But when run under MacOS 10.11.1, near the top of the screen, I see red flickering, as if step 4 is still going while step 2 of the next iteration commences.  The key lines of code are [here](https://github.com/ArchRobison/Crosshair/blob/65aa9738d78dabe52ffd25fcd85565bad2ac3cb1/crosshair.go#L116-L144).  If I move the mouse around, the problem temporarily goes away (because of extra delay reading the events?)

Is my code wrong?  I had a [similar issue last year](https://communities.intel.com/message/247607)  with Windows (without using SDL) that was blamed on the OS and eventually fixed.

**Comment by jackyb** [comment]
Hi ArchRobison, I created a C version that mimics the Go version. Could you check if the issue still happens? Just wanted to quickly check if it's a problem with the binding.

https://gist.github.com/jackyb/dbc38cba4cf7a05b55f2

**Comment by ArchRobison** [comment]
I'm having trouble getting the example to link.  (I'm new to MacOS's non-Unix "frameworks'.)  There seems to be no `SDL/SDL2.h` on my system.  I used Brew to install SDL.  There is a `Headers/SDL2.h`, so I tweaked the `#include` to use it.  But now I seem to be missing some fundamental MacOS library on my link line.  Here's a sample:
```
$ cat Makefile 
a.out: crosshair.c
	clang -std=c11 -I/Library/Frameworks/SDL2.framework/Versions/A/Headers/ $< /usr/local/lib/libSDL2.a -framework CoreFoundation 
$ make
clang -std=c11 -I/Library/Frameworks/SDL2.framework/Versions/A/Headers/ crosshair.c /usr/local/lib/libSDL2.a -framework CoreFoundation 
crosshair.c:79:27: warning: use of GNU old-style field designator extension [-Wgnu-designator]
                SDL_Event quitEvent = { type: SDL_QUIT };
                                        ^~~~~
                                        .type = 
1 warning generated.
Undefined symbols for architecture x86_64:
  "_AudioObjectGetPropertyData", referenced from:
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
      _build_device_list in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectGetPropertyDataSize", referenced from:
      _build_device_list in libSDL2.a(SDL_coreaudio.o)
  "_AudioOutputUnitStart", referenced from:
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
```
What do I need to add to my compile line?

**Comment by ArchRobison** [comment]
I got the program to compile.  The C program exhibits the same red flicker program, so it's not the Go bindings.  Do you have recommendations on how best to report the C example to the SDL community? 

P.S. By patiently looking up symbols in the SDK sources, I was able to get the program to link.  I ended up with:
```
clang -std=c11 -I/Library/Frameworks/SDL2.framework/Versions/A/Headers/ crosshair.c /usr/local/lib/libSDL2.a \
-framework CoreAudio \
-framework AudioUnit \
-framework CoreFoundation \
-framework CoreGraphics \
-framework ForceFeedback \
-framework IOKit \
-framework AppKit \
-framework Carbon \
-liconv
```

**Comment by jackyb** [comment]
Hi ArchRobison, it's great you got it to work! I believe the development mailing list is the best way for you to report the problem. http://libsdl.org/mailing-list.php.
