### ISSUE TITLE
SDL_GetDisplayName not implemented

### ISSUE THREAD

**Issue by tanema** [veandco/go-sdl2#163]
Sorry I keep finding these issues but I found another missed method. 

cheers,

**Comment by krux02** [comment]
you can also add a pull request, because implementing missing methods shouldn't be too hard.

**Comment by tanema** [comment]
cheers, you are absolutely right, but having done this before I found it more of a pain because I have to change imports everywhere just to test it.

I figured for one method (that isn't that important, or urgently needed) I could document it here and it could be done when time permits.

however maybe you are right, I should just go ahead and do it

**Comment by krux02** [comment]
for changing the imports, do this in your bash:

    sed -i 's,veandco/go-sdl,tanema/go-sdl,g' $(find . | grep '\.go$')

it renames all imports

**Comment by tanema** [comment]
hey now that is a neat trick! thanks!

**Comment by krux02** [comment]
no problem

**Comment by jackyb** [comment]
It's a welcome issue, @tanema.

I just added the missing function. Check it out on the latest update!

**Comment by tanema** [comment]
It works perfectly, thanks again!
