### ISSUE TITLE
Provide functions accepting arrays for certain methods

### ISSUE THREAD

**Issue by kelcecil** [veandco/go-sdl2#164]
There's situations where you'll want to define your color or other things using an array literal. This can be helpful to DRY up code. What I'd like to see is something like:

```go
black := []uint8{255, 255, 255, 255}
// Later in the code...
renderer.SetDrawColorArray(black)
```

I'll be happy to contribute this where it makes sense if the PR would be considered.

**Comment by krux02** [comment]
go-sdl2 is generally just a wripper around sdl2 with some little changes to make the functions a little bit more go ideomatic. At the moment I do not see why this does make the api more ideomatic.

**Comment by jackyb** [comment]
I added a quick implementation. See what you guys think!

**Comment by kelcecil** [comment]
@jackyb That's pretty much exactly what I did in my fork. Looks good to me!

@krux02 It's not intended to make the wrapper more idiomatic. The desire is to define a color once using a single variable and use the same definition in various places. It eases DRYing up the code.
