### ISSUE TITLE
ShowMessageBox doesn't properly display buttons

### ISSUE THREAD

**Issue by tanema** [veandco/go-sdl2#176]
Hey I was quite happy to see the new message box implementation so I started to play around with it and noticed that it doesn't quite work yet. I just ran the example and I got this for the buttons:
![screen shot 2016-01-15 at 12 05 40 pm](https://cloud.githubusercontent.com/assets/463193/12359466/87bd0754-bb80-11e5-8599-a6925d73840b.png)

If you press the unlabeled one it will crash the example and give a button id of 200.

Also the escape button does not work on it (the return key does though). I tried looking at the code to see if it was a simple fixable problem but could not come up with anything. It must have something to do with changing the data into cptrs but I cannot tell.

go version: go version go1.5.1 darwin/amd64
git SHA: ead8e10e4e972e55f44d99f6e57c82963040f848 (most current)

cheers,

**Comment by aqiank** [comment]
Hi @tanema, I've fixed it in a recent commit. Please try again.

**Comment by tanema** [comment]
It works perfectly @aqiank, it looks like my suspicions were correct as well. Thanks for the fix!
