### ISSUE TITLE
Does sdl.DropEvent work on  Linux?

### ISSUE THREAD

**Issue by godispy** [veandco/go-sdl2#177]
The drag and drop files did not work. 
I further added “sdl.EventState(sdl.DROPFILE,sdl.ENABLE)” but it still did not work.
So, does sdl.DROPFILE work on Linux?

-------------------------------------------------------------------------------------------------
sdl.EventState(sdl.DROPFILE,sdl.ENABLE)
for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
		switch e := event.(type) {
                     case *sdl.DropEvent:
			 println("drop event")
	             default:
			break
		}
}

**Comment by aqiank** [comment]
It works on my Linux/Plasma 5 desktop.

**Comment by godispy** [comment]
it doesn't work on gentoo kde4

**Comment by aqiank** [comment]
Can you try this quick C snippet and see if it works? Just checking if it's really the binding's issue. https://gist.github.com/aqiank/efa6eefcc81157982acc

**Comment by godispy** [comment]
I tried.  It doesn't work.

**Comment by aqiank** [comment]
You should report the issue to the SDL2 devs. Here's their Bugzilla link: https://bugzilla.libsdl.org/

**Comment by godispy** [comment]
thx
