### ISSUE TITLE
Last version doesn't work

### ISSUE THREAD

**Issue by jegor377** [veandco/go-sdl2#185]
>go get -v github.com/veandco/go-sdl2/sdl
github.com/veandco/go-sdl2 (download)
github.com/veandco/go-sdl2/sdl
# github.com/veandco/go-sdl2/sdl
..\github.com\veandco\go-sdl2\sdl\video.go:183:13: expected (unqualified) identifier

**Comment by jegor377** [comment]
I've got windows 10 pro

**Comment by akovaski** [comment]
Works fine for me, Windows 10 Pro, 64 bit, go1.5.2/go1.6

**Comment by aqiank** [comment]
Hi @jegor377, could you go to the directory of the go-sdl2 that you have go-get and run `git show`? Check if the commit really matches the last version (starts with 3105ff129..).

**Comment by jegor377** [comment]
no problem, 
D:\Dane\Projekty\Go\TestSDLCode\src\github.com\veandco\go-sdl2>git show
commit 3105ff129069157b33de6d246abcefb4d7178d45
Merge: a8fc14d d4e82ab
Author: Jacky Boen <aqiank@gmail.com>
Date:   Thu Mar 17 09:53:43 2016 +0800

    Merge pull request #184 from gen2brain/master

    Add mutexes


D:\Dane\Projekty\Go\TestSDLCode\src\github.com\veandco\go-sdl2>

**Comment by jegor377** [comment]
It's windows 10 pro 32bit

**Comment by jegor377** [comment]
and I've got a question. I'm a noob in golang, so I don't know how, but how to get values from sdl.Event? It's an interface and when I used events in C++ it was just "Event.type == SDL_QUIT", but here the compilator says that sdl.Event doesn't have got value like Type or something. How to get an event type value or else? :)

**Comment by jegor377** [comment]
ok, I found how to read events, but the last version still doesn't work.

**Comment by aqiank** [comment]
Okay, I'll install Windows 10 32-bit tonight and see if I can reproduce the issue.

**Comment by jegor377** [comment]
ok :)

**Comment by akovaski** [comment]
Just a suspicion, but this may be caused by using a C struct as a method receiver on line 183. I'm not sure, as that would be a weird thing to be system dependent. Also, I'm not sure why this method is needed, so perhaps a fix would be to remove the method altogether. If it is needed, perhaps a fix would be (re)defining the type for the package ```type cMessageBoxButtonData C.SDL_MessageBoxButtonData``` for use as the method receiver.

**Comment by aqiank** [comment]
@akovaski is right that there shouldn't be a method for a C type (and it returns itself!?). I removed the method so hopefully it's fine now.

**Comment by jegor377** [comment]
Oh, now it's working. thx:)
