### ISSUE TITLE
Joystick and Gamepad axis and buttons all return 0

### ISSUE THREAD

**Issue by 6677** [veandco/go-sdl2#189]
All buttons for both the Joystick and Gamepad classes return 0. All axis return 0. Tested on OSX El Capitan with a dualshock 4, sixaxis and Xbox 360 wired controller, these controllers function in other software.

**Comment by aqiank** [comment]
Did you set up the Joystick correctly? I've updated the 'events' example to show.

**Comment by krux02** [comment]
Can you please give write an example project that we can compile to verify this behavior? Your behavior can also come from wrong initialization or usage of this library, and to exclude it would be very nice if you provide a project on github with your code.

**Comment by 6677** [comment]
The events example also does not function with a DS4, sixaxis or xbox 360 controller. It does function on windows. These controllers are functioning in gangbeasts on steam on OSX.

**Comment by aqiank** [comment]
Perhaps you can provide us with a minimal example that shows the Joystick and the others not working? We'll find out what the issue is.
