### ISSUE TITLE
Errors while getting library from git.

### ISSUE THREAD

**Issue by jegor377** [veandco/go-sdl2#197]
User>go get -v github.com/veandco/go-sdl2/sdl
github.com/veandco/go-sdl2 (download)
github.com/veandco/go-sdl2/sdl
## github.com/veandco/go-sdl2/sdl
37: error: 'SDL_ANDROID_EXTERNAL_STORAGE_READ' undeclared (first use in this function)
37: error: 'SDL_ANDROID_EXTERNAL_STORAGE_WRITE' undeclared (first use in this function)
37: error: 'SDL_AndroidGetInternalStoragePath' undeclared (first use in this function)
37: error: 'SDL_AndroidGetExternalStoragePath' undeclared (first use in this function)
37: error: 'SDL_AndroidGetExternalStorageState' undeclared (first use in this function)
37: error: 'SDL_AndroidGetJNIEnv' undeclared (first use in this function)
37: error: 'SDL_AndroidGetActivity' undeclared (first use in this function)

My computer is Windows 10 32bit Pro with i3

**Comment by veeableful** [comment]
Interesting. If you're using Windows, the code that requires Android-specific shouldn't be part of the compilation AFAIK. I'll try on my 32-bit Windows laptop later and let you know how it goes.

**Comment by jegor377** [comment]
Ok, thank you for response. I will be wait.

**Comment by veeableful** [comment]
Hi jegor377, I was able to get and compile the library using a Windows 10 32-bit machine. Do you have MinGW installed? I assume you're using MinGW version of SDL2.

What I did is basically install Git, Go, and MinGW. Then I put `C:\MinGW\bin` into Path environment variable in Windows. Then I downloaded development libraries of SDL2 (MinGW version) and put the development headers `C:\MinGW\mingw32\include\SDL2` and libraries into `C:\MinGW\mingw32\lib`.

**Comment by jegor377** [comment]
I installed MinGW and SDL2. Library worked correctly before last update. All paths are set correctly. :/ Now I'm using my backup copy of the SDL2 for Go and it's working.

**Comment by veeableful** [comment]
Could you give me the commit that started to cause this problem? I'll check what went wrong in the commit.

**Comment by jegor377** [comment]
Version that I'm already using is the version which has been commited just after solve this issue - https://github.com/veandco/go-sdl2/issues/185

**Comment by veeableful** [comment]
So that is the version that works? What about the one that doesn't? Could you also give me a specific commit reference for the one that fails to compile? Sorry for the back-and-forth :(

**Comment by jegor377** [comment]
It's the newest version what came out - b219958. :)

**Comment by veeableful** [comment]
Just a final check, is your Go at least version 1.5? It seems they just finalized android support on that release. If not, try updating to it and let me know if it works for you.

At the moment, that seems like the only explanation I can come up with.

**Comment by veeableful** [comment]
I added go1.4 build tag so now you should be able to compile the package even on older Go versions.

**Comment by jegor377** [comment]
You're right! I had go1.2.1 version. Now I've updated to 1.6.2 and tried once again and it's all working. Thanks! :)
