### ISSUE TITLE
could not determine kind of name for C.AUDIO_F32

### ISSUE THREAD

**Issue by gasquake** [veandco/go-sdl2#198]
There is more printed out that all relates to audio, how do I fix this?

**Comment by veeableful** [comment]
Heya, that sounds like a build environment problem. What's the version of Go and OS?

**Comment by gasquake** [comment]
go version go1.6.2 windows/386
Windows 10

**Comment by veeableful** [comment]
It seems the preprocessor macro for Windows is wrong in `sdl/sdl_wrapper.h`. I have fixed it in the latest commit. Could you try updating the library and see if the problem comes up again?

**Comment by gasquake** [comment]
What do you mean update the library? I'm very new to go and go's workflow.

**Comment by veeableful** [comment]
You can update the go-sdl2 library by running `go get -v -u github.com/veandco/go-sdl2/sdl`.

But perhaps there's something else that is wrong. What version is the SDL installed on your environment?

**Comment by gasquake** [comment]
The latest from the website.  SDL2-2.0.4 32bit

**Comment by veeableful** [comment]
Are you using MinGW? If not, can you try using MinGW and see if it works for you? Otherwise, I'm not really sure what the problem is with your environment. If you could explain the steps you took to compile go-sdl2 from start to finish, I think it would help.

**Comment by bj4rtmar** [comment]
I'm having similar issues. When I do `go get -v -u github.com/veandco/go-sdl2/sdl` I get:
>github.com/veandco/go-sdl2 (download)
github.com/veandco/go-sdl2/sdl
\# github.com/veandco/go-sdl2/sdl
could not determine kind of name for C.SDL_HINT_MAC_BACKGROUND_APP
could not determine kind of name for C.SDL_HINT_THREAD_STACK_SIZE
could not determine kind of name for C.SDL_HINT_VIDEO_X11_NET_WM_PING
could not determine kind of name for C.SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4

I'm using:
>go version go1.6.3 linux/amd64

go env:
>GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bjartmar/go"
GORACE=""
GOROOT="/home/bjartmar/.gvm/gos/go1.6.3"
GOTOOLDIR="/home/bjartmar/.gvm/gos/go1.6.3/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by veeableful** [comment]
Hi @bj4rtmar, current the package depends on `pkg-config` for Unix-like OSes. Could you try running `pkg-config --cflags --libs sdl2` and see if it works?

**Comment by bj4rtmar** [comment]
this is what i get:
>-D_REENTRANT -I/usr/local/include/SDL2 -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lpthread

**Comment by veeableful** [comment]
I did fix certain flag and function when using SDL 2.0.0 but none of them are related to the ones you encountered. Other than that, all versions of SDL2 (both distro packages from Arch and Ubuntu, and compile-from-source) seem to work on my computer. Have you tried the package from your distro?

**Comment by veeableful** [comment]
@gasquake Could I trouble you to put all output of the errors here?

**Comment by bj4rtmar** [comment]
I'm using ubuntu and I installed SDL2 by doing `sudo apt-get install libsdl2-dev`

The thing is that go-sdl2 used to work fine on my machine when I installed it a few weeks ago (I was able to run a few go-sdl2/examples programs). I only got those errors when I updated go-sdl2 a few days ago

**Comment by bj4rtmar** [comment]
It seems to me that this commit https://github.com/veandco/go-sdl2/commit/3d2cbd79a2157392f7dc6d3d4fad58da2a81b4b8 introduces the errors on my machine.

I did a git checkout on the commit before that one (`git checkout 0ff68e49`) and I got no errors (tested by running examples/texture/texture.go)

**Comment by veeableful** [comment]
If you have installed SDL2 through the package manager, the headers should be located at /usr/include/SDL2 instead of /usr/local/include/SDL2. Could you check if this is true? It might or might not solve the problem.

If that is not the problem, the only thing I can think of is that your SDL2 is version 2.0.4 but somehow doesn't have the hints. If that's the case, I can make the fix by putting dummy version of those hints.

**Comment by bj4rtmar** [comment]
I checked and I have header files in both of these directories..

In /usr/include/SDL2 I grepped for:
SDL_HINT_MAC_BACKGROUND_APP
SDL_HINT_THREAD_STACK_SIZE
HINT_VIDEO_X11_NET_WM_PING
SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4

and they're all defined in the SDL_hints.h file.
But when I grepped for the same strings in /usr/local/include/SDL2 I got no matches.

I'm not sure what this means.. :confused:

**Comment by veeableful** [comment]
It seems like `pkg-config` defaults to using the local one. Could you try uninstalling the local version of SDL2 temporarily and try again? If you still have the SDL2 source, you should be able to run `make uninstall` inside its folder which will uninstall the local version for you.

**Comment by bj4rtmar** [comment]
That did the trick :smile: 

Thanks for the help!

**Comment by veeableful** [comment]
@bj4rtmar  yay! No problem!

**Comment by gasquake** [comment]
These are my error messages: http://puu.sh/qeodS/3d9aaf9a87.png. Thanks for trying to help veeableful :).

**Comment by gasquake** [comment]
By the way when I make a SDL project with C everything works fine. I don't think SDL is to fault, I'll try fully cleaning and reinstalling Go. I'll get back to you; hopefully with a "yay" message ;P.

**Comment by gasquake** [comment]
Ok, I've just reinstalled all of Go and I'm still getting these audio related messages. It's worth to mention that I get them when I try to install each package. Also if it's any help: my Go and SDL versions are both 32bit.

**Comment by veeableful** [comment]
Hi @gasquake, from the error messages it seems like Go could not find the SDL2 headers. Where do you put the SDL2 header files? go-sdl2 expects it to be at somewhere like `C:\MinGW\mingw32\include\SDL2` if you use MinGW.

**Comment by gasquake** [comment]
Oh, then that's definitely the problem. I keep them at C:\SDL. I'll get back to you after I try implementing this.

**Comment by gasquake** [comment]
Wow, that worked! I mean I had to put my other SDL stuff into MinGW as well, but yeah, that did the trick! Thanks so much, by the way you look beautiful in your profile picture. Have a nice day!

**Comment by veeableful** [comment]
Glad I could help! and thanks for the nice compliment! I appreciate it :blush:
