### ISSUE TITLE
No SDL2 gfx bindings

### ISSUE THREAD

**Issue by faiface** [veandco/go-sdl2#199]
Hello!

These SDL2 bindings are absolutely rocking, there's just one thing that's missing for me: the SDL2 gfx extension. Is there any problem adding it in? If not, I'd be very thankful for having it in.

Thanks!

**Comment by veeableful** [comment]
Hey, thanks! We just haven't thought about adding it in. I'll have a go at it tomorrow.

**Comment by faiface** [comment]
That's very cool! Gfx extension is not essential, however, it's very helpful, because it implements things like drawing various shapes, rotating and scaling images and so on. I am currently using SDL2 with Go in my game and of course, I can implement this functionality myself, however, having it implemented through SDL2 gfx is comfortable and potentially faster in performance.

**Comment by veeableful** [comment]
Okay! I've implemented the GFX primitives part on my branch `iskandar`. Hopefully you can start making use of them. I'll add the rest of the functions later :grin:

**Comment by faiface** [comment]
Thank you very much! :D I'll go get 'em and test them as soon as possible.

**Comment by faiface** [comment]
Trying it out and seems to be working fine ;)
