### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by handicraftsman** [veandco/go-sdl2#200]
Will there be something like tutorial/guide? Not just reference.

**Comment by veeableful** [comment]
We haven't thought about creating a tutorial but that's an interesting suggestion I'll work on creating the tutorials :smiley:

**Comment by handicraftsman** [comment]
Thanks. It's cool. Why i am asking? Just because reading references is not very easy when trying to start using library.

**Comment by somatorio** [comment]
as this issue is closed i guess the tutorials are done, could someone point me towards the tutorials? i'm really lost here =x

**Comment by veeableful** [comment]
Hi @somatorio, unfortunately no but we have been thinking about mimicking processing.org's way of writing the tutorials and references. Our API has been changing a lot as well but it's stabilizing so maybe we're close to ready to get a real website up and running!
