### ISSUE TITLE
struct ABI test

### ISSUE THREAD

**Issue by cdelorme** [veandco/go-sdl2#205]
I get failed tests with this message on debian linux:

        struct_test.go:75: type size mismatch: MouseWheelEvent(28) != cMouseWheelEvent(24)

_This may be a platform or sdl version dependent bug, as the same error does not happen on my macbook when using the same go version._

**Comment by phicode** [comment]
my mouse wheel event definition in `/usr/include/SDL2/SDL_events.h` on linux/amd64 contains 7 4-byte fields:

    /**
     *  \brief Mouse wheel event structure (event.wheel.*)
     */
    typedef struct SDL_MouseWheelEvent
    {
        Uint32 type;        /**< ::SDL_MOUSEWHEEL */
        Uint32 timestamp;
        Uint32 windowID;    /**< The window with mouse focus, if any */
        Uint32 which;       /**< The mouse instance id, or SDL_TOUCH_MOUSEID */
        Sint32 x;           /**< The amount scrolled horizontally, positive to the right and negative to the left */
        Sint32 y;           /**< The amount scrolled vertically, positive away from the user and negative toward the user */
        Uint32 direction;   /**< Set to one of the SDL_MOUSEWHEEL_* defines. When FLIPPED the values in X and Y will be opposite. Multiply by -1 to change them back */
    } SDL_MouseWheelEvent;

It seems that the event definition on your platform is missing one of those fields. Can you verify/post which one is missing ?

**Comment by cdelorme** [comment]
@phicode I installed from the debian package manager, so I used `aptitude download` to grab the source, here is the package info /w version:

	$ aptitude show libsdl2-dev
	Package: libsdl2-dev                     
	State: installed
	Automatically installed: no
	Version: 2.0.2+dfsg1-6
	Priority: optional
	Section: libdevel
	Maintainer: Debian SDL packages maintainers <pkg-sdl-maintainers@lists.alioth.debian.org>
	Architecture: amd64
	Uncompressed Size: 4,138 k
	Depends: libsdl2-2.0-0 (= 2.0.2+dfsg1-6), libasound2-dev, libdbus-1-dev, libegl1-mesa-dev, libgl1-mesa-dev, libgles2-mesa-dev, libglu1-mesa-dev, libpulse-dev, libudev-dev, libwayland-dev, libx11-dev,
	         libxcursor-dev, libxext-dev, libxi-dev, libxinerama-dev, libxkbcommon-dev, libxrandr-dev, libxss-dev, libxt-dev, libxv-dev, libxxf86vm-dev
	Conflicts: libsdl-1.3-dev, libsdl-1.3-dev, libsdl2-dev
	Replaces: libsdl-1.3-dev, libsdl-1.3-dev
	Description: Simple DirectMedia Layer development files
	 SDL is a library that allows programs portable low level access to a video framebuffer, audio output, mouse, and keyboard. 
	 
	 This package contains the files needed to compile and link programs which use SDL.
	Homepage: http://www.libsdl.org/

	Tags: devel::library, role::devel-lib

Here is the block from `SDL_events.h`:

	/**
	 *  \brief Mouse wheel event structure (event.wheel.*)
	 */
	typedef struct SDL_MouseWheelEvent
	{
	    Uint32 type;        /**< ::SDL_MOUSEWHEEL */
	    Uint32 timestamp;
	    Uint32 windowID;    /**< The window with mouse focus, if any */
	    Uint32 which;       /**< The mouse instance id, or SDL_TOUCH_MOUSEID */
	    Sint32 x;           /**< The amount scrolled horizontally, positive to the right and negative to the left */
	    Sint32 y;           /**< The amount scrolled vertically, positive away from the user and negative toward the user */
	} SDL_MouseWheelEvent;

_It would appear that I am missing `Uint32 direction;` in my distributions copy._  Does this mean I need to build the latest source manually instead of relying on the distribution packages?

**Comment by cdelorme** [comment]
As a follow-up, I tried adding backports to see if a newer copy was available, but it seems I'm stuck with 2.0.2 if I don't want to do any extra source compilation.

So I grabbed the latest source release from [libsdl.org](https://www.libsdl.org/download-2.0.php), which was only 2.0.4, and proceeded to compile and install.  The instructions were very simple, and **`go test` is passing** with no extra steps after `sudo make install` (_I was worried I would have to override the linker paths since I did not want to uninstall the `libsdl2-dev` package and then also have to download source and compile all related extensions_).

I can't imagine that debian is the only distribution without the absolute latest copy of libsdl, nor do I think it's sensible for tests to fail between patch versions (assuming semantic versioning).

After reading a bit of [cgo documentation](https://golang.org/cmd/cgo/), I am wondering if it might be wise to follow suit with `go-gl/glfw3` and include the libsdl source matching the libraries implementation.  This would both eliminate version mismatches as well as reduce installation efforts on the developers part.  _However I'm not sure whether this forces static compilation, and what the implications would be._

**Since compiling the latest source did fix the tests, if you think the version mismatch issue is best left to be resolved by the developer then this issue can be closed.**

**Comment by veeableful** [comment]
According to the SDL2 [article](https://wiki.libsdl.org/SDL_MouseWheelEvent), it seems like the `direction` field was added only in >= 2.0.4. If that's the case, then I guess we need to add separate version of `MouseWheelEvent`. I'm thinking to use Go's build tags like `go build -tags 2.0.4` and create separate file called `compat_2.0.4.go`or similar.. but I wonder if there's anything that can be more automated. What do you guys think / suggest?

**Comment by cdelorme** [comment]
As you said, that approach isn't very automated and beyond that I don't think `>=` logic is supported in build constraints, so tags probably don't fit the problem very well.  This also means creating and maintaining compatibility layers within the bindings, and that's a bumpy road.

_Since this ticket originated from a test failing, I'd almost say we should leave the source as is and fix the tests._

Suggested alternatives:

- add an explicit requirement to the readme; "Currently working with SDL versions >= 2.0.4"
- add logic to check SDL version from the test when comparing features we know have changed (more work)
- include the exact copy of the source with the project eliminating the chance for version problems to occur

**Comment by cdelorme** [comment]
Worth mentioning, it turns out I did have to compile extensions (so far only toying with SDL_image, just guessing it applies to all) from source to match the compiled SDL2; I'm assuming it has to do with the path I installed to versus the linker paths for the extensions the package manager installed.

**Comment by veeableful** [comment]
Maybe your first option can be valid for tests (e.g. only requires the latest version for tests, otherwise you can use any version you want). The third might be too much because then we're enforcing the users to compile SDL2 from and it will greatly increase our repository size.

The second option seems to me as the best way to test it as it doesn't diverge too much from how we currently do things. I'll have a go at updating the tests to see if it can be done (unless you want to do it!).

**Comment by cdelorme** [comment]
@veeableful I created a [compatibility branch](https://github.com/cdelorme/go-sdl2/tree/compatibility) under my fork to try out option #2, namely I added a disclaimer which we could check versions before printing and only notify folks using older versions.

In particular I disabled the immediate exit behavior in favor of getting all incompatible results, and here is the result when run with version 2.0.2:

	$ go test
	Warning: tests are created for the latest versions of SDL and may occassionally break for older versions when changes are introduced.
	You are running SDL Version 2.0.2
	--- FAIL: TestStructABI (0.00s)
		struct_test.go:75: type size mismatch: AudioSpec(32) != cAudioSpec(32)
		struct_test.go:75: type size mismatch: DisplayMode(24) != cDisplayMode(24)
		struct_test.go:75: type size mismatch: Palette(24) != cPalette(24)
		struct_test.go:75: type size mismatch: PixelFormat(56) != cPixelFormat(56)
		struct_test.go:75: type size mismatch: Surface(96) != cSurface(96)
		struct_test.go:75: type size mismatch: Version(3) != cVersion(3)
		struct_test.go:75: type size mismatch: WindowEvent(24) != cWindowEvent(24)
		struct_test.go:75: type size mismatch: KeyDownEvent(32) != cKeyboardEvent(32)
		struct_test.go:75: type size mismatch: KeyUpEvent(32) != cKeyboardEvent(32)
		struct_test.go:75: type size mismatch: MouseButtonEvent(28) != cMouseButtonEvent(28)
		struct_test.go:75: type size mismatch: MouseMotionEvent(36) != cMouseMotionEvent(36)
		struct_test.go:75: type size mismatch: MouseWheelEvent(28) != cMouseWheelEvent(24)
		struct_test.go:115: index                           name   offset     size
		struct_test.go:118:     0           MouseWheelEvent.Type        0        4
		struct_test.go:118:     1      MouseWheelEvent.Timestamp        4        4
		struct_test.go:118:     2       MouseWheelEvent.WindowID        8        4
		struct_test.go:118:     3          MouseWheelEvent.Which       12        4
		struct_test.go:118:     4              MouseWheelEvent.X       16        4
		struct_test.go:118:     5              MouseWheelEvent.Y       20        4
		struct_test.go:118:     6      MouseWheelEvent.Direction       24        4
		struct_test.go:115: index                           name   offset     size
		struct_test.go:118:     0         cMouseWheelEvent._type        0        4
		struct_test.go:118:     1     cMouseWheelEvent.timestamp        4        4
		struct_test.go:118:     2      cMouseWheelEvent.windowID        8        4
		struct_test.go:118:     3         cMouseWheelEvent.which       12        4
		struct_test.go:118:     4             cMouseWheelEvent.x       16        4
		struct_test.go:118:     5             cMouseWheelEvent.y       20        4
		struct_test.go:94: field not found: "Direction"
		struct_test.go:75: type size mismatch: TextEditingEvent(52) != cTextEditingEvent(52)
		struct_test.go:75: type size mismatch: TextInputEvent(44) != cTextInputEvent(44)
		struct_test.go:75: type size mismatch: JoyAxisEvent(20) != cJoyAxisEvent(20)
		struct_test.go:75: type size mismatch: JoyBallEvent(20) != cJoyBallEvent(20)
		struct_test.go:75: type size mismatch: JoyHatEvent(16) != cJoyHatEvent(16)
		struct_test.go:75: type size mismatch: JoyButtonEvent(16) != cJoyButtonEvent(16)
		struct_test.go:75: type size mismatch: ControllerAxisEvent(20) != cControllerAxisEvent(20)
		struct_test.go:75: type size mismatch: ControllerButtonEvent(16) != cControllerButtonEvent(16)
		struct_test.go:75: type size mismatch: ControllerDeviceEvent(12) != cControllerDeviceEvent(12)
		struct_test.go:75: type size mismatch: TouchFingerEvent(48) != cTouchFingerEvent(48)
		struct_test.go:75: type size mismatch: MultiGestureEvent(40) != cMultiGestureEvent(40)
		struct_test.go:75: type size mismatch: DollarGestureEvent(40) != cDollarGestureEvent(40)
		struct_test.go:75: type size mismatch: DropEvent(16) != cDropEvent(16)
		struct_test.go:75: type size mismatch: UserEvent(32) != cUserEvent(32)
		struct_test.go:75: type size mismatch: SysWMEvent(16) != cSysWMEvent(16)
	--- FAIL: TestTypeABI (0.00s)
		struct_test.go:75: type size mismatch: AudioStatus(4) != cAudioStatus(4)
		struct_test.go:75: type size mismatch: ErrorCode(4) != cErrorCode(4)
		struct_test.go:75: type size mismatch: RendererFlip(4) != cRendererFlip(4)
	FAIL
	exit status 1
	FAIL	github.com/veandco/go-sdl2/sdl	24.142s

_Since the tests previously failed right away using `t.Fatalf()`, I didn't realize but there are a **lot** of edge cases._  Not sure if this would be untenable, but I will submit a PR with a modified version check and disclaimer for now.

**Comment by cdelorme** [comment]
It may be unrelated, but while using SDL 2.0.2 I was unable to receive GameController Device events.  The Joystick Device events worked, and reinstalling 2.0.4 fixed the problem, but this would pretty much confirm my fears that changes in structs per patch version are possibly creating incompatibility within the bindings.

**Comment by veeableful** [comment]
Sometimes, the issues could be from SDL2 itself. Could you provide us the code you have to confirm the issue? I'll check it out.

**Comment by veeableful** [comment]
Sorry, what I mean is the source code you used to test the game controller event.. and what game controller is it?

As for including the source, if you could propose a way we can make it work, definitely.

**Comment by cdelorme** [comment]
Ah, my mistake, I should have understood the context.  I have just uploaded the source [here](https://github.com/cdelorme/go-game).

I was using [this commit](https://github.com/cdelorme/go-game/tree/009ec0c79849f62388deb932d15e2eb8cfa390e9) with additional event logging when I ran into the error, but I think the current version would work just as well.

I don't have much in the readme yet as far as usage instructions, so this should suffice:

	go get -u
	go build
	LOG_LEVEL=debug ./go-game

**Comment by veeableful** [comment]
It seems like I can't get joystick events in your program (it works on `examples/events` though) .

Could you try the following C snippet? Just to check if the game controller events are working for you. It didn't work for me on both 2.0.2 and 2.0.4 (I used Xbox360 controller but could be I'm missing something).

```
#include <SDL2/SDL.h>

int main()
{
	SDL_Init(SDL_INIT_EVERYTHING);
	SDL_Window *window = SDL_CreateWindow("Game Controller", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, 0);
	SDL_bool running = SDL_TRUE;

	SDL_JoystickEventState(SDL_ENABLE);

	while (running) {
		SDL_Event event;

		while (SDL_PollEvent(&event)) {
			switch (event.type) {
			case SDL_QUIT:
				running = SDL_FALSE;
				break;

			case SDL_CONTROLLERAXISMOTION:
				fprintf(stdout, "controller axis motion\n");
				break;

			case SDL_CONTROLLERBUTTONDOWN:
				fprintf(stdout, "controller button down\n");
				break;

			case SDL_CONTROLLERBUTTONUP:
				fprintf(stdout, "controller button up\n");
				break;

			case SDL_CONTROLLERDEVICEADDED:
				fprintf(stdout, "controller device added\n");
				break;

			case SDL_CONTROLLERDEVICEREMOVED:
				fprintf(stdout, "controller device removed\n");
				break;

			case SDL_CONTROLLERDEVICEREMAPPED:
				fprintf(stdout, "controller device remapped\n");
				break;
			}
		}

		SDL_Delay(16);
	}

	SDL_DestroyWindow(window);
	SDL_Quit();
}
```

**Comment by cdelorme** [comment]
I was also testing on linux using xboxdrv and an xbox360 controller.  _I would use xpad if they fixed the lights, but currently it just flashes indefinitely even though the controller input works._

I have my xboxdrv configured to accept up to 4 controllers, and it appears that this pre-emptively creates `/dev/input/` resources, and as a result it always displays 4 messages for devices added when I start my application.  If I stop or restart the xboxdrv, the device removed fires as expected, but powering off the controllers does not.

When using 2.0.2 I was able to get joystick events; this is what I verified from `examples/events.go` before trying to translate to using the game controller type.  It turns out that if you don't `Open()` a joystick or controller, none of the button or axis events fire.

I tried your C code with both 2.0.4 and 2.0.2, and both behaved as expected, displaying 4 added devices but no other events (because that code does not open the controllers).  I would make the modifications to open and track controllers, but my C is a bit rusty and since I verified it from go I don't think it's necessary.  _I was still unable to get any controller events with my program using 2.0.2, but they work fine in 2.0.4._

While it's not finished I pushed changes up that open and track controllers, which should capture the other controller events.  If you want to give that a try you should get logs of the new events firing now.

**Comment by veeableful** [comment]
I added commit that should fix the test issue from a patch I posted on your repository. Please try.

**Comment by cdelorme** [comment]
Just gave this a try, it passed all tests; I will close this ticket.  I still haven't tried code that actually uses these structs but if I encounter anything unexpected I'll open a new ticket.  Thank you very much for the fix!
