### ISSUE TITLE
Multiple Key Down & Hold

### ISSUE THREAD

**Issue by billyninja** [veandco/go-sdl2#208]
The following snippet captures alright a single arrow key pressed over time. But if I press and hold 2 arrow keys simultaneously, it captures both keys for the first "tick", but if I keep them pressed, only one of them keeps capturing. (The goal here is to make my game character walk in diagonals using arrow keys.)

`
println("S-----------------------------------------")

for event = sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
        switch t := event.(type) {
	case *sdl.QuitEvent:
        	return false
	case *sdl.KeyDownEvent:
		println(">", t.Keysym.Sym)
		v := handleKeyEvent(t.Keysym.Sym)
		vel.X += (v.X * 1)
		vel.Y += (v.Y * 1)
	case *sdl.KeyUpEvent:
		handleKeyUpEvent(t.Keysym.Sym)
	}
}
println("F-----------------------------------------")
`

So it would output:

(ARROW_LEFT + ARROW_DOWN PRESSED)
`S-----------------------------------------
 1073741905
1073741904
F-----------------------------------------`

(KEPT EM PRESSED)
`S-----------------------------------------
F-----------------------------------------`

(goes like this for about 1 second)

(KEPT EM PRESSED)
`S-----------------------------------------
1073741905
F-----------------------------------------`
(goes like this indefinitely, printing at every tick)

Dunno if it is a go-sdl2 bug or just me not understanding clearly how PollEvent actually works.

**Comment by billyninja** [comment]
I've managed do get the result I wanted by using the KeyUp event type as the only way to decrease velocity added by a KeyDown event. So if you pressed up arrow key your velocity Y = -1, only when detected a arrow_up keyup that velocity is zeroed (and that is even more efficient than computing KeyDown everytime). That is doing for now. *But* I'm still confused about the way PollEvent works. If it should only capture the exact tick that i'had pressed a certain key down, why it keeps printing after while? Is this OS behavior? To randomly repeat ONE arbitrary (and not all that are hold) key event if it keeps pressed?

**Comment by veeableful** [comment]
Sorry for the late reply! Been really busy for the past three weeks..

I've created a simple C version. It does seem to be the normal behaviour.

```
#include <SDL2/SDL.h>

int main()
{
        SDL_Window *window;
        SDL_Event event;
        SDL_bool running = SDL_TRUE;

        window = SDL_CreateWindow("Issue #208", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1024, 768, 0);

        while (running) {
                while (SDL_PollEvent(&event)) {
                        switch (event.type) {
                        case SDL_QUIT:
                                running = SDL_FALSE;
                                break;

                        case SDL_KEYDOWN:
                                fprintf(stdout, "key down: %d \n", event.key.keysym.sym);
                                break;

                        case SDL_KEYUP:
                                fprintf(stdout, "key up: %d \n", event.key.keysym.sym);
                                break;

                        default:
                                break;
                        }
                }
        }

        SDL_DestroyWindow(window);
        SDL_Quit();
}
```
