### ISSUE TITLE
Race conditions in queue/goroutine examples

### ISSUE THREAD

**Issue by monkeybird** [veandco/go-sdl2#209]
I noticed a few potential race conditions in the `examples/render_goroutine` and `examples/render_queue` sources. Specifically the following is not safe and will not behave as intended when `GOMAXPROCS > 1`.

```
	sdl.CallQueue <- func() {
		window, err = sdl.CreateWindow(WindowTitle, sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED, WindowWidth, WindowHeight, sdl.WINDOW_OPENGL)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create window: %s\n", err)
		return 1
	}
	defer func() {
		sdl.CallQueue <- func() {
			window.Destroy()
		}
	}()
```

This goes for the creation of the renderer as well. The error checking code expects the queued function to already be executed. There is no guarantee that this is the case. Which means it may incorrectly report that there is no error. It then happily continues running the demo code, even though the window or renderer might not be initialized.

For correct behaviour, leave the initialization of the window and renderer in the main thread.

**Comment by monkeybird** [comment]
Additionally, setting `running = false` in a goroutine, is also not safe. I would suggest either using a quit channel to signal exiting of the main loop, or use an atomic flag and read/write it using the `sync/atomic' package.

**Comment by veeableful** [comment]
Sorry for the late reply! been really busy for the past three weeks..

I added a blocking helper to run functions on the main thread so now it should be guaranteed to finish. Also added a mutex for the running variable.

I'm not familiar with the `sync/atomic` package but patch is welcome!
