### ISSUE TITLE
Heavy allocation in SDL_PollEvent

### ISSUE THREAD

**Issue by shepheb** [veandco/go-sdl2#211]
I'm working on a Gameboy emulator. I was getting ~28-30 fps instead of the targeted 60, so I started profiling. Lots of time was being spent in the allocator and GC, so I profiled memory use. 99.99% of it came from `sdl.PollEvent()`, which I was calling from the main loop.

I tried patching it locally to use a single global `C.SDL_Event`, and that reduced the allocation to 0.

I've since made this a much smaller problem by using `HasEvent(s)` to only read if there are events I care about, but it still seems unfortunate. I know you probably don't want to change the API back to receiving a pointer from the user, but is there any harm in using a global event? (`SDL_PollEvent` is locked to the video thread.) If that's unacceptable, what about a separate call where I pass in the pointer?

**Comment by billyninja** [comment]
Your issue caught my attention, since I'm as well calling sdl.PollEvent() every frame in my game. But I haven't visualized your solution quite clearly (especially the global C.SDL_EVENT part). Could you share some snippet(s)?

**Comment by shepheb** [comment]
I mean changing `PollEvent` from

``` go
// PollEvent (https://wiki.libsdl.org/SDL_PollEvent)
func PollEvent() Event {
	var cevent C.SDL_Event
	ret := C.SDL_PollEvent(&cevent)
	if ret == 0 {
		return nil
	}
	return goEvent((*CEvent)(unsafe.Pointer(&cevent)))
}
```
to

``` go
var cevent C.SDL_Event

// PollEvent (https://wiki.libsdl.org/SDL_PollEvent)
func PollEvent() Event {
	ret := C.SDL_PollEvent(&cevent)
	if ret == 0 {
		return nil
	}
	return goEvent((*CEvent)(unsafe.Pointer(&cevent)))
}
```

The API is the same, except that the returned pointer is only valid until the next call to `PollEvent`.

**Comment by billyninja** [comment]
You patched in a go-sdl2 fork of yours?

**Comment by shepheb** [comment]
Just in my local `$GOROOT`. It's an easy enough change to make locally.

**Comment by veeableful** [comment]
Hi @shephep, I've added your solution to the master branch. Thanks for reporting this issue!

**Comment by shepheb** [comment]
Thanks!
