### ISSUE TITLE
Window Doesn't Respond Sometimes

### ISSUE THREAD

**Issue by shabinesh** [veandco/go-sdl2#212]
I buillt a small 2D game. However, the window becomes non-responsive to any events. The strange part is it works sometimes and doesn't most of the time. I am on a OSX Yoesmite and using go-1.7.

Below is the main function

```
func main() {
	/* Initilize SDL with all its subsystems.
	create a Game instance if Intilization is a success */
	err := sdl.Init(sdl.INIT_EVERYTHING)
	if err != nil {
		panic(err)
	}

	g := new(Game)
	g.init("Flappy")
	g.drawTitle("Flappy Bird")
	g.clear()

	var event sdl.Event

	go g.play() //  Keep moving the background

	running := true
	fmt.Println("Waiting on events")
	for running {
		for event = sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
			switch event.(type) {
			case *sdl.QuitEvent:
				running = false
				break
			case *sdl.KeyDownEvent:
				g.handleKeyEvent(event.(*sdl.KeyDownEvent))
			}
		}
	}
	quito()
}
```

**Comment by veeableful** [comment]
Hi @shabinesh, usually the main loop needs an `SDL_Delay(16)` or something similar at the end of the block. Could try and see if it works?

**Comment by shabinesh** [comment]
@veeableful Thanks for getting back quick. I tried & I still seem to be struck. I increased the delay upto 100ms. Just to add some more information, animation just works fine every time, but the window doesn't capture any events and window controls doesn't work. PollEvent() returns nil, but sometimes everything works fine and captures all the events. Does this tick you a common mistake or could it be a bug?

**Comment by veeableful** [comment]
@shabinesh Hmm..I guess it might be a bug. Could you try compiling the following C code and Go code to see if only the Go code produces the issue?

**C**
```
#include <SDL2/SDL.h>

int main(int argc, char **argv) {
        SDL_Init(SDL_INIT_EVERYTHING);

        SDL_Window *window = SDL_CreateWindow("Flappy", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 800, 600, SDL_WINDOW_SHOWN);
        if (!window) {
                fprintf(stderr, "main: %s\n", SDL_GetError());
                return -1;
        }

        SDL_bool running = SDL_TRUE;

        while (running) {
                SDL_Event event;
                while (SDL_PollEvent(&event)) {
                        switch (event.type) {
                        case SDL_QUIT:
                                running = SDL_FALSE;
                                break;

                        case SDL_KEYDOWN:
                                fprintf(stdout, "main: %s\n", "got keydown event");
                                break;
                        }
                }

                SDL_Delay(16);
        }

        SDL_DestroyWindow(window);

        SDL_Quit();
}
```

**Go**
```
package main

import (
        "fmt"
        "os"

        "github.com/veandco/go-sdl2/sdl"
)

func main() {
        sdl.Init(sdl.INIT_EVERYTHING)

        window, err := sdl.CreateWindow("Flappy", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED, 800, 600, sdl.WINDOW_SHOWN)
        if err != nil {
                fmt.Println("main:", err)
                os.Exit(1)
        }

        running := true

        for running {
                for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
                        switch event.(type) {
                        case *sdl.QuitEvent:
                                running = false

                        case *sdl.KeyDownEvent:
                                fmt.Println("main:", "got keydown event")
                        }
                }

                sdl.Delay(16)
        }

        window.Destroy()

        sdl.Quit()
}
```

**Comment by shabinesh** [comment]
Hi @veeableful , Thanks a ton, It does work in both C and Go, However I am wondering if scope of the `window SDL.Window` to the main loop matter to the PollEvent. If you see my code I create my window inside `g.init("Flappy")` ,

**Comment by veeableful** [comment]
Hi @shabinesh, I'm not 100% sure of SDL2's behavior, but I believe it should be okay if you create SDL2 window on the same thread as main() and have a living reference to it during the SDL_PollEvent().

**Comment by shabinesh** [comment]
@veeableful Thanks. It seems to work sdl.window instance is in the scope of the main thread.  But seldom i hit the same problem of window not responding. I was wondering if 100% CPU consumption of PollEvent() is a problem and changed to WaitEvent(), but no waiver. But thanks to you 90% of the problem is solved 👍 :)

**Comment by veeableful** [comment]
@shabinesh Glad to hear that it's almost solved! Could you then create a minimal example that reproduces the problem? Perhaps then I can see what's causing the issue.

**Comment by shabinesh** [comment]
@veeableful Un/fortunately I couldn't reproduce that error, This sometimes happen in the actual game , Killing and restarting the program makes it work. But actually the initial problem might be due to the program losing scope of the window, 

```
package main

import (
	"fmt"

	"github.com/veandco/go-sdl2/sdl"
)

type Game struct {
	state int
}

func (g *Game) init() {
	window, err := sdl.CreateWindow("Flappy",
		sdl.WINDOWPOS_CENTERED,
		sdl.WINDOWPOS_CENTERED,
		800,
		600,
		sdl.WINDOW_SHOWN)
	if err != nil {
		fmt.Print("Error creating window")
	}
	_, _ = sdl.CreateRenderer(window, -1, sdl.RENDERER_ACCELERATED)
}

func (g *Game) handleKeyEvent(e *sdl.KeyDownEvent) {
	fmt.Println("Key Event Occured", e)
}

func main() {
	err := sdl.Init(sdl.INIT_EVERYTHING)
	if err != nil {
		panic(err)
	}

	g := new(Game)
	g.init()

	var event sdl.Event

	running := true
	fmt.Println("Waiting on events")
	for running {
		for event = sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
			switch event.(type) {
			case *sdl.QuitEvent:
				running = false
				break
			case *sdl.KeyDownEvent:
				g.handleKeyEvent(event.(*sdl.KeyDownEvent))
			}
		}
	}
	sdl.Quit()
}
```

The window gets created inside the init() method, the garbage collection could could actually kick in to remove the local window references which in turn should make window non responsive.. However I could not reproduce that even with the program above which tries to prove my hypothesis.

**Comment by Grandzam** [comment]
This issue happens as well with my project, and notably if I run the events.go example it also becomes unresponsive after a while. I will try to fix the problem with my game using the above solution and come back, but definitely your own example needs to be changed.

**Comment by Grandzam** [comment]
Ok there was no solution to the problem above. This is a really great project but I will have to throw away all my code and use something else if this problem doesn't get fixed. I definitely cannot have this problem when I release.

**Comment by veeableful** [comment]
Hi @Grandzam, sorry to hear that. I'll try the events example on Windows 10 using go 1.6 and see if I can reproduce it.

**Comment by Grandzam** [comment]
If it works for you I think it might be an installation thing.

I'm also using gcc 5.1 so maybe I need to update it?

**Comment by veeableful** [comment]
It seems like I can't run even a simple SDL2 program on my side. Will experiment around and let you know once I found a solution.

**Comment by veeableful** [comment]
@Grandzam, I experience the same thing (I hope?) and it seems like adding an `SDL_Delay()` in the loop fixes the stuttering. Could you confirm?

**Comment by Grandzam** [comment]
Which loop? I have one in my main loop but I don't think I have one in my event loop. I don't have access to my code right now, I'll confirm in 4 or 5 hours.

**Comment by veeableful** [comment]
Yeah, it should be in the main loop. But that's strange if it still happens. Could you check with the latest events example? (I pushed to git)

**Comment by Grandzam** [comment]
events.go works for me now. However, my program still doesn't work properly (actually, it already had sdl.Delay)

I kept working on it and condensed the bug down to this. I made a few observations playing around with this code but nothing conclusive and I want to confirm that this doesn't work for you first. Put a image path in img.Load() and try it out.

```
/*      This program should make your window unresponsive after running it for a while.
        This (probably) means that PollEvent() will always return nil and Windows complains
        because your window is not responding to events
        The program will keep running everything outside the event loop.

        It should take about 15 seconds to 2 minutes to go unresponsive (usually closer to 15 seconds)
*/
package main

import (
        "fmt"
        "github.com/veandco/go-sdl2/sdl"
        "github.com/veandco/go-sdl2/sdl_image"
        "os"
)

func main() {
        sdl.Init(sdl.INIT_EVERYTHING)

        /** set up display **/
        window, err := sdl.CreateWindow("Flappy", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED, 800, 600, sdl.WINDOW_SHOWN)
        if err != nil {
                fmt.Println("window error:", err)
                os.Exit(1)
        }

        var renderer *sdl.Renderer
        renderer, err = sdl.CreateRenderer(window, -1, sdl.RENDERER_ACCELERATED)
        if err != nil {
                fmt.Println("renderer error:", err)
                os.Exit(2)
        }
	defer renderer.Destroy()

        /** load our PNG **/
        var mySurface *sdl.Surface
        var myTexture *sdl.Texture

        mySurface, err = img.Load("RDNassets/grasstile.png")
        if err != nil {
                fmt.Println("error creating surface:", err)
                os.Exit(3)
        }
        defer mySurface.Free()
        myTexture, err = renderer.CreateTextureFromSurface(mySurface)
        if err != nil {
                fmt.Println("error creating texture:", err)
                os.Exit(4)
        }
        defer myTexture.Destroy()

        //the program will print when this reaches 0
        printMessageCount := 20

        /** start main loop **/
        running := true
        for running {
                for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
                        switch event.(type) {
                        case *sdl.QuitEvent:
                                running = false
                        }
                }
                renderer.Clear()

                /* display our image in a loop, like we would in a game
                   (such as my game) to make a room out of a tileset

                   many of them are drawn offscreen but that isnt unusual for a game */
                for i := 0; i < 20; i++ {
                        for j := 0; j < 20; j++ {
                                dst := sdl.Rect{int32(i)*100,
                                                int32(j)*100,
                                                100,
                                                100}
                                renderer.Copy(myTexture, nil, &dst)
                        }
                }
                renderer.Present()

                //this will keep printing after the window goes unresponsive
                printMessageCount--
                if printMessageCount <= 0 {
                        fmt.Println("Still running...",sdl.GetTicks())
                        printMessageCount = 20
                }

                sdl.Delay(16)
        }

        window.Destroy()

        sdl.Quit()
}
```

**Comment by Grandzam** [comment]
Does this code work fine for you? Is there an issue with this code or the sdl binding?

**Comment by veeableful** [comment]
Hi @Grandzam, sorry for late reply!

I experience the same result on my Windows 10 virtual machine. I find that locking the OS thread through `runtime.LockOSThread()` "fixes". I'm guessing anything that does rendering needs to have it OS thread locked according to the SDL FAQ: https://wiki.libsdl.org/FAQDevelopment. Let me know if it solves your issue.

**Comment by Grandzam** [comment]
Sorry about that, I saw that and was planning to try it, but forgot about it. My program works perfectly now.
