### ISSUE TITLE
AudioCVT not usable

### ISSUE THREAD

**Issue by wtlangford** [veandco/go-sdl2#214]
There doesn't appear to be a way to allocate the buffer space for the `AudioCVT` struct.
In C, you would do this:
```C
// Change 1024 stereo sample frames at 48000Hz from float32 to int16.
SDL_AudioCVT cvt;
SDL_BuildAudioCVT(&cvt, AUDIO_F32, 2, 48000, AUDIO_S16, 2, 48000);
SDL_assert(cvt.needed); // obviously, this one is always needed.
cvt.len = 1024 * 2 * 4;  // 1024 stereo float32 sample frames.
cvt.buf = (Uint8 *) SDL_malloc(cvt.len * cvt.len_mult);
// read your float32 data into cvt.buf here.
SDL_ConvertAudio(&cvt);
// cvt.buf has cvt.len_cvt bytes of converted data now.
```
(Source: https://wiki.libsdl.org/SDL_AudioCVT)

On the Go side, there doesn't appear to be a way to actually store a reference to the buffer in the `AudioCVT`.  The `.Buf()` function returns a slice with its length and capacity set, but the data pointer is still `nil`, so any accesses to that slice result in a segmentation fault.

So, unless I'm missing something, there are a few options:
1. Expose a way to set `buf` so that we can fill the slice returned by `.Buf()` (I consider this a more dangerous option because calling `append()` with the returned slice can cause our original data pointer to become invalid).
2. Make `ConvertAudio()` take a slice of appropriate length/capacity and place its data pointer into the `AudioCVT` for the duration of the cgo call.
3. Do struct translation for cgo calls that take an `AudioCVT`.

Thoughts?

**Comment by veeableful** [comment]
Hiya, sorry for the late reply (merry christmas and happy new year!).

I'm thinking of giving user a couple interfaces for allocating and freeing the buffer `AllocBuf()` and `FreeBuf()`. I think it's more streamlined than making `buf` public and doesn't disturb the SDL interface of `ConvertAudio()`. But if it's a problem, then I think I like option 1 the best because it's the most straightforward solution and gives user a lot of control.

...actually yeah, let's try option 1! I've push a commit that make `buf` public as `Buf` and renamed the `Buf()` method to `BufAsSlice()`. Let me know if it works for you!

**Comment by wtlangford** [comment]
No worries on the delay, its a busy season for everyone.

ConvertAudio takes a pointer to go memory, so any pointers in that memory must not be pointers to go memory. So we need `buf` to point to C memory. Unfortunately, unless we `include "C"` in the calling code for `C.malloc` or expose `sdl.Malloc` and `sdl.Free`, there's no good way to provide a C buffer. I'm somewhat against exposing the SDL_Malloc and SDL_Free functions, because they sometimes use a custom malloc implementation. I'd probably recommend adding those buffer functions you were describing.

**Comment by veeableful** [comment]
Done! I suppose I'll let the user decide whether to do something with `Buf` directly using `import "C"` or use the functions provided. I also made `Buf` into `unsafe.Pointer` to make it clearer that it should point to memory from C.

**Comment by wtlangford** [comment]
This works! There's an odd point where you need to set `LenCVT = Len` in order for the slice from `BufAsSlice()` to be useful for filling with source data (`len_cvt` is really an out-value from `ConvertAudio` telling you how much of the buffer is the output), but I don't see a better option, because `LenCVT` is definitely the right value to use as the length of the slice, and I'm not going to assert that `LenCVT == 0` is not a valid output from `ConvertAudio`.  Maybe there should be some kind of comment to this effect, though, since it's surprising.

Either way, I think this closes the issue.  Thanks!
