### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by ctwoodward** [veandco/go-sdl2#217]
Followed installation instructions  given for Windows and I can't get it to compile.

Used MSYS2 to install:

> pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2{,_mixer,_image,_ttf}

That runs fine.

```
$ pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2{,_mixer,_image,_ttf}
warning: mingw-w64-x86_64-gcc-6.2.0-2 is up to date -- reinstalling
warning: mingw-w64-x86_64-SDL2-2.0.5-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-SDL2_mixer-2.0.1-3 is up to date -- reinstalling
warning: mingw-w64-x86_64-SDL2_image-2.0.1-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-SDL2_ttf-2.0.14-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (5) mingw-w64-x86_64-SDL2-2.0.5-1  mingw-w64-x86_64-SDL2_image-2.0.1-1
             mingw-w64-x86_64-SDL2_mixer-2.0.1-3
             mingw-w64-x86_64-SDL2_ttf-2.0.14-1  mingw-w64-x86_64-gcc-6.2.0-2

Total Installed Size:  116.64 MiB
Net Upgrade Size:        0.00 MiB
 
:: Proceed with installation? [Y/n] Y
(5/5) checking keys in keyring                     [#####################] 100%
(5/5) checking package integrity                   [#####################] 100%
(5/5) loading package files                        [#####################] 100%
(5/5) checking for file conflicts                  [#####################] 100%
(5/5) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/5) reinstalling mingw-w64-x86_64-gcc            [#####################] 100%
(2/5) reinstalling mingw-w64-x86_64-SDL2           [#####################] 100%
(3/5) reinstalling mingw-w64-x86_64-SDL2_mixer     [#####################] 100%
(4/5) reinstalling mingw-w64-x86_64-SDL2_image     [#####################] 100%
(5/5) reinstalling mingw-w64-x86_64-SDL2_ttf       [#####################] 100%


```
When I run go get -v github.com/veandco/go-sdl2/sdl  I get this error:

```
github.com/veandco/go-sdl2 (download)
github.com/veandco/go-sdl2/sdl
# github.com/veandco/go-sdl2/sdl
work\src\github.com\veandco\go-sdl2\sdl\yuv_sw_c.go:17: undefined: Surface
work\src\github.com\veandco\go-sdl2\sdl\yuv_sw_c.go:18: undefined: Surface
```

And then  after that sdl_image, sdl_ttf all give the same error:

```
github.com/veandco/go-sdl2/sdl
# github.com/veandco/go-sdl2/sdl
work\src\github.com\veandco\go-sdl2\sdl\yuv_sw_c.go:17: undefined: Surface
work\src\github.com\veandco\go-sdl2\sdl\yuv_sw_c.go:18: undefined: Surface

```
sdl_mixer gives this message:

`can't load package: package github.com/veandco/go-sdl2/sdl_mixer: no buildable Go source files in C:\users\ctwoo\work\src\github.com\veandco\go-sdl2\sdl_mixer
`
I feel like I'm missing something very fundamental but can't figure it out.  When I look in surface.go I can see the definition of Surface so I don't know why the compiler doesn't see it when looking at the other files.

**Comment by veeableful** [comment]
Hmm that is interesting.. it didn't happen to me on Windows 10 64-bit. How did you install Go? I used `pacman -S mingw-w64-x86_64-go`.

**Comment by vinzBad** [comment]
Had similar problems last week, heres my writeup on building go-sdl2 on windows: https://github.com/vinzBad/go-sdl2-tut/blob/master/00_preparation/windows.md

**Comment by veeableful** [comment]
Hey @vinzBad, thanks for the detailed instructions! May I appropriate it as part of the README?

**Comment by vinzBad** [comment]
Of course! Maybe review it before adding? Because I was the only tester of this "guide" so far ;)

**Comment by robert-wallis** [comment]
The `set CGO_CFLAGS=-ID:\dev\mingw64\mingw64\include` part of your guide just helped me get my `go get` command to compile.  Thank you @vinzBad 

Incidentally, I compiled from source and manually copied the files into the `mingw64` directories.

**Comment by veeableful** [comment]
I tested @vinzBad's guide on a fresh Windows 10 64-bit VM and it seems to work for me. However, it seems like some steps are not strictly required or could be done another way so I did another test from clean snapshot and skipped / reworked some steps to be simpler (hopefully). If one of you has the time, please check the updated Windows instruction in README.md and let me know if something doesn't work.

PS. It looks horrible right now but if somebody knows how to make it look pretty on Github, I'd love to have your pull request :stuck_out_tongue:

**Comment by vinzBad** [comment]
Great to hear @robert-wallis  :) 

@veeableful Thanks for reviewing my guide :+1: It's interesting that you didn't need to set CGO_FLAGS, maybe there are some hardcoded paths in the mingw64 toolchain?

**Comment by veeableful** [comment]
@vinzBad No problem! Thank you for the guide. I'm guessing adding the second `bin` folder:
`C:\Program Files\mingw-w64\x86_64-6.3.0-win32-seh-rt_v5-rev1\mingw64\x86_64-w64-mingw32\bin`

 to the Path environment variable makes it works because the tools in the `bin` folder have the standard include paths set.

**Comment by robert-wallis** [comment]
I just tried to add that second inner bin (`C:\MinGW64\mingw64\x86_64-w64-mingw32\bin`) to my `PATH`, but it still couldn't find the include folder in my case.  Although I didn't follow the same MinGW install instructions so maybe it's something else.

```Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Family>go get github.com/veandco/go-sdl2/sdl
# github.com/veandco/go-sdl2/sdl
In file included from Documents\Dev\GO\src\github.com\veandco\go-sdl2\sdl\audio.go:4:0:
./sdl_wrapper.h:2:23: fatal error: SDL2/SDL.h: No such file or directory
  #include <SDL2/SDL.h>
                       ^
compilation terminated.

C:\Users\Family>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\Users\Family\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\MinGW64\mingw64\bin;C:\MinGW64\mingw64\x86_64-w64-mingw32\bin;C:\MinGW\bin;C:\Program Files\Mercurial\;C:\Program Files (x86)\Vim\vim80;C:\Android\SDK\tools;C:\Android\SDK\platform-tools;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Go\bin;C:\Users\Family\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Family\AppData\Local\Programs\Python\Python35\;C:\Users\Family\AppData\Local\Microsoft\WindowsApps;C:\Users\Family\Documents\Dev\GO\bin

C:\Users\Family>set CGO_CFLAGS=-IC:\MinGW64\mingw64\include

C:\Users\Family>go get github.com/veandco/go-sdl2/sdl

C:\Users\Family>
```

**Comment by robert-wallis** [comment]
False alarm, I just found out that I "installed" SDL2 in the wrong directory.  Following the instructions on the new README I moved the SDL lib and include files into the `C:\MinGW64\mingw64\x86_64-w64-mingw32` folder, they were in the one above that `C:\MinGW64\mingw64`  Then, after deleting go-sdl2, I tried in a new cmd window without CGO_FLAGS set, and it worked perfectly.

So the README instructions look good to me, :shipit:

**Comment by veeableful** [comment]
Amazing. Thanks @robert-wallis for taking the time to retry the installation process again. Much appreciated!
