### ISSUE TITLE
Compile errors on Linux

### ISSUE THREAD

**Issue by r41d** [veandco/go-sdl2#219]
I get several compile errors due to some paramters not casted right.
I fixed it in my form [HERE](https://github.com/r41d/go-sdl2/commit/57cc93b93e086cadb32b82e88d3b81fe94d425a2) and this works for me.

Does anyone have an idea why this problem occurs on my system.
System is Gentoo with Go 1.8 and media-libs/sdl2-gfx-1.0.1

**Comment by veeableful** [comment]
It seems like Go 1.8 introduced a certain change in the compiler that caused the issue although I can't find it in the release note. Go 1.7 seems to work fine for me.

Could you submit your fix as a pull request?

**Comment by r41d** [comment]
Just did :)
