### ISSUE TITLE
Wrong constant values in sdl_gfx package

### ISSUE THREAD

**Issue by icza** [veandco/go-sdl2#221]
The [sdl_gfx.go](https://github.com/veandco/go-sdl2/blob/master/sdl_gfx/sdl_gfx.go) file contains wrong constant values:

	// FPS
	const (
		FPS_UPPER_LIMIT = 200
		FPS_LOWER_LIMIT = 200
		FPS_DEFAULT     = 30
	)

`FPS_LOWER_LIMIT` should be something small (no greater than `FPS_DEFAULT`), most likely `1`.

And:

	const (
		SMOOTHING_OFF = 0
		SMOOTHING_ON  = 0
	)

`SMOOTHING_ON` should be `1`.

**Comment by chaeyoungsong** [comment]
:open_mouth: 

Fixed it in the latest commit. Thanks!

**Comment by icza** [comment]
Cool, thanks for the fast fix :)
