### ISSUE TITLE
support DequeueAudio

### ISSUE THREAD

**Issue by gengen1988** [veandco/go-sdl2#222]
see: https://wiki.libsdl.org/SDL_DequeueAudio

**Comment by chaeyoungsong** [comment]
Hi @gengen1988, thanks for reporting this. I just added the binding in latest commit 👍

**Comment by deadprogram** [comment]
Hello @gengen1988 & @chaeyoungsong 

This latest updated is giving us build errors.

Can we please get a pragma warning but no build error for this, in the same fashion that https://github.com/veandco/go-sdl2/pull/215 corrected?

Thank you!

**Comment by veeableful** [comment]
Should be fixed in the latest commit e97e53b.

**Comment by deadprogram** [comment]
Thanks @veeableful that did it.
