### ISSUE TITLE
sdl_image.SavePNG() always returns an error.

### ISSUE THREAD

**Issue by GrundleTrundle** [veandco/go-sdl2#227]
I can't do a pull request for this now, but it looks like it's a typo.  The code in SavePNG() does this: 

`C.free(unsafe.Pointer(_file))`

`_file` is used on the next line after that, I suspect that free is supposed to be deferred.

**Comment by veeableful** [comment]
Hi @GrundleTrundle, the issue has been fixed. Could you try updating the package?

**Comment by GrundleTrundle** [comment]
Yes, that did it.  Thanks!
