### ISSUE TITLE
gfx.StringRGBA with multiple windows/renderers

### ISSUE THREAD

**Issue by DanTulovsky** [veandco/go-sdl2#229]
Hi.

(I am not confident there is not a bug in my code somewhere, but I can't seem to find it.)  If I create two windows and two renderers that run at the same time, or one after the other, the gfx.StringRGBA(r, ...) call only works on the first window.  

Calling it on the second renderer/window, results in one of two errors messages.

If the first window is still running (Destroy() hasn't been called): "Texture was not created with this renderer"

If the first window is no longer running: "Invalid texture"

This leads me to believe that the second renderer is trying to use the first window.  

Now, other operations work fine for both windows (in sequence or at the same time).  For example, r.FillRect(box) works just fine on the same renderer 'r' in the same function block.  While gfx.StringRGBA(r, ...) fails with the errors above.

Has anyone seen anything like this? Here's a small program that reproduces the error:

https://github.com/DanTulovsky/sdl2/blob/master/gfx2_example.go

The structure is basically what I have in the real program.  The error when win(2) is called is:

2017/06/25 12:13:26 error: Texture was not created with this renderer

Thanks
Dan

**Comment by veeableful** [comment]
Hi @DanTulovsky, it seems to be a behavior from SDL2 or SDL2_gfx itself. I managed to reproduce with the native implementation [here](https://paste.fedoraproject.org/paste/hJfSyRi4Vk-7lWca~oJ5xg).

Perhaps there's a specific way to do it that I'm not aware of but I'll label this as SDL2 issue for now.

**Comment by veeableful** [comment]
Hi again @DanTulovsky, according to the [reply](https://discourse.libsdl.org/t/sdl2-gfx-not-working-with-multiple-windows/22713/2) by a poster in the SDL forums, it seems you need to do `gfx.SetFont(nil, 0, 0)` to clear character texture cache in SDL2_gfx after calling the `gfx.StringRGBA()` function.

Note that I also just updated the `gfx` package so the function is `gfx.SetFont()` instead of `gfx.GFXPrimitiveSetFont()` for convenience. So you may need to update the Go package if you haven't already.

The update also fixes an issue where you can't pass nil value into the `gfx.SetFont()` as it would segfaults if you do that.

**Comment by DanTulovsky** [comment]
Thank you for your help.  I don't see gfx.SetFont() yet, but using gfx.GFXPrimitiveSetFont() with your patch for nil seems to work.  It seems that calling this too often is not a good idea. The first obvious place I put this into in my real code, a section that gets called a lot, promptly resulted in my mac locking up (reproducible every time).

I moved it into the main for() loop that does the screen refresh, and that seems to work ok.

btw, if "github.com/veandco/go-sdl2/sdl_gfx" is imported from nested files, it produces the following error (additional functions removed for readability):

# command-line-arguments
/usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
duplicate symbol __cgo_544454c2de7c_Cfunc_SDL_framerateDelay in:
    /var/folders/46/f69_gjnn0971sgpdwn3xb9cm0000gn/T/go-link-227181855/000004.o
    /var/folders/46/f69_gjnn0971sgpdwn3xb9cm0000gn/T/go-link-227181855/000005.o
duplicate symbol __cgo_544454c2de7c_Cfunc_SDL_getFramerate in:
    /var/folders/46/f69_gjnn0971sgpdwn3xb9cm0000gn/T/go-link-227181855/000004.o
    /var/folders/46/f69_gjnn0971sgpdwn3xb9cm0000gn/T/go-link-227181855/000005.o
duplicate symbol __cgo_544454c2de7c_Cfunc_SDL_imageFilterAbsDiff in:
    /var/folders/46/f69_gjnn0971sgpdwn3xb9cm0000gn/T/go-link-227181855/000004.o
    /var/folders/46/f69_gjnn0971sgpdwn3xb9cm0000gn/T/go-link-227181855/000005.o

e.g.

file1 (package main):

import "github.com/veandco/go-sdl2/sdl_gfx"
import "local/file2"

file2 (package other):

import "github.com/veandco/go-sdl2/sdl_gfx"

**Comment by veeableful** [comment]
Ah I didn't seem to push the latest commits (doh!). Now it should have `gfx.SetFont()`.

I've also removed symlinks to the gfx and friends as it seems to be the cause of the compile error with nested import. You can try using the new path `github.com/veandco/go-sdl2/gfx` instead. I wanted to let people who still uses `sdl_gfx` to compile just fine but I guess there's some issues with that approach.

As for the performance, I guess you have to call it once after each full drawing in a window. So if you have two windows, it will get called only two times every frame.

**Comment by DanTulovsky** [comment]
Confirmed all working. Thank you very much for your help!
