### ISSUE TITLE
Generate a standalone build on Mac OS X

### ISSUE THREAD

**Issue by topheman** [veandco/go-sdl2#234]
How do you generate a build shipping with statically linked version of the libs (the goal being to be able to distribute a binary to people without asking them to install sdl2 and other shared libs via homebrew or apt-get) ?

I tried multiple things - nothing works. The closest I got is on [topheman/gopher-ball](https://github.com/topheman/gopher-ball), running `CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o gopher-ball-darwin-amd64.app .`, I got the following error:

```
# github.com/veandco/go-sdl2/sdl
../../veandco/go-sdl2/sdl/yuv_sw_c.go:17: undefined: Surface
../../veandco/go-sdl2/sdl/yuv_sw_c.go:18: undefined: Surface
make: *** [darwin] Error 2
```

More infos https://github.com/topheman/gopher-ball/issues/2

**Comment by veeableful** [comment]
Hi @topheman, it is a real problem. I believe for Mac you have to bundle everything you need including the SDL2 library into an .app directory which acts as a Mac bundle.

I'll be getting a Mac system this Saturday so I'll get back to you then. Once I get an initial working packaging process, I'll add a guide to the README and notify you here.

**Comment by topheman** [comment]
Thanks a lot @veeableful !

If that can help, I tried something a few days ago : https://github.com/topheman/gopher-ball/commit/0c7043cad33e0ba9d2197a6c94993a99076f9153 (removed then)

* retrieved the used libs of the generated binary with `otool -L mybinary` (same as `ldd` on linux)
* copied those in the folder I distribute the binary

But there were some pitfalls:

* the binary was still pointing to the shared libraries anyway (maybe using `install_name_tool` those paths could be changed)
* whatever, the libs themselves pointed to other libs and so on ... so I decided to change strategy

Now, you have all the infos I can think about.

**Comment by veeableful** [comment]
No problem @topheman!

I've created a simple packaging guide for macOS at https://github.com/veandco/go-sdl2-example which I may eventually move here. It's very basic as I don't really know the macOS ecosystem but it seems okay if you're only using go-sdl2.

Let me know if you can get your application to run (at least, without the assets).

**Comment by topheman** [comment]
Hie @veeableful ,

Thanks for your example. I got my whole application to run - even with the assets:

* The PR with the changes (packaging a real MacOS app + better Makefile) : https://github.com/topheman/gopher-ball/pull/3/files (everything is on master now)
* You can try the binary I generated from my computer, it's on the [releases](https://github.com/topheman/gopher-ball/releases) section

If you could confirm that the binary I generated is working on your computer, that would be great.

The next step will be generating the app for windows, first off, I'll setup a VM and install go and sdl2 on it ...

**Comment by veeableful** [comment]
Hi @topheman,

It seems like it's missing some libraries on my computer. Here's the output:

```
Process:               gopher-ball-darwin-amd64 [499]
Path:                  /Volumes/VOLUME/*/gopher-ball-darwin-amd64.app/Contents/MacOS/gopher-ball-darwin-amd64
Identifier:            co.topheman.gopher-ball
Version:               1.0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gopher-ball-darwin-amd64 [499]
User ID:               501

Date/Time:             2017-08-13 09:26:41.457 +0800
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        B12EF689-63B3-08EA-3CBB-AD68BC2F5B53


Time Awake Since Boot: 180 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /private/var/folders/7d/3g1h3cwn1t797_m8n1jcrrdc0000gn/T/AppTranslocation/B68C8027-3428-4449-A9D9-F635BFDD2771/d/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2_image-2.0.0.dylib
  Reason: image not found

Binary Images:
         0x4000000 -          0x413efef +co.topheman.gopher-ball (1.0) <33215059-25B9-3B9E-B576-556E5D89F9F8> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/MacOS/gopher-ball-darwin-amd64
         0x41bc000 -          0x41c9fff +libSDL2_image-2.0.0.dylib (0) <5C3B1BC7-D1A6-3A41-A095-DE48E84A7553> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2_image-2.0.0.dylib
         0x41de000 -          0x41e2fff +libSDL2_ttf-2.0.0.dylib (0) <6089314D-B7ED-3883-8616-630C56CCF3C6> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2_ttf-2.0.0.dylib
         0x41e6000 -          0x4292ff3 +libSDL2-2.0.0.dylib (0) <9E719E8E-E88E-3189-A837-C0121A187E07> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2-2.0.0.dylib
         0x8f07000 -          0x8f44dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff959b6000 -     0x7fff959b7ffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib

Model: MacBookAir7,2, BootROM MBA71.0166.B30, 2 processors, Intel Core i5, 1.6 GHz, 4 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x02FE, 0x45424A3230554638454455302D474E2D4620
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x02FE, 0x45424A3230554638454455302D474E2D4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2
```

**Comment by topheman** [comment]
Those are dependencies of dependencies, it seems I can't `install_name_tool -change` on a dependency (a *.dylib file) ...

**Comment by topheman** [comment]
@veeableful I just pushed a fix on this PR: https://github.com/topheman/gopher-ball/pull/4 , can you check [the generated binary](https://transfer.sh/txiIH/gopher-ball-darwin-amd64.app.zip) to see if the linking worked, please ?

I'm using the following command for the dependency *.dylib:

```shell
sudo install_name_tool -id @executable_path/../Frameworks/somelib.dylib ../Frameworks/somelib.dylib;
```

Unfortunately, it seems that `sudo` is required ...

**Comment by veeableful** [comment]
Hi @topheman, I didn't bring my Macbook to work ><. I will test it back home and let you know.

**Comment by veeableful** [comment]
It seems I could run `install_name_tool -change` using `sudo` (only some need it?). Here's the one I was working with if you want [here](https://transfer.sh/RBgR3/gopher-ball-darwin-amd64.app.zip). It needs `libfreetype` to be bundled as required by `libSDL2_ttf`.

**Comment by topheman** [comment]
> It seems I could run install_name_tool -change using sudo (only some need it?)

`install_name_tool -id` requires `sudo` (for `dylib` - see https://github.com/topheman/gopher-ball/pull/4/files#diff-b67911656ef5d18c4ae36cb6741b7965R73 )

But it seems that `install_name_tool -id` isn't the way to change the pointing dependencies ... they still point to the previous path ...

**Comment by veeableful** [comment]
Hi @topheman, are you sure you can't use `install_name_tool -change` with `sudo`? I just used it to change most of the dependency paths of the `.dylib` files and `otool` does show the changes.

**Comment by topheman** [comment]
Sorry, I wasn't clear.

You **can** use `install_name_tool -change` with `sudo` (as well as all the other commands in the Makefile like `cp`, `mv`, `mkdir` ...), but if you execute the whole Makefile as `root`, you will produce a bundle whose owner is `root` (which is bad, for example if you want to delete it, share it or anything else ...).

Whatever `install_name_tool -change` doesn't need `sudo`, this is `install_name_tool -id` that needs sudo and it seems that it doesn't work.

I must say I feel a little lost ... I've been trying to solve this for days and I haven't find any solution (and it doesn't seem like anyone has any example - not even go-sdl2 related but simply a golang based desktop gui application relying on some C libraries).

Maybe someone with a more advanced knowledge in MacOS could help us ?

**Comment by veeableful** [comment]
Hi @topheman, I believe some of the libraries do need `install_name_tool -change` with `sudo`. I've bundled the application and confirmed that it can run on my friend's Macbook Pro. You can download it [here](https://transfer.sh/GhzbA/gopher-ball-darwin-amd64.app.zip). You don't need to run the whole Makefile as sudo.

One thing to note though is that it can't run on older macOS than 10.12. Something I'll continue to look into after I buy some second-handed old Macbook soon.

**Comment by topheman** [comment]
Hie @veeableful ,

I tried your [last version](https://transfer.sh/GhzbA/gopher-ball-darwin-amd64.app.zip) on a MacOS X Sierra (without any SDL2 libs installed). I got the following:

```
Process:               gopher-ball-darwin-amd64 [5679]
Path:                  /Volumes/VOLUME/*/gopher-ball-darwin-amd64.app/Contents/MacOS/gopher-ball-darwin-amd64
Identifier:            co.topheman.gopher-ball
Version:               1.0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gopher-ball-darwin-amd64 [5679]
User ID:               502

Date/Time:             2017-08-16 15:22:20.660 +0200
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        1FCD5074-8322-CD5F-093A-1C92140F98B7


Time Awake Since Boot: 20000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libpng16.16.dylib
  Referenced from: /private/var/folders/nc/98_2knd948l8ysnv5q444hjw0000gp/T/AppTranslocation/0B87CE37-BDFF-4822-8075-F2240F32B320/d/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2_image-2.0.0.dylib
  Reason: image not found

Binary Images:
         0x4000000 -          0x413efef +co.topheman.gopher-ball (1.0) <33215059-25B9-3B9E-B576-556E5D89F9F8> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/MacOS/gopher-ball-darwin-amd64
         0x41bc000 -          0x41caff7 +libSDL2_image-2.0.0.dylib (0) <8C63FA53-7910-3FE7-8E91-EF3AD55A564E> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2_image-2.0.0.dylib
         0x41df000 -          0x41e3fff +libSDL2_ttf-2.0.0.dylib (0) <19F13310-EB38-3B6B-8C1A-1D5E3EAA5999> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2_ttf-2.0.0.dylib
         0x41e7000 -          0x4292fff +libSDL2-2.0.0.dylib (0) <C2DCCC4E-A890-3498-8362-A19519411C8C> /var/folders/*/gopher-ball-darwin-amd64.app/Contents/Frameworks/libSDL2-2.0.0.dylib
         0xa65b000 -          0xa698287  dyld (421.2) <13A9466A-2576-3ABB-AD9D-D6BC16439B8F> /usr/lib/dyld
    0x7fffbcbbe000 -     0x7fffbcbbfff3  libSystem.B.dylib (1238) <CFC3669C-FB44-3A51-8815-1E84A168F3C5> /usr/lib/libSystem.B.dylib

Model: iMac16,2, BootROM IM162.0206.B01, 4 processors, Intel Core i5, 2,8 GHz, 16 GB, SMC 2.32f20
Graphics: Intel Iris Pro Graphics 6200, Intel Iris Pro Graphics 6200, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E434C544D4C41522D4E5544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E434C544D4C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x156), Broadcom BCM43xx 1.0 (7.21.171.47.1a8)
Bluetooth: Version 5.0.1f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Magic Keyboard
USB Device: Apple Optical USB Mouse
Thunderbolt Bus: iMac, Apple Inc., 27.4
```

**Comment by veeableful** [comment]
Sorry, I guess my friend must have used a version I sent to him before which I thought is the last one. Could you try this one and let me know if it works? https://transfer.sh/dufTT/gopher-ball-darwin-amd64.app.zip.

**Comment by topheman** [comment]
Hie @veeableful ,

I made a change to my Makefile : https://github.com/topheman/gopher-ball/pull/4/files

1) I `install_name_tool -change` on the dependencies .dylib of the root .dylib
2) to avoid `sudo` I `chmod +w` the .dylib that I change
3) I removed the logs on the events (it was slowing down the app)

I checked with `otool -L`, the dylib are pointing correctly. Could you tell me if it works on your mac (without shared libs), please ? https://transfer.sh/imjhB/gopher-ball-darwin-amd64.app.zip

Thanks,

Tophe

**Comment by veeableful** [comment]
Hi @topheman, it seems like there's a mistake in your Makefile that uses `@executable_path/[library]` path instead of `@executable_path/../[library]`. Could you try changing that and generate the app bundle again?

**Comment by topheman** [comment]
@veeableful 

Just made the fix in https://github.com/topheman/gopher-ball/pull/4/commits/7e7317caabd4e7f219232dafad393e81a9554dd3

You can test the build : https://transfer.sh/zlAMv/gopher-ball-darwin-amd64.app.zip

**Comment by veeableful** [comment]
Ahhh my bad! It should be `@executable_path/../Frameworks/[library]`. Also, I think you are missing some `install_name_tool -change` for dependencies in `libSDL2_image`, `libSDL2_ttf`, `libfreetype`, and `libtiff`. Check their `otool` results for the ones that start with `/usr/local`. You can ignore the ones that point to themselves though.

**Comment by topheman** [comment]
You're right, this was my bad too (I was treating them as relative path since I was in the same directory when using `install_name_tool -change` but I assume it should be relative to the binary inside the package).

Just made the fix: https://github.com/topheman/gopher-ball/commit/248fa1e68af3974c99d2dec608c5b9bb7e17999c

You can test the build: https://transfer.sh/SGMSd/gopher-ball-darwin-amd64.app.zip

**Comment by veeableful** [comment]
Almost there! Just need to update some dependency paths of the `libSDL2_image`, `libSDL2_ttf`, `libfreetype`, and `libtiff`. There's some that is still pointing to `/usr/local`.

**Comment by topheman** [comment]
New fixes : linked the missing `/usr/local` libs : https://github.com/topheman/gopher-ball/commit/46fae8a72b9581ecfd06e4bd2872db5b73b9e51d

You can test the build: https://transfer.sh/ypsbY/gopher-ball-darwin-amd64.app.zip

**Comment by veeableful** [comment]
Yup, it's working now! Congrats haha.

**Comment by topheman** [comment]
Thanks so much @veeableful !

I'll update my readme then merge to `master` and publish a new release, that way we'll be able close the issue (I renamed it so that it's specific to Mac OS X).

My next step will be to rebase my branch with the windows build steps on `master` - I had to reset my Windows VM (that's a problem for an other day 😉 )

**Comment by veeableful** [comment]
No problem! One thing to note is that the app bundle doesn't work on older version of macOS. Probably needs to build it on older macOS or something? Anyway, we took the first step!

**Comment by topheman** [comment]
It seems, some minimum version of the system / sdk can be specified in [`Info.plist`](https://github.com/topheman/gopher-ball/blob/master/build/darwin/Contents/Info.plist).

I'll do some digging here (it might not require to build on a previous Mac OS X, because the kind of app made with go and sdl2 aren't hardly tighted with the version of the system).

**Comment by topheman** [comment]
@veeableful I fixed the memory leak and made the Windows build 🎉 

https://github.com/topheman/gopher-ball/releases/tag/v0.3.0

**Comment by veeableful** [comment]
@topheman Nice! Would you mind writing how you packaged the Windows build? I will use it as reference to write packaging instructions on my [go-sdl2-example](https://github.com/veandco/go-sdl2-example) repository (which I probably will expand to include the other SDL2 modules).
