### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#236]
I have followed the instructions step-by-step for ubuntu/linux yet when building 

…ttf/sdl_ttf.go
…mix/midi.go
…img/sdl_image.go

they all fail with 
```
./sdl_{module}_wrapper.h:5:24: fatal error: SDL_{module}.h: No such file or directory
  #include <SDL_{module}.h>
```
Whereas module is image, mixer or ttf. It is most probably not your fault but I did not know where to ask else.

**Comment by veeableful** [comment]
Hmm how did you install the SDL2 modules? And how did you try to build go-sdl2 packages? Which version of Ubuntu is it?

**Comment by Pixdigit** [comment]
via:
`sudo apt install libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev`
And then go-sdl with:
`Downloads go get -v github.com/veandco/go-sdl2/{sdl,mix,img,ttf}`
I am running Xubuntu 17.04

**Comment by veeableful** [comment]
Do you have `/usr/lib/x86_64-linux-gnu/pkgconfig/sdl2.pc` file in your Xubuntu? Does `pkg-config --cflags sdl2` output anything?

**Comment by Pixdigit** [comment]
`/usr/lib/x86_64-linux-gnu/pkgconfig/sdl2.pc` exists and `pkg-config --cflags sdl2` returns
`-D_REENTRANT -I/usr/local/include/SDL2`

**Comment by veeableful** [comment]
That is weird that you have include directory at `/usr/local/include/SDL2`. Did you install SDL2 from sources other than apt? If yes, perhaps try uninstalling it and run the `pkg-config --cflags sdl2` command again. It should point to `/usr/include/SDL2` and hopefully go-sdl2 works then.

**Comment by Pixdigit** [comment]
I tried a different sdl-go binding which required building sdl yourself. But I did a apt purge libsdl2*-dev afterwards. Also I purged again with no avail.

**Comment by Pixdigit** [comment]
So I now used cat to hunt down any reference to SDL in my filesystem and forcefully remove each file. Then a reinstall and for now it seems to work.
But why did apt purge or dpkg --reconfigure etc. not fix it?

**Comment by veeableful** [comment]
That's because the custom SDL2 was overriding system's SDL2 so you need to remove the custom one (usually a `make uninstall` would do). There was no need to touch SDL2 in apt.

**Comment by Pixdigit** [comment]
But I already did a `make uninstall`. So then it was probably a mistake in the 6 year old makefile
