### ISSUE TITLE
DestroyWindow is missing?

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#237]
I would expect [this](https://wiki.libsdl.org/SDL_DestroyWindow?highlight=%28%5CbCategoryAPI%5Cb%29%7C%28SDLFunctionTemplate%29) function to be invoked by `sdl.DestroyWindow()` but it does not exist. Also I did not find any informations about the window object in the sdl wiki so could it be that sdl's window is "just a pointer" so does not have any properties? But since go-sdl2's windows have methods could it be that those passive functions are turned into active functions on the window object? If this is the case what is the naming convention for transferring the function names of sdl2 into method names for go-sdl2?

**Comment by veeableful** [comment]
Hi @Pixdigit, our convention for making a function into a method is usually we remove the type name of the object (e.g. in this case `Window` in `SDL_DestroyWindow` and then we just take whatever is left as the method name e.g. `window.Destroy()`). If you spot anything that you feel inconsistent, feel free to tell us and we'll have a look about it.

**Comment by Pixdigit** [comment]
Ok thank you again. But generally a small guide on the differences between "pure" SDL and Go-SDL would be nice for starters.

**Comment by Pixdigit** [comment]
Neither sdl.CreateTexture nor sdl.Texture.Create exist (I tested Createtexture, Create_texture and Create_Texture too). Or do these follow some other kind of pattern?

**Comment by Pixdigit** [comment]
And while we are at it: Where is SDL.PIXELFORMAT_RGBA32?

**Comment by veeableful** [comment]
Hi @Pixdigit,

You can create texture through renderer:
`func (renderer *Renderer) CreateTexture(format uint32, access int, w int, h int) (*Texture, error)`

SDL_PIXELFORMAT_RGBA32 and its variants were missing from the package. I just added them in the latest commit. Let me know if you can use them.

For future reference, you can take a look at https://godoc.org/github.com/veandco/go-sdl2 for an overview of the package's API.

**Comment by Pixdigit** [comment]
Ok I will for close this issue. I did not know there was a documentation.
However I will post here if it worked.

**Comment by Pixdigit** [comment]
Works now
