### ISSUE TITLE
Missing Documentation about Texture.Lock

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#238]
Sorry to bother yet again but I promise it is different this time.

When locking a Texture for pixel access it requires a *unsafe.Pointer as a pointer to the pixel bytes. So I created a Surface, called .Pixels() on it and created a pointer pointing to the result. However `cannot use &pixels (type *[]byte) as type *unsafe.Pointer`. In the documentation of unsafe it merely requires a Pointer to an arbitrary type and I think a pointer to a slice filled with pixel bytes is suitable for that description. 
What am I doing wrong?

**Comment by Pixdigit** [comment]
[This](url) should be enough to understand the situation.

**Comment by veeableful** [comment]
Hi @Pixdigit,

Could you try posting the link again? It seems like it leads to a page not found.

**Comment by Pixdigit** [comment]
Weird. Try this: [https://pastebin.com/qJwrnpWw](https://pastebin.com/qJwrnpWw)

**Comment by veeableful** [comment]
Hi @Pixdigit,

I've updated the code in go-sdl2/sdl package to make the `Lock` function more user-friendly. You can see my example here: https://paste.fedoraproject.org/paste/7VdvmajUp4KnrOpTWIQ3UA

Let me know if it works out for you or you have any other problem.

**Comment by Pixdigit** [comment]
Why did you create your own struct instead of sdl.Rect ?

**Comment by veeableful** [comment]
Because I'm an idiot 🤣

I just continued your example and didn't know you meant to use sdl.Rect.

**Comment by Pixdigit** [comment]
Well nobody is perfect (The variable has rect in it though).
Everything works now.

**Comment by veeableful** [comment]
Haha thanks, and glad to know it works now.

**Comment by Pixdigit** [comment]
Bad news. Still does not work.
[This](https://pastebin.com/SMZAvkBE) is the complete code I am running. I would expect to see a white screen. However It remains black. I checked the err returns even though they are discarded in the code I posted. However the code that you wrote works.

**Comment by veeableful** [comment]
Hi @Pixdigit,

You should lock the texture before modifying it and after that unlock it. The rect you use for `renderer.Copy()` also has X and Y positions that are outside the screen.

**Comment by Pixdigit** [comment]
I tried that but it did not work work so I tried the other way around but forgot to revert for the paste.
Yeah and I totally forgot that sdl.WINDOWPOS_UNDEFINED is not 0. If I change the position it works thank you very much

**Comment by Pixdigit** [comment]
Sorry for bothering yet again. But this might actually be a bug in SDL itself:
[This](https://pastebin.com/CTKaDv1Q) for me renders a red screen. But sometimes not. The other colors work but only sometimes.  It is really inconsistent.

**Comment by veeableful** [comment]
Hmm yeah that's weird, it's always red screen for me. The pixel format seems to be backwards as well (ABGR instead of RGBA) even though when I print the texture's pixel format, it says RGBA8888. Maybe you can try and modify my minimal semi-reproduction of the program in C [here](https://paste.fedoraproject.org/paste/P~moQtw4U7rycEzAht1TWw) and see if it works as intended on your end. If it still happens, Perhaps you can ask for help on SDL2's [Discourse forum](https://discourse.libsdl.org/).

**Comment by Pixdigit** [comment]
I get the error that the calls to SDL are undefined. libsdl2-dev ist installed. I do not code in C so I do not know how to fix that

**Comment by Pixdigit** [comment]
I fiddled around again with the go variant and in seems that the byte order is just inverted meaning its  ABGR instead of RGBA. Might have something to do with endianess?

**Comment by veeableful** [comment]
Hi @Pixdigit,

You can try run the C version by executing `gcc [filename].c -lSDL2` followed by `./a.out`. You can try modify it a little to match your expectation. As for the byte order, I think we probably just missed something simple (hopefully!).

**Comment by Pixdigit** [comment]
I tried the C version and still get a red screen. So it is probably either something with SDL or hardware.

**Comment by Pixdigit** [comment]
However when I use reversed byte order [it works](https://pastebin.com/SpSf44b3)

**Comment by Pixdigit** [comment]
I also tried PIXELFORMAT_ABRG which then behaves like PIXELFORMAT_RGBA

**Comment by Pixdigit** [comment]
And I also checked, that I have little endian. Might it have something to do with that?

**Comment by veeableful** [comment]
Hi @Pixdigit,

I'm afraid I'm not knowledgeable about the implementation. You probably will have better luck asking in SDL2's forum.
