### ISSUE TITLE
Goify renderer.GetRendererInfo

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#240]
The method name should be renderer.GetInfo and also not expect a pointer to a RenderInfo struct.

**Comment by veeableful** [comment]
Nice catch! I changed it to `GetInfo()` and returns the info struct.

**Comment by Pixdigit** [comment]
Also same for renderer.GetRendererOutputSize

**Comment by Pixdigit** [comment]
While we are at it: renderer.GetLogicalSize is completely missing.

**Comment by veeableful** [comment]
Thanks! I've updated the code.
