### ISSUE TITLE
Question: In FAQ last question about SDL2 with Go.

### ISSUE THREAD

**Issue by Aukstkalnis** [veandco/go-sdl2#241]
Hello,

Will there be Go port of SDL2?
Due to the way Go is going with C interopability, this might not be possible or even make sense. Another way that we're currently thinking is to create a Rust port instead as it has nicer compatibility with C.

Does this mean that this library is not binding to SDL2? If so, why it is called go-sdl2?

**Comment by veeableful** [comment]
Hi @Aukstkalnis,

There was an intention to make this a port but we realized it was a mistake so it's there to clarify. This is still just a binding.

**Comment by veeableful** [comment]
I figure I can remove it now since it's been awhile since we cancelled that plan. I think most people shouldn't be aware of it by now.
