### ISSUE TITLE
how play mp3 from memory?

### ISSUE THREAD

**Issue by pvitaliy84** [veandco/go-sdl2#255]
Hello. Please help me, i don't understand how play mp3 from memory --> []byte

```
func play(mp3 []byte) {
if err := sdl.Init(sdl.INIT_AUDIO); err != nil {
		log.Println(err)
		return
	}
	defer sdl.Quit()

	if err := mix.Init(mix.INIT_MP3); err != nil {
		log.Println(err)
		return
	}
	defer mix.Quit()

	if err := mix.OpenAudio(22050, mix.DEFAULT_FORMAT, 2, 4096); err != nil {
		log.Println(err)
		return
	}
	defer mix.CloseAudio()

        ?????????????????
}
```

**Comment by veeableful** [comment]
Hi @pvitaliy84, I updated a bit of the code (particularly `mix.QuickLoad_WAV()`) and added an example called `audio_wav_memory` in the `examples` directory. You can only play WAV or raw audio data from memory though. If you want to play MP3, perhaps save the data as a temporary file and then play the file.

**Comment by pvitaliy84** [comment]
Ok, thnx for you help!
