### ISSUE TITLE
Is min() supposed to return the minimum value?

### ISSUE THREAD

**Issue by fohristiwhirl** [veandco/go-sdl2#256]
I was just glancing through the code, and noticed that in `gfx/sdl_gfx.go` the function min() does not do what one would expect.

Assuming it is supposed to be the minimum, a correct version would be:

```golang
func min(a ...int) int {
	b := a[0]

	for i := 1; i < len(a); i++ {
		if b > a[i] {
			b = a[i]
		}
	}

	return b
}
```

**Comment by veeableful** [comment]
Oh dear! You're right. I've fixed it now. Thanks!
