### ISSUE TITLE
Window frame isn't visible on macOS

### ISSUE THREAD

**Issue by Zac-Garby** [veandco/go-sdl2#262]
When I create the window using this code:

```go
sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
    800, 600, sdl.WINDOW_SHOWN)
```

It's just a black rectangle, with no titlebar. How can I give the window a titlebar?

**Comment by veeableful** [comment]
Could you try with this code and see if it works? I tried on my macOS and seems to work fine. I think SDL2 just needs some additional processing in the background to get the whole thing running.

```
package main

import "github.com/veandco/go-sdl2/sdl"

func main() {
        sdl.Init(sdl.INIT_EVERYTHING)
        defer sdl.Quit()

        window, _ := sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED, 800, 600, sdl.WINDOW_SHOWN)
        defer window.Destroy()

        running := true
        for running {
                for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
                        switch event.(type) {
                        case *sdl.QuitEvent:
                                println("Quit")
                                running = false
                                break
                        }
                }
                sdl.Delay(16)
        }
}
```

**Comment by Zac-Garby** [comment]
It works - thanks :) The titlebar's still dark grey, though. Not a huge problem, but if there's an easy fix it'd be nice

**Comment by veeableful** [comment]
Is it not supposed to be dark grey? I'm not sure if SDL2 provides the capability to customize the window title bar. You might need to get the native window handle using window.GetID() and do OSX specific code using the handle. I've never coded OSX GUI application though so if it's simple enough to do, I might add it to platform-specific part of the binding as an extra.

**Comment by Zac-Garby** [comment]
Usually it's light-ish grey, by dark grey I mean about 2x darker than usual. It's strange because it doesn't always happen, either. It seems that if only happens with certain clear colours.

**Comment by veeableful** [comment]
Could you post screenshots for both? Maybe I'll ask the SDL2 guys about this.

**Comment by Zac-Garby** [comment]
<img width="912" alt="screen shot 2017-10-22 at 19 01 01" src="https://user-images.githubusercontent.com/19708658/31864771-7f6e115a-b75b-11e7-9e07-152ce1df92cc.png">

<img width="842" alt="screen shot 2017-10-22 at 19 01 53" src="https://user-images.githubusercontent.com/19708658/31864772-7f91b768-b75b-11e7-8eb8-c37bd149e267.png">

(As it says, the dark titlebar seemed to happen with all background colours now, so I just used TextEdit.app)

**Comment by veeableful** [comment]
Hi @Zac-Garby,

According to slouken, it looks like you might have to recompile SDL2 with a bit of modification: https://discourse.libsdl.org/t/question-about-title-bar-color-on-osx/23275/2?u=veeableful

**Comment by Zac-Garby** [comment]
Nice, thanks! It'd be really cool to be able to set the colour at runtime
