### ISSUE TITLE
Example texture_png failed

### ISSUE THREAD

**Issue by ScottHuangZL** [veandco/go-sdl2#263]
The sample texture success load bmp files.
However, the sample texture_png failed. 

It show error: Failed to load PNG: Failed loading libpng16-16.dll , exit status 3.

I use Win10 64bit, use Go 1.9.2 , thanks.

Can you help on it? thanks.

**Comment by veeableful** [comment]
Hi @ScottHuangZL , you need to download the [SDL2](http://libsdl.org/download-2.0.php) and [SDL2_image](https://www.libsdl.org/projects/SDL_image/) Windows runtime libraries and put the .dll files inside the texture_png example folder. After that, try run the program again and let me know if it works for you.

**Comment by ScottHuangZL** [comment]
It is work after I download the runtime libraries to **overwrite** existing one. Thanks.

Originally, I just download the **dev pacakage**, and it including those dll files already, so I think no need additional work.

It will be helpful in case you add this tip in your readme.md in advance, it can save some time for new comers:) Thanks.

**Comment by veeableful** [comment]
You're right. I'll add the note to readme.
