### ISSUE TITLE
Update sdl: mutex.go

### ISSUE THREAD

**Issue by malashin** [veandco/go-sdl2#276]
`sdl: mutex.go` should be rewritten to use methods and return errors instead of ints.

**Comment by veeableful** [comment]
Added it in https://github.com/veandco/go-sdl2/commit/6a5f9c44c6d4c9cdad16bbccaf86d96197323ebd

**Comment by malashin** [comment]
Should be mentioned in BREAKING.md.

**Comment by malashin** [comment]
Ok, you've already did it. Issue can be closed.
