### ISSUE TITLE
sdl: yuv_sw_c: SW_YUVTexture seems to be depricated

### ISSUE THREAD

**Issue by malashin** [veandco/go-sdl2#280]
sdl: yuv_sw_c: SW_YUVTexture seems to be depricated. I can find it in SDL 1 sources, but not in SDL 2.

`SDL_UpdateYUVTexture()` uses a simple Texture, not a YUVTexture.

**Comment by veeableful** [comment]
Hmm you're right. I can find it in SDL2 sources but it doesn't seem to be publicly declared anywhere in the header files. Seems like it's safe to remove it so I did it.
