### ISSUE TITLE
Function parameter types and Struct field types are not compatible for coordinates.

### ISSUE THREAD

**Issue by dodobyte** [veandco/go-sdl2#281]
Edit: I believe this issue is the same with #99. Can be merged or discarded.

Let me make it clear with a simple example.

`sdl.Point` structure has `X` and `Y` fields as `int32`. However `renderer.DrawPoint` has `x` and `y` parameters as `int`.

```go
type Point struct {
	X int32
	Y int32
}

func (renderer *Renderer) DrawPoint(x, y int) error 
```

Same applies to `DrawLine` and some other functions that deal with coordinates such as `GetMouseState`.

I've seen the same issue even in this libraries code. [see](https://github.com/veandco/go-sdl2/blob/d50e839aebb74da60a03bdf9a052b9c2559b37ad/sdl/rect.go#L277)

We don't see the same issue elsewhere. `sdl.Color` and `texture.SetColorMod` are perfectly compatible.

I use this library frequently for my game and this issue causes me too much type casting. I think it would be a lot nicer if these types were compatible. 

My suggestion is to convert everything to int32.

**Comment by veeableful** [comment]
Hi @dodobyte, I see your point. I've converted most of the coordinate and size parameter types to int32. Let me know if I'm missing some things!

**Comment by dodobyte** [comment]
Hi @veeableful, I updated my code and tried it out. Everything seems to work fine. I don't see anything missing. Thanks you very much.

**Comment by malashin** [comment]
Wouldn't it make more sense to actually convert everything to `int` instead of `int32`? To me this seems much more userfriendly, and more Go-like.

Though it would require either rewriting of some structs, or writing additional getter methods that read `int32` from a struct and return `int` while original values are unexported.

**Comment by veeableful** [comment]
Ideally I guess `int` is more desirable but yeah, most of the structs right now are designed to be compatible with the C counterparts so they can be directly transferred between C and Go for efficiency. If we want to use `int`, we definitely need some translation layer as mentioned in the original [issue](https://github.com/veandco/go-sdl2/issues/99) which might add some overhead and code complexity. I wonder if there's a way to satisfy both sides..

**Comment by macroblock** [comment]
Hi all, I think that the main part of the problem is transferring Point and Rect structures and their fields between an application that uses go-sdl2 (int) and go-sdl2 itself (int32). Maybe we should add this bridge-functionality in the library. For example:
```go

func NewRect(x, y, w, h int) *Rect {
	return &Rect{X:int32(x), Y:int32(y), W:int32(w), H:int32(h)}
}

func (r *Rect) SetPos(x, y int) {
	r.x = int32(x)
	r.y = int32(y)
}

func (r *Rect) SetSize(w, h int) {
	r.w = int32(w)
	r.h = int32(h)
}

func (r *Rect) SetBound(x, y, w, h int) {
	r.SetPos(x, y)
	r.SetSize(w, h)
}

func (r *Rect) X() int { return int(r.X) }

func (r *Rect) Y() int { return int(r.Y) }

func (r *Rect) Pos() (x, y int) { return int(r.X), int(r.Y) }

func (r *Rect) Size() (w, h int) { return int(r.W), int(r.H) }

func (r *Rect) Bound() (x, y, w, h int) { return r.Pos(), r.Size() }

... and 32 bit versions ...

func (r *Rect) SetPos32(x, y int32) {...}
func (r *Rect) SetSize32(w, h int32) {...}
func (r *Rect) SetBound32(x, y, w, h int32) {...}
func (r *Rect) X32() int { return r.X }
func (r *Rect) Y32() int { return r.Y }
func (r *Rect) Pos32() (x, y int32) { return r.X, r.Y }
func (r *Rect) Size32() (w, h int32) { return r.W), r.H }
func (r *Rect) Bound32() (x, y, w, h int) { return r.X, r.Y, r.W, r.H }
```

**Comment by dodobyte** [comment]
@macroblock, bad idea. Too many new things to learn and document, too many unnecessary indirection.
go-sdl2 is already a bridge between sdl2 and go-sdl2 users. 

First off, the problem is not only `sdl.Rect` structure, there are many other things. [see](https://github.com/veandco/go-sdl2/commit/4ebcc929905579c7fd0e5caff4e40be03c85e6e1). 
Second, `sdl.Rect` was always `int32`, @veeableful converted function parameters that were not compatible with the struct fields.

Also i use and like sdl.Rect literals everywhere in my code because it's very simple and useful. I can't imagine having to call a function for such simple things.

![](https://i.imgur.com/mROVyxn.png)

**Comment by macroblock** [comment]
@dodobyte, my proposal does not affect your code in any way. It does not change existing fields. It's extended functionality for gophers who prefer to use a native int in their calculations as it provided in golang. And make their code more clean readable.
This:
```go
...
r := sdl.newRect(2*x, fy+dy, w, h)
render.FillRect(r)
r.x += int32(dx)
r.y += int32(dy)
...
```
vs. this:
```go
...
r := sdl.Rect{int32(dx+i%width), int32(dy+i/width), int32(w), int32(h)}
drawSlot(int(r.X), int(r.Y), int(r.W), int(r.H), item[i])
...
```

**Comment by dodobyte** [comment]
@macroblock, i understand your point but i am against inventing new functions or methods that don't have SDL2 counterpart. The library is very intuitive because it's a fairly straightforward translation from C to Go.

Second and perhaps more important thing is that it would split the users. Some people would use the library like me, with literals and `int32` variables while others use with `int`'s and methods. 

I strongly encourage authors to make everything `int` or `int32`, but we must have only one way to do a certain thing.

You cannot make everyone happy, otherwise you would become C++ :)

**Comment by dodobyte** [comment]
@malashin, i invalidate my previous point about serialization. It's my C habit to dump structs directly to file in binary. There are much better ways to serialize objects in Go such as [Gob](https://golang.org/pkg/encoding/gob/). This deals with the issues i mentioned before.

I still believe `int32` to be a better choice though.
