### ISSUE TITLE
something error in ubuntu 16.04  go version go1.9rc1 linux/amd64

### ISSUE THREAD

**Issue by akzi** [veandco/go-sdl2#294]
# github.com/veandco/go-sdl2/sdl
../github.com/veandco/go-sdl2/sdl/events.go:125:17: could not determine kind of name for C.SDL_DROPBEGIN
../github.com/veandco/go-sdl2/sdl/events.go:126:17: could not determine kind of name for C.SDL_DROPCOMPLETE
../github.com/veandco/go-sdl2/sdl/events.go:124:17: could not determine kind of name for C.SDL_DROPTEXT

**Comment by veeableful** [comment]
Hmm is that the latest go-sdl2? It should have placeholders already so those errors shouldn't happen. Could you try updating go-sdl2?

**Comment by hsoolien** [comment]
I am having the same issue, Mint 18.2, go1.6.2

**Comment by malashin** [comment]
Ubuntu 16.04 SDL's version is 2.0.4.
`SDL_DROPTEXT`, `SDL_DROPBEGIN`, and `SDL_DROPCOMPLETE` are available since SDL 2.0.5.

Substitute function are currently checking for >= 2.0.4 instead of 2.0.5. Should be fixed once PR is merged with the master. Update go-sdl2 after that.

**Comment by veeableful** [comment]
I have merged it to master. Thanks @malashin!
