### ISSUE TITLE
No available video device

### ISSUE THREAD

**Issue by 5k3105** [veandco/go-sdl2#298]
Hey,
Trying to get SDL working without x11. I get 'No available video device' using example.

```
pi@raspberry:~/go/src/local/s1 $ tvservice -s
state 0x12000a [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive
```

installed sdl according to:
https://discourse.libsdl.org/t/rendertarget-texture-got-deleted-between-renderpresent/22983/19
```
sudo apt-get update                      # Update package list
sudo apt-get upgrade                     # Upgrade installed packages
sudo apt-get install mercurial           # Install mercurial
sudo apt-get build-dep libsdl2           # Install most build dependencies
sudo apt-get install libgbm-dev          # Install the libgbm dependency
sudo apt-get install libgl1-mesa-dri     # Install the vc4 driver
hg clone https://hg.libsdl.org/SDL       # Get the source with mercurial
mkdir SDL/out                            # Create build directory
cd SDL/out
../configure --disable-video-x11 --disable-video-wayland --enable-video-kmsdrm --host arm-raspberry-linux-gnueabihf --disable-rpath 
make -j4
sudo make install                        # Install into /usr/local
sudo ldconfig                            # Update ld cache to make the linker aware of the new library
```

Any hints?
Thanks!

**Comment by veeableful** [comment]
Hi @5k3105, could you provide us with a minimal sample code? Just want to make sure that the issue is related to go-sdl2.

**Comment by 5k3105** [comment]
It's probably some settings somewhere - not related to go-sdl2.

Example from the front page:

```go
package main

import "github.com/veandco/go-sdl2/sdl"

func main() {
	if err := sdl.Init(sdl.INIT_EVERYTHING); err != nil {
		panic(err)
	}
	defer sdl.Quit()

	window, err := sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED, sdl.WINDOWPOS_UNDEFINED,
		800, 600, sdl.WINDOW_SHOWN)
	if err != nil {
		panic(err)
	}
	defer window.Destroy()

	surface, err := window.GetSurface()
	if err != nil {
		panic(err)
	}

	rect := sdl.Rect{0, 0, 200, 200}
	surface.FillRect(&rect, 0xffff0000)
	window.UpdateSurface()

	sdl.Delay(2500)
}
```

**Comment by 5k3105** [comment]
Nevermind. Looks like my pi is too old to use vc4. I just don't understand why I can get my emulator that uses SDL to run from terminal without x11 but I can't develop an application for SDL.

**Comment by veeableful** [comment]
Which emulator is that? Might be worth trying it out on my Raspberry Pi to see if it works. I can add it as an extra documentation in README or the go-sdl2 website we have in mind for the future reference.

**Comment by 5k3105** [comment]
Oh, I had compiled vice http://vice.pokefinder.org/ for the pi with sdl and without x11. It's probably using sdl1 though. However, it seems like I should have been able to compile with sdl2 without x11 but maybe it couldn't find opengl. openvg worked well though because I only needed a simple display.

**Comment by veeableful** [comment]
Thanks for responding even though you found a solution!
