### ISSUE TITLE
Ability to optionally exclude examples

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#301]
I set up my new laptop along with a working environment for go. However when I set it up I wondered why I suddenly had 3 more source packages for go-gl. Since I do not need them do not want to keep maintaining that bit of code (meaning checking for (security-)updates etc.) it would be nice to be able to exclude it when installing go-sdl2.

**Comment by veeableful** [comment]
Hi @Pixdigit, installing go-sdl2 shouldn't install any extra packages (or at least it doesn't for me). How did you install go-sdl2? Maybe I'll try and see if it happens to me. I usually just use `go install -v github.com/go-sdl2/sdl` (or I can also use `go install -v github.com/go-sdl2` but that means the `sdl` package won't be pre-compiled).

**Comment by Pixdigit** [comment]
I got it by `go get -v github.com/veandco/go-sdl2{ttf,mix,sdl,gfx}`

**Comment by veeableful** [comment]
Hmm strange, it doesn't seem to do it for me. Have you tried backing up the `$GOPATH` folder and run the same command to see if it happens again? The only way I see you can get `go-gl` package is if you run `go get -v` inside one of the opengl examples.

**Comment by Pixdigit** [comment]
Turns out the gl packages only get installed when I execute `go get -u -v all`. I mean I _could_ do selective updates but it is a bit inconvenient.

**Comment by veeableful** [comment]
Okay, I'll move the examples and assets out to another repository.

**Comment by veeableful** [comment]
I've moved them out to another [repository](https://github.com/veandco/go-sdl2-examples). Could you try again and confirm that it works? You might need to clear the $GOPATH though.

**Comment by Pixdigit** [comment]
This has fixed it. And thank you for your effort as it is not usual to fix such minor annoyances so fast.

**Comment by malashin** [comment]
@veeableful 

TestSurface() fails now due to the lack of `../assets/test.bmp`.

```go
if image, err = LoadBMP("../assets/test.bmp"); err != nil {
	t.Error(err)
}
```
https://github.com/veandco/go-sdl2/blob/master/sdl/surface_test.go#L37

**Comment by veeableful** [comment]
@malashin 

Hmm, I guess I'll add the go-sdl2-examples repository as submodule. Thanks for the notice!
