### ISSUE TITLE
Does the LoadWAV binding make sense?

### ISSUE THREAD

**Issue by jackmott** [veandco/go-sdl2#308]
https://github.com/veandco/go-sdl2/blob/master/sdl/audio.go#L334

LoadWAV takes a pointer to an AudioSpec, then also returns a pointer to an audiospec, I think the *same* pointer.  Is the return value redundant/unecessary?

**Comment by veeableful** [comment]
Hi @jackmott, you're right that it's redundant. @malashin has implemented the change so you won't need to pass the *AudioSpec anymore.

**Comment by jackmott** [comment]
Great, seems solved to me.
