### ISSUE TITLE
Functions should return structs instead of requiring pointers to them

### ISSUE THREAD

**Issue by malashin** [veandco/go-sdl2#311]
I've found some C-code leftovers that in my opinion should be changed, but decided not to at this time and would like to hear more opinions on this issue. There are plenty of binding functions that require struct pointers to be passed because C can't return those structs.

**Examples:**
```go
func GetDisplayBounds(displayIndex int, rect *Rect) error {}
func GetDisplayMode(displayIndex int, modeIndex int, mode *DisplayMode) error {}
func (window *Window) GetDisplayMode(mode *DisplayMode) error {}
```

**The way it is used now:**
```go
rect := sdl.Rect{}
err := sdl.GetDisplayBounds(0, &rect)
```

I think that in Go those struct should be returned from those functions, instead of being passed into them as pointers.

**The way it should be used:**
```go
rect, err := sdl.GetDisplayBound(0)
```

There was an issue about one function that does it couple of days ago (https://github.com/veandco/go-sdl2/issues/308). Since thise function was changed, all other similar functions should be changed as well.

**Comment by veeableful** [comment]
Yeah, it seems like that's the direction is this kind of functions are going to. I don't see any downside and it does seem more ergonomic. I'd say go for it!

**Comment by thomas-holmes** [comment]
I would think the only real upside is allowing you to reuse the same rectangle in an iterative operation rather than always, potentially, allocating a new one.

**Comment by thomas-holmes** [comment]
On further thought, likely we could still avoid an excess of allocations based on how it's called. May be a bit more expensive to do the copy than direct setting, but when I think more about it probably may not make much of a difference. Might be worth wipping up some benchmarks to see if there is a variance.

**Comment by malashin** [comment]
@veeablefu, regarding this changes https://github.com/veandco/go-sdl2/commit/1cae00eaa8b51cbf3d4e680c287b378e8bec0f20.

It might be more feasible to return pointers, instead of structs. That way in case of an error we can return `nil` instead of an empty struct.

This function right next to the modified ones does return a pointer already (original C code though):
https://github.com/veandco/go-sdl2/blob/master/sdl/video.go#L408

We should think this through so it's more or less consistent in the whole lib. This is the reason I abandoned this back when this issue was started and did not get feedback from others. It's not that simple if you look at all the cases, but the library requires consistency in its approach.

Some functions are pretty much stuck with the way they are in C though, especially the ones from SDL1:
https://wiki.libsdl.org/SDL_OpenAudio

**Comment by thomas-holmes** [comment]
I'm of two minds with regard to this. Some increased consistency from the go side would be nice but might be really challenging to nail perfectly. Just copying what SDL does (which seems to be the case  for the current API) seems to be the safest approach.

I will admit I'm not sure I understand why some of these SDL functions return pointers instead of the simple structures that only have a few lightweight fields.

Tagging @veeableful b/c you mispelled their name in your comment :)

**Comment by veeableful** [comment]
@malashin 

What concern do you have with returning structs? My thought was that it is fine because the errors are returned as well. It also aligns with how I imagine the C code would be, for example:

```
SDL_Rect r;
if (SDL_GetDisplayBounds(0, &r) != 0) {
    SDL_Log("SDL_GetDisplayBounds failed: %s", SDL_GetError());
    return 1;
}
```

where `r` is a struct and not pointer. I just thought that this is the "right" translation to Go.

**Comment by malashin** [comment]
@veeableful 
> I just thought that this is the "right" translation to Go.

I think that its the way it should be myself. There should be a rule when we are allowed to do this. Probably everything that has a Go struct without unsafe pointers in it should be returned as a struct.

There are not not so many structs to return then and should be easy to do.

Though this ones might also be better off returned as structs, since they are created without pointers _(this functions differ a lot from C code)_:
```go
// AudioSpec contains the audio output format. It also contains a callback that is called when the audio device needs more data.
// (https://wiki.libsdl.org/SDL_AudioSpec)
type AudioSpec struct {
	Freq     int32          // DSP frequency (samples per second)
	Format   AudioFormat    // audio data format
	Channels uint8          // number of separate sound channels
	Silence  uint8          // audio buffer silence value (calculated)
	Samples  uint16         // audio buffer size in samples (power of 2)
	_        uint16         // padding
	Size     uint32         // audio buffer size in bytes (calculated)
	Callback AudioCallback  // the function to call when the audio device needs more data
	UserData unsafe.Pointer // a pointer that is passed to callback (otherwise ignored by SDL)
}

// LoadWAVRW loads a WAVE from the data source, automatically freeing that source if freeSrc is true.
// (https://wiki.libsdl.org/SDL_LoadWAV_RW)
func LoadWAVRW(src *RWops, freeSrc bool) ([]byte, *AudioSpec) {)

// LoadWAV loads a WAVE from a file.
// (https://wiki.libsdl.org/SDL_LoadWAV)
func LoadWAV(file string) ([]byte, *AudioSpec) {}
```

**Comment by veeableful** [comment]
@malashin 

Which part do you think differs a lot from the C code? I actually thought that they're very similar except that we merge `Uint8*` and `Uint32` in C as `[]byte` in Go. The pointer return is consistent with the C counterpart too.

**Comment by snakeru** [comment]
I think this got closed some time ago. Currently all three of these functions have Go-style signatures. For example:

`func GetDisplayBounds(displayIndex int) (rect Rect, err error)`

**Comment by veeableful** [comment]
Nice catch @snakeru! I think I will close this for now then. If there's some other functions that haven't been converted, this issue can be re-opened!
