### ISSUE TITLE
Please, provide some example how to use sdl ttf

### ISSUE THREAD

**Issue by xahon** [veandco/go-sdl2#312]
How to print a text?
P.S. I there a way to use tilemap instead of font?

**Comment by veeableful** [comment]
Hi @xahon, you can checkout `https://github.com/veandco/go-sdl2-examples/blob/master/examples/text/text.go` for an example.

There's no built-in support for tilemap but perhaps you can create the font tilemap and blit them into the surface yourself?

**Comment by xahon** [comment]
@veeableful thank you. It's exactly what i wanted
