### ISSUE TITLE
Calculate the pitch for texture update

### ISSUE THREAD

**Issue by Sendoushi** [veandco/go-sdl2#314]
Hi guys,

I'm trying to setup V4L2 with SDL and I already have a frame / byte[] . Now I want to set a texture and updating the texture I need the pitch. What should be the pitch?

From general `SDL_UpdateTexture()` usage, it seems that I should use `frameWidth * sizeof(uint32)` but is this still true for `go-sdl2`? How should I calculate the row size in bytes?

**Comment by Sendoushi** [comment]
So that byte[] variable, I can simply save it like: `ioutil.WriteFile("./test.jpg", frame, 0644)` if that helps somehow...

**Comment by veeableful** [comment]
Hi @Sendoushi, you can get the pitch from using `Lock()` on the texture. However the bytes you get won't be encoded in JPEG so you will need to encode it first before saving into a JPEG file.

**Comment by Sendoushi** [comment]
Here is the solution I found, and it is working but maybe not the best solution, what do you think?

```go
        // decode into image
	img, err := jpeg.Decode(bytes.NewReader(f))
	if err != nil {
		return nil, errors.New("jpeg-decode:" + err.Error())
	}
	if img == nil {
		return nil, nil
	}

	// TODO: check if needs to be converted

	// convert pixel type
	ycbcr := img.(*image.YCbCr)
	b := ycbcr.Bounds()
	rgba := image.NewRGBA(image.Rect(0, 0, b.Dx(), b.Dy()))
	draw.Draw(rgba, rgba.Bounds(), ycbcr, b.Min, draw.Src)
```

**Comment by veeableful** [comment]
Hi @Sendoushi, sorry I've been away for the lunar new year (Happy new year by the way!).

Did you manage to solve all your problems? From the code snippet itself, I don't really see if there's any potential issue with it. If you can give us a complete minimal code that runs, I'd be happy to check it!

**Comment by Sendoushi** [comment]
Yep. Using the golang image standard library makes more sense.
I ended up improving the code to convert to `RGBA` just in case it isn't.

This also removes the dependency from `sdl-image` and `SDL` is used essentially to show data. Relying more in the go standard library. Makes sense to me.
