### ISSUE TITLE
window.GetDisplayMode shouldnt require a displayMode object

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#318]
Currently window.GetDisplayMode requires a displayMode object to be filled with the data just as SDL2 does. However to be consistent it should construct it itself and just return the new object.

**Comment by Pixdigit** [comment]
Same for sdl.GetDesktopDisplayMode(displayIndex, mode)

**Comment by Pixdigit** [comment]
Same goes for `renderer.ReadPixels(rect *Rect, format uint32,` _pixels unsafe.Pointer_ `, pitch int)`

**Comment by veeableful** [comment]
I have changed all the above and some except `renderer.ReadPixels` as it's slightly more complicated.

**Comment by malashin** [comment]
There is an issue https://github.com/veandco/go-sdl2/issues/311 regarding this problem. I'm closing this one.
