### ISSUE TITLE
Convert texture to surface?

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#321]
I know this is for once not an issue of go-sdl2 but SDL2 itself and secondly is not an issue rather than a question about how SDL2/go-sdl2 works. However @veeableful mentioned in #259 that I can ask here.

I have the issue that I want to convert a texture back to a surface. SDL2 itself does not come with this functionality and therefore go-sdl2 neither. So I tried CreateRGBSurfaceFrom with anything remotely representing a pointer to the texture data. However no matter what I use (not even a C pointer) go proclaims: "[…] cannot use […] as type unsafe.Pointer in argument to sdl.CreateRGBSurfaceFrom". Apart from keeping track of the surface while loading it from file before converting to texture I have no other idea how to do this.

**Comment by veeableful** [comment]
I'm no expert but as far as I can tell, there's no method to convert texture back to surface. Is there a reason why you would want a surface?

**Comment by malashin** [comment]
@Pixdigit 

You read the pixel data from sdl.Texture with Texture.ReadPixels().

This will update the Surface pixels with the ones read from the Texture.
```go
s, _ := sdl.CreateRGBSurfaceWithFormat(0, 128, 128, 32, sdl.PIXELFORMAT_RGBA8888)
r.ReadPixels(nil, 0, s.Data(), int(s.Pitch))
```

Though you are much better off with reading the file as a Sruface in the first place. Other options are slow and might not be reliable since Texture might be modified by the GPU.

**Comment by Pixdigit** [comment]
@malashin But then I would need to keep track of either the filepath (which could possibly change during runtime) or the surface which eats a ton of ram. So I would stick with your answer.

**Comment by malashin** [comment]
@Pixdigit I screwed up with the answer actually. ReadPixles() is a Renderer's method, hence r.ReadPixles() in the example. You will need to copy Texture to Renderer first (quite a bad idea imo).

**Comment by Pixdigit** [comment]
Well then the user just has to provide the filepath instead of pixeldata
