### ISSUE TITLE
Error in GFX update/install

### ISSUE THREAD

**Issue by hsoolien** [veandco/go-sdl2#322]
Got the following error when updating my SDL/GFX
First popped up trying out the demo code for GFX
```
In file included from ..\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:8:0:
./sdl_gfx_wrapper.h:2:11: fatal error: SDL2/SDL2_framerate.h: No such file or directory
  #include <SDL2/SDL2_framerate.h>
```

**Comment by malashin** [comment]
Hello @hsoolien.

Do you actually have `SDL2_gfx` installed? `SDL2_framerate.h` is a part of `SDL2_gfx`.

**Comment by hsoolien** [comment]
You know I thought I had, don't I feel foolish, thank you
