### ISSUE TITLE
opengl and opengl3 examples need new GLCreateContext and GLSwap methods

### ISSUE THREAD

**Issue by jojomickymack** [veandco/go-sdl2#327]
I wasn't able to compile the opengl examples (opengl, opengl3), the sdl.createContext and sdl.GLSwapWindow methods were undefined.

I found issue below and used window.GLCreateContext() and window.GLSwap() and was able to then compile and run.

should GLCreateContext use a *Window receiver? #325

those 2 methods should be fixed in the master branch of the examples repo so new users can run them.

Cheers on this library, I consider it one of go's best!

**Comment by veeableful** [comment]
Hi @jojomickymack, thanks for the report! It should have been fixed in the latest commit now.

**Comment by jojomickymack** [comment]
works great!
