### ISSUE TITLE
Make iHapticEffect interface public

### ISSUE THREAD

**Issue by tanema** [veandco/go-sdl2#331]
iHapticEffect was introduced here: https://github.com/veandco/go-sdl2/pull/316

I was updating my codebase for the newest version of the library and found a sticking point. I often save my effects for running later and updating and to have a single method I can call to run the effects. Here is my method that runs effects: https://github.com/tanema/amore/blob/master/joystick/joystick.go#L249

If iHapticEffect was public this would be super simple but if it is not public then I will have create the effects over and over again and have a bunch of redundant code.

I am specifically thinking about the UpdateEffect method where I previously passed in an effect but now it requires an interface that is not public making it really hard to pass it around.

**Comment by tanema** [comment]
nvm I realized I can just do this with NewEffect 👍

**Comment by tanema** [comment]
*sorry for the noise* I was incorrect because I still cannot add an iHapticEffect as a struct field or a method param.

**Comment by malashin** [comment]
Hi @tanema 

My guess is that you want to pass HapticEffect and be able to modify its type afterwards.
Sadly it's not possible with current implementation. You can create and update effects as long as they still have the same type.
```go
// Create HapticLeftRight to test low frequency motor.
e := &sdl.HapticLeftRight{
	Type:           sdl.HAPTIC_LEFTRIGHT,
	Length:         3000,
	LargeMagnitude: 32767,
	SmallMagnitude: 0,
}

// Add this effect to haptics.
id, err := h.NewEffect(e)
if err != nil {
	panic(err)
}
// Run the effect.
h.RunEffect(id, 1)
fmt.Println("Running haptic effect:", e)
// Wait 3 seconds.
time.Sleep(3 * time.Second)

// Modify HapticLeftRight to test high frequency motor.
e.LargeMagnitude = 0
e.SmallMagnitude = 32767

// Update haptic effect.
err = h.UpdateEffect(id, e)
if err != nil {
	panic(err)
}
// Run the effect.
h.RunEffect(id, 1)
fmt.Println("Running haptic effect:", e)
// Wait 3 seconds.
time.Sleep(3 * time.Second)
// Destroy the effect.
h.DestroyEffect(id)
```

Interface access wont fix this. Golang doesn't have unions and the only reason it worked before is that you could return pointers to the C's HapticEffect that was modifiable. Thought we could add those methods to the interface.

Current implementation is easier to understand in my opinion, but after looking into it i'm thinking of reverting back to the old one https://github.com/veandco/go-sdl2/blob/2b0e4a2e51f4bb7e1cf495310b98f60d50eb46e6/sdl/haptic.go. At least the old one works similar to original SDL2.

I'll look more into it and do some testing first. If you have any ideas, feel free to share. ;)

**Comment by tanema** [comment]
Well, I don't want to edit an effect, I just want to store it and pass it into a method. I will try again to refactor but this makes it pretty difficult to pass around effect data.

**Comment by tanema** [comment]
I *think* it is bad practice to pass around a private interface, if you run `golint` on this repo I imagine it would warn you.

All I want to do is.

- Make an effect with NewEffect.
- If the effect changes, update that effect with UpdateEffect and pass in a new struct to that.
- if the update fails, destroy the effect and create a new one, passing in the struct that was just passed into updateeffect.

I have this all contained in a single method call because for compatibility reasons I have to try several approaches to setting an effect. I will call UpdateEffect on each attempt.
- Try LeftRight
- Try Custom
- Try Periodic

I am not sure, but from what I have seen other developers doing I think it is unwise/unefficient to create a new effect. I would also want a method to do that anyways so that it would destroy the previous effect before creating a new one.

**Comment by veeableful** [comment]
I believe it should be fine to make the interface public if the method is private. It also seems like we're not using the HapticEffect type so perhaps we can rename the iHapticEffect interface to that? You could then use the HapticEffect interface as a variable type to store your effects. Would that solve your problem @tanema?

**Comment by tanema** [comment]
Absolutely.

**Comment by veeableful** [comment]
@tanema I've made the update on the master branch. You can try it now :grin:

**Comment by tanema** [comment]
Thank you so much, this cleaned up my code really well.

For your reference: https://github.com/tanema/amore/pull/13/files#diff-6304fb2f8471613ba36ad9b2971638e8R241
