### ISSUE TITLE
SDL2/SDL.h: No such file or directory {Windows 10}

### ISSUE THREAD

**Issue by jGeorge437** [veandco/go-sdl2#342]
This issue was raised two years ago here:
https://github.com/veandco/go-sdl2/issues/88 

Unfortunately the user's account has been deleted and other efforts of mine to find the fix has failed. 
Tried following this tutorial (led to failure, can skip first five minutes, installation ends at 23:30)
https://www.youtube.com/watch?v=OXSMx45kayw

Error message
`
C:\Users\USERNAME\Documents\GOProjects\src\git.radops.net\RP\flappy-gopher\sdl2Test> go get github.com/veandco/go-sdl2/sdl
{Pound} github.com/veandco/go-sdl2/sdl
In file included from ..\..\..\..\github.com\veandco\go-sdl2\sdl\audio.go:4:0:
./sdl_wrapper.h:2:23: fatal error: SDL2/SDL.h: No such file or directory
compilation terminated.
`

SDL2.dll is found here (and config):
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\bin

I see the SDL.h (and a crap ton more headers) here:
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\include\SDL2

**Comment by veeableful** [comment]
For me, I only merged the folder that SDL2 provides with the existing directory (`x86_64-w64-mingw32`) under mingw-w64. I do use Git Bash as the command-line interface though which may provide different environment somewhat. What terminal do you use for compiling? I could try it again on the same terminal to see if it's related.

**Comment by jGeorge437** [comment]
I got it working. I'm so startled! 

I started using Powershell as my method, and my current solution involved me moving mingw64 out from Program Files and under my windows profile (Icky, I know) and using Git Bash, though I would like to try this again on my work computer using powershell to truly see if that had anything to do with it. Bear in mind the first computer I tried this on was a work computer, and with our infrastructure moving to implement... "stricter" that could've been the culprit. 

I will follow this with a more in depth update and possibly a pull request to the readme section of the installation file if that is okay :)

**Comment by veeableful** [comment]
Hi @hdfsyu, do you also have an issue with the installation on Windows 10? If possible, could you create a new issue with an overview on how you installed and tried to use it? Thanks!

**Comment by anilkonac** [comment]
I had the same problem, but I noticed that I'm copying bin, include, lib and share folders into ..\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64 not into ..\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32. Copying x86_64-w64-mingw32 folder as told in Readme.md would solve it in the first place.

**Comment by IfeSunmola** [comment]
If anyone still has this problem, I fixed mine by just copying everything in the include folder of SDL to the include folder of MinGW and I used it in my code like: `#include <SDL.h`

The SDL was downloaded from https://libsdl.org/download-2.0.php  (.zip)

Something might probably go wrong soon but if it works, it works I guess
