### ISSUE TITLE
How to use RWOps

### ISSUE THREAD

**Issue by rucuriousyet** [veandco/go-sdl2#344]
I was wondering how to read/write from RWOps srcs.... I would love an example using a io.Reader or io.Writer since that is very standard and commonly used. The goal here is to statically load assets that can be compiled and bundled into the Go binary, meaning that rather than opening a file, I will need to load fonts, images etc from memory.

**Comment by veeableful** [comment]
Hi @rucuriousyet! I decided to make the functions to look more Go-like and conforms to standard Go I/O interfaces. I've also added an example to `.go-sdl2-examples/examples/rwops/memory.go`. Let me know if it does or doesn't help you!
