### ISSUE TITLE
Failed to found *sdl.KeyUpEvent

### ISSUE THREAD

**Issue by Chipsterjulien** [veandco/go-sdl2#349]
Hello
I search _*sdl.KeyUpEvent_ and _*sdl.KeyDownEvent_ as [your example](https://github.com/veandco/go-sdl2-examples/blob/48be04793af0dc1ef534cd5bd8660430345b7e30/examples/events/WaitEvent.go) but i'm failed to found it
Any idea ?

**Comment by veeableful** [comment]
Hi @Chipsterjulien, I've updated the examples. Could you try again?

**Comment by Chipsterjulien** [comment]
I go home and test it.
Thank you for help and the great responsiveness
