### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by jclc** [veandco/go-sdl2#353]
Support for Vulkan functions. Compatibility with https://github.com/vulkan-go/vulkan would be very nice. Could Vulkan handles be transferred between packages as uintptrs? I'm not sure how two separate CGO-enabled packages will handle the same types.

**Comment by veeableful** [comment]
I think both packages need to type alias the handles as uintptr which requires Go 1.9. Maybe there's a hack that can be used for forcing a cast between the two types but I have no clue what the hack is..

**Comment by jclc** [comment]
This isn't quite solved yet. The only function I couldn't test properly is VulkanCreateSurface. I'll need to make sure go-sdl2 can interface with vulkan-go first. I'll probably have to change the Go wrapper function signature to take a uintptr instead of the actual Vk handle.

**Comment by Pixdigit** [comment]
Doesnt SDL support Vulkan natively?

**Comment by jclc** [comment]
It does, but you need another library to load and use the Vulkan functions.

**Comment by jclc** [comment]
My patches are now in vulkan-go/vulkan, you can test Vulkan support yourself with `go get github.com/vulkan-go/demos/vulkancube/vulkancube_sdl2`
