### ISSUE TITLE
Missing WarpMouseGlobal

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#360]
[WarpMouseGlobal](https://wiki.libsdl.org/SDL_WarpMouseGlobal) is not yet implemented

**Comment by malashin** [comment]
Added it to the master branch.

`*Window.WarpMouseInWindow` should be renamed at some point with other breaking changes, leaving it for now.

**Comment by veeableful** [comment]
Thanks @malashin! You're the best.
