### ISSUE TITLE
AudioStream.Clear calls SDL_AudioStreamFlush

### ISSUE THREAD

**Issue by gonutz** [veandco/go-sdl2#377]
[The implementation of AudioStream.Clear](https://github.com/veandco/go-sdl2/blob/master/sdl/audio.go#L620) calls `SDL_AudioStreamFlush`. It should probably be calling `SDL_AudioStreamClear` right?

**Comment by gonutz** [comment]
By the way, why are there so many `TODO:`s in the doc comments of API calls?

**Comment by veeableful** [comment]
You're right @gonutz. Thanks for informing me!

The `TODO`s are to mark page URLs that don't exist yet. When SDL2 devs publish the pages, they should be removed.

**Comment by gonutz** [comment]
I see you did the change so I am closing this now.
