### ISSUE TITLE
 Sensor.Close calls SDL_SensorGetNonPortableType

### ISSUE THREAD

**Issue by gonutz** [veandco/go-sdl2#378]
[The implementation of Sensor.Close](https://github.com/veandco/go-sdl2/blob/master/sdl/sensor.go#L307) calls `SDL_SensorGetNonPortableType`. It should probably be calling `SDL_SensorClose` right?

This is the same thing that happened in #377. I am currently going through your whole API, removing the CGo from the Windows port by loading the DLL and calling it directly rather than going through the C layer. I am almost done and will be opening a large pull request soon. Maybe I find some more of these along the way :-)

**Comment by veeableful** [comment]
Thanks for catching this! I've fixed it in master branch.

**Comment by gonutz** [comment]
OK, closing this as well.
