### ISSUE TITLE
commit #3acc826 regression

### ISSUE THREAD

**Issue by rvi64** [veandco/go-sdl2#379]
```
% go build
# github.com/veandco/go-sdl2/sdl
../go/src/github.com/veandco/go-sdl2/sdl/audio.go:621:123: (func literal)(stream.cptr()) used as value
```

This bug was introduced with commit #3acc82665a0b4c8fde7789d2392c77e895613438

**Comment by dedalqq** [comment]
I have a similar problem = (

**Comment by veeableful** [comment]
Oh dear! Sorry about that, I thought the CI would have failed. I've fixed it now..I think.
