### ISSUE TITLE
AudioStream.Clear returns an error

### ISSUE THREAD

**Issue by gonutz** [veandco/go-sdl2#380]
In [the current SDL_audio.h](http://hg.libsdl.org/SDL/file/48e26b5d4f56/include/SDL_audio.h), line 602, the function `SDL_AudioStreamFlush` is defined as

    extern DECLSPEC void SDLCALL SDL_AudioStreamClear(SDL_AudioStream *stream);

with the return type `void`. In [your implementation](https://github.com/veandco/go-sdl2/blob/3acc82665a0b4c8fde7789d2392c77e895613438/sdl/audio.go#L621) however, you use its return value to generate an error. How does this even compile? Am I missing something here? Should it not return nothing instead of `error`?

**Comment by dedalqq** [comment]
duplicate:
https://github.com/veandco/go-sdl2/issues/379

**Comment by gonutz** [comment]
Oh I see, closing this one then.
