### ISSUE TITLE
how to get text from sdl.TextInputEvent.Text???

### ISSUE THREAD

**Issue by dedalqq** [veandco/go-sdl2#384]
```
type TextInputEvent struct {
         .......................
	Text      [C.SDL_TEXTINPUTEVENT_TEXT_SIZE]byte // the null-terminated input text in UTF-8 encoding
}
```

i do not found examples for this. =(

**Comment by gonutz** [comment]
You can go through the Text variable until you find a `0`. This marks the end of the string, say that `i` is the index at which the `0` occurs, then you would get the text string like this: `s := string(event.Text[:i])`.

**Comment by veeableful** [comment]
Hi @dedalqq, I added `GetText()` method to get the text as string from the `TextEditingEvent` and `TextInputEvent`. Let me know if it works!

**Comment by gonutz** [comment]
Don't you want to close this issue? I have tested the code and it works fine :-)

**Comment by veeableful** [comment]
Thanks for testing it @gonutz! I shall close this issue then~
