### ISSUE TITLE
Pull #385 broke sdl gfx

### ISSUE THREAD

**Issue by depili** [veandco/go-sdl2#386]
https://github.com/veandco/go-sdl2/blame/master/gfx/sdl_gfx.go#L620 Line 620 has a (copy-paste?) mistake and is missing the underscore in len causing the compilation to fail. Faulty commit is 042cf8322c847379ced77b4d7d1832b6b560ddd6

**Comment by veeableful** [comment]
Hi @depili, so sorry about that! It should be fixed now in master branch. Please try!

**Comment by depili** [comment]
Yes, 902a8518c8fcea0ff782bb346a8767d5e1bf89f8 does indeed fix this issue and rerunning the previously failed build job succeeds now: https://gitlab.com/Depili/clock-8001/-/jobs/164517043
