### ISSUE TITLE
Do in tests

### ISSUE THREAD

**Issue by gonutz** [veandco/go-sdl2#388]
Hey, I am trying to use your tests for [my DLL port](https://github.com/gonutz/go-sdl2/tree/master/sdl) but right away when I copy [TestEventsAddEventWatch](https://github.com/veandco/go-sdl2/blob/902a8518c8fcea0ff782bb346a8767d5e1bf89f8/sdl/events_test.go#L187) I get a panic in the test because the test does not call Main but uses Do. Could you explain to me how you run your tests if not with `go test`? Is it a different way of running the tests? Do they even pass (I have currently no C-compiler on my Windows so I have not run your tests but I assume they all pass)?

**Comment by veeableful** [comment]
Hi @gonutz, I use `go test` to run the tests. However there is `TestMain()` in `sdl_test.go` that will be called first which will in turn call the `sdl.Main()` function. But yeeeah, the tests are not super comprehensive or looked after right now. I just fixed a compile error and the tests seem to pass (for now!).

**Comment by gonutz** [comment]
I see, that is what I was missing. Thank you very much, I am on my way and testing now. I want to have as many functions tested as possible and I am using your repo as an example.
The progress of my port is good, only a handful of functions that have not yet been ported. After testing as much as possible I will probably open the PR.
