### ISSUE TITLE
SDL_Net

### ISSUE THREAD

**Issue by TerensTare** [veandco/go-sdl2#403]
There is also a library by the original SDL maker called SDL_Net.
What about that?

**Comment by veeableful** [comment]
Hi @TerensTare we think that Go already provides most if not all networking capabilities either in the standard library or external library so there is no SDL_net binding because it would be somewhat redundant. However if there is a good use-case, we could create binding for it as well of course!

**Comment by TerensTare** [comment]
Well, that's a quiet good reason.
I understand it and that's cool.
So I wish you good luck in continuing the development of go-sdl2.
all the bests
