### ISSUE TITLE
Possible overflow

### ISSUE THREAD

**Issue by flga** [veandco/go-sdl2#405]
Hey, I was looking into removing unsafe.Pointer from Renderer.ReadPixels and I stumbled upon [this](https://github.com/veandco/go-sdl2/blob/5a9e461058bd05ddef9c8cde64e58d4f96d1f186/sdl/render.go#L372).

Isn't it overriding arbitrary memory?

**Comment by flga** [comment]
Took a look at the docs, which state "This is filled in with a **pointer** to the locked pixels, appropriately offset by the locked area" (regarding the data pointer).
I assumed SDL wrote to it.

**Comment by veeableful** [comment]
Hi @flga, I really appreciate the continuous care you give to this project! That certainly would be a nice design improvement to make. Will you be creating a PR for it?

**Comment by flga** [comment]
@veeableful it's a very useful lib, it's my pleasure :)
Yep, i'll work on it today, I just need to think a little bit more on how to test it properly.
