### ISSUE TITLE
Vulkan funcs should return unsafe.Pointer instead of uintptr

### ISSUE THREAD

**Issue by Nightwulf** [veandco/go-sdl2#409]
VulkanCreateSurface(instance interface{}) returns an uintptr which is a dangerous behaviour hence uintptr is not updated by the garbage collector. It should return the unsafe.Pointer instead which is updated.
In VulkanGetVkGetInstanceProcAddr() it is done correctly.
if you use VulkanCreateSurface() and try to cast it to a vkSurfaceKHR, you need to cast it back to unsafe.Pointer which then causes a warning when call "go vet": "possible misuse of unsafe.Pointer"

**Comment by veeableful** [comment]
Hi @Nightwulf, thanks for the feedback! I've updated the function to return `unsafe.Pointer` instead.

**Comment by Nightwulf** [comment]
Hey @veeableful,

thank you for the fast reply and change. Go vet no longer moans now!
