### ISSUE TITLE
Compile error with sdl2-2.0.10

### ISSUE THREAD

**Issue by Nightwulf** [veandco/go-sdl2#416]
Compiling any go-program which includes "github.com/veandco/go-sdl2/sdl" causes an compile error when sdl2-lib is at version 2.0.10:
`# github.com/veandco/go-sdl2/sdl
../../github.com/veandco/go-sdl2/sdl/hints.go:107:50: could not determine kind of name for C.SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH`

After downgrade to sdl2-2.0.9, compile works again.
Simple example code showing the problem:
```
package main

import (
	"github.com/veandco/go-sdl2/sdl"
	"log"
)

func main() {
	err := sdl.Init(sdl.INIT_EVERYTHING)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by veeableful** [comment]
Hi @Nightwulf, thanks for reporting this! It should have been fixed in the master branch.

**Comment by Nightwulf** [comment]
Great, compiling works again. Thanks for the blazingly fast fix!
