### ISSUE TITLE
Audio messed up

### ISSUE THREAD

**Issue by Matias-Barrios** [veandco/go-sdl2#420]
I'm trying to add audio to a game I'm making.

I can see the audio plays ok just the first three times ( .WAV by the way ) and from the 4th time.onwards is messed up ( like it were radio static ).

Here is the repo of my code : https://github.com/Matias-Barrios/SDL_Universe/blob/master/SDL/audio.go

Can someone tell me if I'm doing something wrong that might cause the issue?

**Comment by veeableful** [comment]
Hi @Matias-Barrios, I have been investigating the issue but I haven't found the real problem that is causing it yet. I did find that the `board.Draw` function seems to contribute to the problem, at least at a glance. For example, if I call the function three more times, it seems to reproduce the problem as soon as the next piece appears. However, if I play the sound before the next piece appears, it seems to be fine.

**Comment by Matias-Barrios** [comment]
@veeableful Thanks for checking on this. I'll try to check on that relationship and I'll post here with my findings

**Comment by Matias-Barrios** [comment]
@veeableful so I tried removing the board.Draw method entirely and it works fine. Then I tried  removing only the SDL.Draw from it, and it also works fine. 

So the issue is happening only because of the amount of times I call SDL.Draw. (?)

Do you have any idea if this is possible and why? I can help to solve the bug if you give me some hint

**Comment by veeableful** [comment]
Hi @Matias-Barrios,

I seem to have fixed it by allocating the destination rectangle for `Copy()` in the native C context. I suppose it has something to do with how Go's memory works (perhaps the rectangle got cleaned up before it can be used by SDL_Renderer?). I have pushed the fix into the `master` branch so let me know if it works for you!

**Comment by Matias-Barrios** [comment]
@veeableful Hi ! I have just downloaded the latest version and now it works perfectly fine. thanks so much for your help!! Your work is awesome.

**Comment by veeableful** [comment]
No problem! Thanks for reporting the issue!
