### ISSUE TITLE
Recent commit breaking use of render.Copy

### ISSUE THREAD

**Issue by jackmott** [veandco/go-sdl2#422]
This commit seems to have broken copy on some of my existing programs:
https://github.com/veandco/go-sdl2/commit/fbf6279185d95a1266b391df284c2db53a611649

`renderer.Copy(tex, nil, nil)`   now panics with a nil pointer dereference error.

Per SDL2 specs this should be allowed:
https://wiki.libsdl.org/SDL_RenderCopy

I'm not familiar with what was attempting to be fixed here with this change, so can't offer a fix, but am happy to help if anyone has pointers.

**Comment by veeableful** [comment]
Hi @jackmott, truly sorry about that! I should have fixed that in the `test` branch. Could I trouble you to go to `$GOPATH/src/github.com/veandco/go-sdl2/sdl` and run `git fetch`, `git checkout test`, `git reset --hard origin/test`, and finally `go install`? After that, you can try compiling your program again and see if it still happens. If everything's fine, I'll push to `master` branch immediately!

It was a workaround for a really strange [problem](https://github.com/veandco/go-sdl2/issues/420) where it affected audio playback by calling `sdl.Renderer.Copy()` using `sdl.Rect` from Go's context.

**Comment by jackmott** [comment]
Confirmed fixed, go ahead and push to master, thank you.

**Comment by veeableful** [comment]
Alright, I have pushed to master!
