### ISSUE TITLE
Vulkan functions not included in releases

### ISSUE THREAD

**Issue by jclc** [veandco/go-sdl2#425]
sdl/vulkan.go isn't included in any of the release tags, so the default module Go tries to use won't work if you want to work with Vulkan. This should probably be fixed for future releases.

**Comment by veeableful** [comment]
Hi @jclc, that's a very good point! I suppose I will push a v0.4.0 tag this weekend with the master branch once I have reviewed all the commits since v0.3.0 for the release write-up.

**Comment by jclc** [comment]
This seems to have been fixed.
