### ISSUE TITLE
go get github.com/veandco/go-sdl2/{img, mix} fails

### ISSUE THREAD

**Issue by CarterScadden** [veandco/go-sdl2#429]
When running in bash getting this error.
In file included from go/src/github.com/veandco/go-sdl2/img/sdl_image.go:5:0:
```
./sdl_image_wrapper.h:5:11: fatal error: SDL_image.h: No such file or directory
  #include <SDL_image.h>
                ^~~~~~~~~~~~~
```

```
In file included from go/src/github.com/veandco/go-sdl2/mix/midi.go:6:0:
./sdl_mixer_wrapper.h:4:11: fatal error: SDL_mixer.h: No such file or directory
  #include <SDL_mixer.h>
           ^~~~~~~~~~~~~
```

**Comment by veeableful** [comment]
Hi @CarterScadden, what platform are you on? Did you install the native libraries for SDL_image and SDL_Mixer?

**Comment by CarterScadden** [comment]
Yes sorry, I've resolved the issue didn't realize I needed to install those libraries from else where. Thank you
