### ISSUE TITLE
Alpha not working for big?? images

### ISSUE THREAD

**Issue by Matias-Barrios** [veandco/go-sdl2#431]
I have a weird issue when trying to add alpha to the background of my game. I have this function :

```
// Get a texture from a window, a renderer and a path
func GetTexture(w *sdl.Window, r *sdl.Renderer, path string, alpha uint8) *sdl.Texture {
	surface, err := w.GetSurface()
	if err != nil {
		panic(err)
	}
	surface.FillRect(nil, 0)

	surfaceImg, err := img.Load(path)
	if err != nil {
		log.Fatalf("Failed to load PNG: %s\n", err)
		os.Exit(4)
	}
	surfaceImg.SetAlphaMod(alpha)
	textureImg, err := r.CreateTextureFromSurface(surfaceImg)
	if err != nil {
		log.Fatalf("Failed to create texture: %s\n", err)
		os.Exit(5)
	}
	surfaceImg.Free()
	return textureImg
}
```

The problem is, it seems to make textures transparent only when they are small (??). for instance I can make each small block in my game transparent but it does not seem to affect the background, although both are drawn in the same way.

**Comment by veeableful** [comment]
Hi @Matias-Barrios, could you please create a very minimal example that demonstrate this issue? That would really help me in figuring out the issue. Thanks!

**Comment by Matias-Barrios** [comment]
Hi @veeableful . I have created this small repo which only draws a background and a block :+1: 
https://github.com/Matias-Barrios/transparency_bug

You can clone and play around with these two lines :
https://github.com/Matias-Barrios/transparency_bug/blob/master/main.go#L32-L33

You will see that although the transparency of the block changes the background is not affected. Please let me know if this is minimalist enough

**Comment by veeableful** [comment]
Hi @Matias-Barrios, it seems like the texture needs to set a blend mode via `textureImg.SetBlendMode(sdl.BLENDMODE_BLEND)` so any image can be made translucent. Otherwise, it seems like the image needs to be saved with RGBA color type (based on quick investigation using fotoforensics.com on the images).

**Comment by veeableful** [comment]
Oh and thank you very much for the mini example! That was super helpful! :smiley:

**Comment by Matias-Barrios** [comment]
@veeableful understood. Thanks for digging into this. I'll try to add the changes and contact you back in case of issues. Awesome! :)
