### ISSUE TITLE
SDL2 not found

### ISSUE THREAD

**Issue by ali2210** [veandco/go-sdl2#433]
![Capture](https://user-images.githubusercontent.com/20568079/65835744-50b5a780-e303-11e9-919e-c05da7fee36d.JPG)
 
I'm using your package in my project but hadn't download properly

**Comment by veeableful** [comment]
Hi @ali2210, it seems like the native packages are not installed for your environment. You can refer to our [Requirements](https://github.com/veandco/go-sdl2#requirements) in the README to see how they can be installed for your OS. Once you have done that, you should be able to use our package.

**Comment by ali2210** [comment]
Thank you for this valuable information
This Message send through secure channel called BBM



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
