### ISSUE TITLE
when i am try go get github.com/veandco/go-sdl2/sdl

### ISSUE THREAD

**Issue by sadek69** [veandco/go-sdl2#435]
or compile sdl2 test,
i am received this error 

src/github.com/veandco/go-sdl2/sdl/hints.go:86:50: could not determine kind of name for C.SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH

i am use osx mojave.
latest sdl2
and latest golang.
please help.

**Comment by veeableful** [comment]
Hi @sadek69,

That issue should have been fixed in the master branch. Could you try running `go get -v -u github.com/veandco/go-sdl2/sdl`?

**Comment by sadek69** [comment]
Hi @veeableful thank you who you try to help but after this command i am received this error

Aborting
package github.com/veandco/go-sdl2/sdl: exit status 1

he try to start update but exit with this mistake....
maybe you have more idea what me do?

**Comment by veeableful** [comment]
Hi @sadek69, is that the full output? If you run the command I posted, I believe it should at least show:
```
github.com/veandco/go-sdl2 (download)
```

**Comment by sadek69** [comment]
exes-Mac-mini:go _exe$ go get -v -u github.com/veandco/go-sdl2/sdl
github.com/veandco/go-sdl2 (download)
# cd /Users/_exe/go/src/github.com/veandco/go-sdl2; git pull --ff-only
error: The following untracked working tree files would be overwritten by merge:
	.go-sdl2-libs/include/SDL2/SDL.h
	.go-sdl2-libs/include/SDL2/SDL2_framerate.h
	.go-sdl2-libs/include/SDL2/SDL2_gfxPrimitives.h
	.go-sdl2-libs/include/SDL2/SDL2_imageFilter.h
	.go-sdl2-libs/include/SDL2/SDL2_rotozoom.h
	.go-sdl2-libs/include/SDL2/SDL_assert.h
	.go-sdl2-libs/include/SDL2/SDL_atomic.h
	.go-sdl2-libs/include/SDL2/SDL_audio.h
	.go-sdl2-libs/include/SDL2/SDL_bits.h
	.go-sdl2-libs/include/SDL2/SDL_blendmode.h
	.go-sdl2-libs/include/SDL2/SDL_clipboard.h
	.go-sdl2-libs/include/SDL2/SDL_config.h
	.go-sdl2-libs/include/SDL2/SDL_config_android_arm.h
	.go-sdl2-libs/include/SDL2/SDL_config_darwin_amd64.h
	.go-sdl2-libs/include/SDL2/SDL_config_linux_386.h
	.go-sdl2-libs/include/SDL2/SDL_config_linux_amd64.h
	.go-sdl2-libs/include/SDL2/SDL_config_linux_arm.h
	.go-sdl2-libs/include/SDL2/SDL_config_windows_386.h
	.go-sdl2-libs/include/SDL2/SDL_config_windows_amd64.h
	.go-sdl2-libs/include/SDL2/SDL_cpuinfo.h
	.go-sdl2-libs/include/SDL2/SDL_egl.h
	.go-sdl2-libs/include/SDL2/SDL_endian.h
	.go-sdl2-libs/include/SDL2/SDL_error.h
	.go-sdl2-libs/include/SDL2/SDL_events.h
	.go-sdl2-libs/include/SDL2/SDL_filesystem.h
	.go-sdl2-libs/include/SDL2/SDL_gamecontroller.h
	.go-sdl2-libs/include/SDL2/SDL_gesture.h
	.go-sdl2-libs/include/SDL2/SDL_haptic.h
	.go-sdl2-libs/include/SDL2/SDL_hints.h
	.go-sdl2-libs/include/SDL2/SDL_image.h
	.go-sdl2-libs/include/SDL2/SDL_joystick.h
	.go-sdl2-libs/include/SDL2/SDL_keyboard.h
	.go-sdl2-libs/include/SDL2/SDL_keycode.h
	.go-sdl2-libs/include/SDL2/SDL_loadso.h
	.go-sdl2-libs/include/SDL2/SDL_log.h
	.go-sdl2-libs/include/SDL2/SDL_main.h
	.go-sdl2-libs/include/SDL2/SDL_messagebox.h
	.go-sdl2-libs/include/SDL2/SDL_mixer.h
	.go-sdl2-libs/include/SDL2/SDL_mouse.h
	.go-sdl2-libs/include/SDL2/SDL_mutex.h
	.go-sdl2-libs/include/SDL2/SDL_name.h
	.go-sdl2-libs/include/SDL2/SDL_opengl.h
	.go-sdl2-libs/include/SDL2/SDL_opengl_glext.h
	.go-sdl2-libs/include/SDL2/SDL_opengles.h
	.go-sdl2-libs/include/SDL2/SDL_opengles2.h
	.go-sdl2-libs/include/SDL2/SDL_opengles2_gl2.h
	.go-sdl2-libs/include/SDL2/SDL_opengles2_gl2ext.h
	.go-sdl2-libs/include/SDL2/SDL_opengles2_gl2platform.h
	.go-sdl2-libs/include/SDL2/SDL_opengles2_khrplatform.h
	.go-sdl2-libs/include/SDL2/SDL_pixels.h
	.go-sdl2-libs/include/SDL2/SDL_platform.h
	.go-sdl2-libs/include/SDL2/SDL_power.h
	.go-sdl2-libs/include/SDL2/SDL_quit.h
	.go-sdl2-libs/include/SDL2/SDL_rect.h
	.go-sdl2-libs/include/SDL2/SDL_render.h
	.go-sdl2-libs/include/SDL2/SDL_revision.h
	.go-sdl2-libs/include/SDL2/SDL_rwops.h
	.go-sdl2-libs/include/SDL2/SDL_scancode.h
	.go-sdl2-libs/include/SDL2/SDL_shape.h
	.go-sdl2-libs/include/SDL2/SDL_stdinc.h
	.go-sdl2-libs/include/SDL2/SDL_surface.h
	.go-sdl2-libs/include/SDL2/SDL_system.h
	.go-sdl2-libs/include/SDL2/SDL_syswm.h
	.go-sdl2-libs/include/SDL2/SDL_test.h
	.go-sdl2-libs/include/SDL2/SDL_test_assert.h
	.go-sdl2-libs/include/SDL2/SDL_test_common.h
	.go-sdl2-libs/include/SDL2/SDL_test_compare.h
	.go-sdl2-libs/include/SDL2/SDL_test_crc32.h
	.go-sdl2-libs/include/SDL2/SDL_test_font.h
	.go-sdl2-libs/include/SDL2/SDL_test_fuzzer.h
	.go-sdl2-libs/include/SDL2/SDL_test_harness.h
	.go-sdl2-libs/include/SDL2/SDL_test_images.h
	.go-sdl2-libs/include/SDL2/SDL_test_log.h
	.go-sdl2-libs/include/SDL2/SDL_test_md5.h
	.go-sdl2-libs/include/SDL2/SDL_test_memory.h
	.go-sdl2-libs/include/SDL2/SDL_test_random.h
	.go-sdl2-libs/include/SDL2/SDL_thread.h
	.go-sdl2-libs/include/SDL2/SDL_timer.h
	.go-sdl2-libs/include/SDL2/SDL_touch.h
	.go-sdl2-libs/include/SDL2/SDL_ttf.h
	.go-sdl2-libs/include/SDL2/SDL_types.h
	.go-sdl2-libs/include/SDL2/SDL_version.h
	.go-sdl2-libs/include/SDL2/SDL_video.h
	.go-sdl2-libs/include/SDL2/SDL_vulkan.h
	.go-sdl2-libs/include/SDL2/begin_code.h
	.go-sdl2-libs/include/SDL2/close_code.h
	.go-sdl2-libs/libSDL2_android_arm.a
	.go-sdl2-libs/libSDL2_darwin_amd64.a
	.go-sdl2-libs/libSDL2_gfx_android_arm.a
	.go-sdl2-libs/libSDL2_gfx_darwin_amd64.a
	.go-sdl2-libs/libSDL2_gfx_linux_386.a
	.go-sdl2-libs/libSDL2_gfx_linux_amd64.a
	.go-sdl2-libs/libSDL2_gfx_linux_arm.a
	.go-sdl2
Aborting
package github.com/veandco/go-sdl2/sdl: exit status 1


this is full output!

**Comment by veeableful** [comment]
Hi @sadek69, could you delete the whole directory like so:
```
rm -rf /Users/_exe/go/src/github.com/veandco/go-sdl2
```

and run `go get -u -v github.com/veandco/go-sdl2/sdl` again?

**Comment by sadek69** [comment]
thank you.now all work.
