### ISSUE TITLE
How to install SDL_gfx on windows

### ISSUE THREAD

**Issue by Suceru** [veandco/go-sdl2#444]
Mingw is currently installed, its directory is in  `D:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64
`, the SDL_image and ttf are installed to copy the entire `SDL2_image-devel-2.0.5-mingw.tar.gz\SDL2_image-devel-2.0.5-mingw.tar\SDL2_image-2.0.5\x86_64-w64-mingw32` folder to `D:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32 
`

But SDL_gfx is different from SDL_ttf, it does not have the x86_64-w64-mingw32 folder, I do not understand how to install  SDL_gfx-2.0.26.tar.gz to Windows 10 .

**Comment by veeableful** [comment]
Hi @Suceru! Sorry for the late reply. Could you try [this](https://github.com/veandco/go-sdl2/issues/427) method and see if it works for you? I will add it to the README if it's simple enough to follow.

**Comment by Suceru** [comment]
> Hi @Suceru! Sorry for the late reply. Could you try this method and see if it works for you? I will add it to the README if it's simple enough to follow.
@veeableful 
I'm not familiar with mingw, i downloaded` SDL2_gfx.dll` and put it in the `\bin` directory like `SDL_image`. Then copy all the `.h` files to the `x86_64-w64-mingw32\include\SDL2` folder, and change the file name and header file to 2 (eg:like SDL2_gfxPrimitives.h). When using `go run C:\Users\fidax\go\src\github.com\veandco\go-sdl2\.go-sdl2-examples\examples\gfx` command, it prompts `ld.exe: cannot find -lSDL2_gfx`
<img width="387" alt="SDL2_gfx" src="https://user-images.githubusercontent.com/20983345/71775611-64397400-2fbe-11ea-8ed2-1a498898b624.png">
copy to
<img width="960" alt="folder" src="https://user-images.githubusercontent.com/20983345/71775577-0147dd00-2fbe-11ea-962d-a4318485e96e.png">
change the file names
<img width="250" alt="header name" src="https://user-images.githubusercontent.com/20983345/71775578-0147dd00-2fbe-11ea-994e-7032d0e3ea02.png">
In CMD run `go run gfx.go`
<img width="960" alt="cmd go run" src="https://user-images.githubusercontent.com/20983345/71775576-00af4680-2fbe-11ea-9fd4-ce91d3842494.png">

**Comment by veeableful** [comment]
Hi @Suceru, have you tried to put it inside `lib` as well?

**Comment by Suceru** [comment]
@veeableful 
Sorry, when I did this, I didn't know what I should do next.
I have put `SDL2_gfx.dll` in  `\lib`, Run ... .
<img width="960" alt="copy" src="https://user-images.githubusercontent.com/20983345/72141118-2f1d8f00-33cd-11ea-824a-133e19e4bb14.png">
<img width="960" alt="cmd go run" src="https://user-images.githubusercontent.com/20983345/72141117-2e84f880-33cd-11ea-867f-b1f7665571a7.png">

```
# github.com/veandco/go-sdl2/gfx
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:91:90: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_pixelColor
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:103:86: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_pixelRGBA
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:113:81: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_hlineColor
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:126:92: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_hlineRGBA
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:136:81: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_vlineColor
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:149:92: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_vlineRGBA
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:160:91: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_rectangleColor
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:174:102: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_rectangleRGBA
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:186:104: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_roundedRectangleColor
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:201:115: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_roundedRectangleRGBA
go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:201:115: too many errors

```

**Comment by veeableful** [comment]
Hmm that's strange.. are you using `sdl.Surface` instead of `sdl.Renderer` with `gfx` functions?

**Comment by Suceru** [comment]
@veeableful I am directly running the code for the example.

> go\src\github.com\veandco\go-sdl2\.go-sdl2-examples\examples\gfx\gfx.go
That's what he originally wrote.
So, I don't known

**Comment by veeableful** [comment]
Hi @Suceru, I see that you are using `sdl.Surface` (at least from what I can tell in the screenshot above) and the example doesn't have `sdl.Surface`. Are you using the latest `go-sdl2`?

**Comment by Suceru** [comment]
Yes, `go-sdl2` is the latest version. There is no `SDL_surface` code in the examples, only `SDL_renderer`. 
The location of this `error` message comes from the file `SDL_gfx.go
`

>   # github.com/veandco/go-sdl2/gfx
> go\src\github.com\veandco\go-sdl2\gfx\sdl_gfx.go:91:90: cannot use _cgo0 (type *_Ctype_struct_SDL_Renderer) as type *_Ctype_struct_SDL_Surface in argument to _Cfunc_pixelColor
> 

My other SDL2 configurations can be used normally, but `sdl_gfx` does not know how to install. I put the `sdl_gfx.dll` in the link you posted earlier into the `\ bin `and `\ lib` folders (I don't know if it is correct). In addition, copy the .h file in the downloaded `sdl_gfx` archive to the` \included\sdl2` folder and then` #include <SDL/SDL.h>` inside changed to `#include <SDL2/SDL.h>`
When the` #include <SDL2 / SDL.h>` error is not prompted, show `the SDL_surface cannot be used`. My intuition is that only `go-sdl_gfx` is correct, there should be problems in the setting part of` mingw
`

**Comment by veeableful** [comment]
Hmm that's weird... Could you post the definition of `pixelColor` in the `SDL2_gfxPrimitives.h` file? The one I have looks like this:

```c
SDL2_GFXPRIMITIVES_SCOPE int pixelColor(SDL_Renderer * renderer, Sint16 x, Sint16 y, Uint32 color);
```

**Comment by Suceru** [comment]
@veeableful Oh, thank you guys, I have configured. 
First of all, I mistakenly regarded the `gfx of SDL `as the `gfx of SDL2` (I saw two `versions 1.0.4` and `2.0.25` on the website, I didn't pay much attention to `2.0.25` as the latest version of SDL2). Then I copied `the .h and .c files` of `SDL2-gfx` to the ` \include\SDL2 of mingw` folder  and it worked fine.
The correct is: 
<img width="349" alt="need SDL2-gfx" src="https://user-images.githubusercontent.com/20983345/72696424-16546c80-3b77-11ea-8b31-34d9c72cfe20.PNG">
The err is: 
<img width="290" alt="err sdl-gfx" src="https://user-images.githubusercontent.com/20983345/72696432-1a808a00-3b77-11ea-9a14-2d80eccefff8.PNG">
`put .h and .c to \SDL2`
<img width="652" alt="put to sdl" src="https://user-images.githubusercontent.com/20983345/72696439-21a79800-3b77-11ea-89f0-81b5ed8da8ee.PNG">
put `SDL_gfx.dll to \bin and \lib`(If this are missing , will be errs:1. `exit status 3221225781` and 2. ```
/x86_64-w64-mingw32/bin/ld.exe: cannot find -lSDL2_gfx
collect2.exe: error: ld returned 1 exit status
``` )

<img width="582" alt="SDL2_gfx-dll" src="https://user-images.githubusercontent.com/20983345/72696786-81527300-3b78-11ea-9dd4-a72021db1537.PNG">

**Comment by Suceru** [comment]
@veeableful It turns out that the method you proposed earlier is correct, as long as you download `the .dll file and .h and .c files`, you can use it.
<img width="591" alt="run" src="https://user-images.githubusercontent.com/20983345/72697012-4bfa5500-3b79-11ea-91a1-44ac3e622938.PNG">

**Comment by veeableful** [comment]
No problem @Suceru! Glad I could help 😃
