### ISSUE TITLE
Use of platform-specific int type for JoyDeviceAddedEvent.Which

### ISSUE THREAD

**Issue by seletskiy** [veandco/go-sdl2#451]
Line in question:

https://github.com/veandco/go-sdl2/blob/0f0aff6510ff6b885d668509789fbf6120e47d8c/sdl/events.go#L564

I believe this should be [declared as `int32`][1] instead of `int`, since it will be silently compiled as `int64` on 64-bit systems.

In particular, [`joystick-input`][2] example from `go-sdl2-examples` fails with panic because of that.

[1]: https://wiki.libsdl.org/SDL_JoyDeviceEvent
[2]: https://github.com/veandco/go-sdl2-examples/tree/master/examples/joystick-input

**Comment by veeableful** [comment]
Hi @seletskiy, thank you for catching that. I have changed it to use `sdl.JoystickID` which is an `int32` in the latest patch version!

**Comment by seletskiy** [comment]
@veeableful: nice one!
