### ISSUE TITLE
os x rendering bug

### ISSUE THREAD

**Issue by xTal96** [veandco/go-sdl2#452]
I'm having this bug with go-sdl2 on mac os x catalina, it seems like the renderer has a lot of padding, for example, this red box should be rendered at (0, 0):
<img width="912" alt="Screen Shot 2020-02-22 at 14 55 10" src="https://user-images.githubusercontent.com/10939574/75092755-af661100-5583-11ea-9270-e598b1de2a51.png">
after changing the window's position the box is renderer properly, like this:
<img width="912" alt="Screen Shot 2020-02-22 at 14 59 12" src="https://user-images.githubusercontent.com/10939574/75092771-edfbcb80-5583-11ea-8996-a6e0027cb051.png">
only happens on my mac machine, tried to reproduce with same code on windows but it works fine there

**Comment by veeableful** [comment]
Hi @xTal96, could I bother you with providing an minimal example code that reproduces this? I simply would like to know if it's an issue with the binding or SDL2 itself.

**Comment by xTal96** [comment]
I updated my os to the latest version and now it won't happen,
closing
