### ISSUE TITLE
why do some original functions not exist in this project?

### ISSUE THREAD

**Issue by l-f-h** [veandco/go-sdl2#455]
Some original functions suck like 
[SDL_SetVideoMode](http://dranger.com/ffmpeg/functions.html#SDL_SetVideoMode)
[SDL_CreateYUVOverlay](http://dranger.com/ffmpeg/functions.html#SDL_CreateYUVOverlay)
etc...
I could't found them in go-sdl project, but we really need them!
why not add these functions?

**Comment by gen2brain** [comment]
These functions are for SDL1 and are removed from SDL2. Bindings are for ver2 and there you create SDL_Texture with YV12 format for something like you want to do.

**Comment by l-f-h** [comment]
Thanks~
