### ISSUE TITLE
`RenderUTF8Blended` doesn't work well

### ISSUE THREAD

**Issue by danielgatis** [veandco/go-sdl2#463]
Hi!

I'm trying to write some strings:

```
	var surface *sdl.Surface
	if surface, err = ft.RenderUTF8Blended("🐹", color); err != nil {
		return nil, nil, errors.Wrap(err, "Failed to draw")
	}
```

With this font:
```
❯ fc-match --format=%{file} "FiraCode Nerd Font"
/Users/daniel/Library/Fonts/Fira Code Regular Nerd Font Complete.otf% 
```

But I'm getting this output:
<img width="614" alt="Screen Shot 2020-05-23 at 19 46 31" src="https://user-images.githubusercontent.com/7380/82741931-20a59380-9d2e-11ea-8c5c-a7c5f4e59294.png">

What's wrong?

**Comment by veeableful** [comment]
Hi @danielgatis, does the font contain the emoji? I tested with other fonts such as NotoColorEmoji and it seems to draw it.

**Comment by danielgatis** [comment]
@veeableful 
you are right, I also did the same teste but the glyph color is grayscale. There is no color support?
