### ISSUE TITLE
Plan to add iOS compilation support ?

### ISSUE THREAD

**Issue by QiProject** [veandco/go-sdl2#466]
Or any guide that's we could build it our own ?

**Comment by veeableful** [comment]
Hi @QiProject,

We don't have any effort in adding iOS compilation support yet as I'm unknowledgeable in that area. We certainly could use some help! Otherwise, I might need to learn about the iOS development process.

**Comment by QiProject** [comment]
It’d be great if it could support iOS since sdl itself support iOS, 
And go is a such good Lang to work, hope id help some of this in the future.

**Comment by gedw99** [comment]
i have a mac  and ios device to test on, if anyone needs a guinea pig to test on :)

**Comment by veeableful** [comment]
Thanks for the kind offer, @gedw99! I will let you know once we start implementing support for iOS.
