### ISSUE TITLE
Manipulating Pixel on SDL.Texture Didn't Work as Expected

### ISSUE THREAD

**Issue by RoganMatrivski** [veandco/go-sdl2#468]
I've made a simple program that will make a square window filled with a blue gradient. Here's the snippet: 
```golang
package main

import "github.com/veandco/go-sdl2/sdl"

const (
	SCREEN_WIDTH  = 512
	SCREEN_HEIGHT = 512
)

func hPanic(err error) {
	if err != nil {
		panic(err)
	}
}

func mapval(i int, iMax int, max float64) float64 {
	return float64(float64(i)/float64(iMax)) * max
}

func main() {
	_, renderer, err := sdl.CreateWindowAndRenderer(SCREEN_WIDTH, SCREEN_HEIGHT, sdl.WINDOW_SHOWN)
	hPanic(err)

	if err := renderer.SetDrawColor(0xFF, 0xFF, 0xFF, 0xFF); err != nil {
		hPanic(err)
	}

	tex, err := renderer.CreateTexture(sdl.PIXELFORMAT_ARGB8888, sdl.TEXTUREACCESS_STREAMING, SCREEN_WIDTH, SCREEN_HEIGHT)
	hPanic(err)

	px, pitch, err := tex.Lock(nil)
	hPanic(err)

	texLockedX, texLockedY := pitch/4, len(px)/pitch

	// B G R Alpha
	for y := 0; y < texLockedY; y++ {
		for x := 0; x < texLockedX; x++ {
			currentIdxPos := ((y * texLockedY) + x) * 4
			px[currentIdxPos+0] = byte(mapval(x, texLockedX, 255))
			px[currentIdxPos+1] = 0
			px[currentIdxPos+2] = 0
			px[currentIdxPos+3] = 255
		}
	}

	tex.Unlock()

	renderer.Copy(tex, nil, nil)
	renderer.Present()

	sdl.Delay(2000)
	return
}
```
And it works as expected

![image](https://user-images.githubusercontent.com/19743747/87363271-01dbb480-c59b-11ea-8ff5-be39cfaae1a8.png)

But if I change the width to a smaller value, this error shows up:

![image](https://user-images.githubusercontent.com/19743747/87363330-22a40a00-c59b-11ea-824a-9f5b7dfed156.png)

And if I change it to a bigger value, the code runs fine. But it doesn't show the correct result.

![image](https://user-images.githubusercontent.com/19743747/87363417-52531200-c59b-11ea-9e69-dd308920f825.png)

Am i doing it wrong?

**Comment by veeableful** [comment]
Hi @RoganMatrivski, I'm really sorry for the wait! I believe the `currentIdxPos` line should be `currentIdxPos := (x + y * texLockedX) * 4` so it multiplies the width by the y instead of the height by the y.

**Comment by RoganMatrivski** [comment]
Oh god that was a dumb mistake. After fixing it with your suggestions it works. Thanks! And sorry for taking your time.
![image](https://user-images.githubusercontent.com/19743747/87867077-5cb64700-c9b3-11ea-8483-d104ac0afc2f.png)
