### ISSUE TITLE
# github.com/veandco/go-sdl2/sdl cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by watchdog19** [veandco/go-sdl2#469]
This is the error message i get

**Comment by veeableful** [comment]
Hi @watchdog19, could you mention your operating system and Go version (run `go version`), and the command you ran to get the error message?

**Comment by watchdog19** [comment]
I use Windows 
**go env**
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Osose\AppData\Local\go-build
set GOENV=C:\Users\Osose\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Osose\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Osose\AppData\Local\Temp\go-build747574890=/tmp/go-build -gno-record-gcc-switches

I was running a program that will create a new window and i got the error message

**Comment by vault-thirteen** [comment]
I have the same error when I tri to start the "Hello, World" example from the `readme` file :)
