### ISSUE TITLE
about renderers ReadPixel usage

### ISSUE THREAD

**Issue by sigzegv** [veandco/go-sdl2#477]
How am I supposed to use renderer.ReadPIxels pixel parameter ?

I am doing this

    renderer.SetRenderTarget(t)
    var pixels unsafe.Pointer
    renderer.ReadPixels(nil, sdl.PIXELFORMAT_ARGB8888, pixels, int(unsafe.Sizeof(uint32(1)))*int(width))
    fmt.Printf("%#v\n", pixels)

but I just get (unsafe.Pointer)(nil) as response. So this mean my pixels array wasn't filled.

I would like to be able to load pixels data and then convert it to either []byte or *uint32.

**Comment by veeableful** [comment]
Hi @sigzegv, you can pass the address of the first item of an array such as `unsafe.Pointer(&pixels[0])`. So `pixels` can be declared like `var pixels = make([]byte, width*height*channels)`.

**Comment by sigzegv** [comment]
I am not realy familiar with unsafe.pointer type, am I forced to use then the texture Update method to reaffect the pixels ? or is there a way then to indirect value to the pointer directly ?

**Comment by gen2brain** [comment]
@sigzegv You have an example here https://play.golang.org/p/14JFZvpukGK, ReadPixels is a slow operation.

**Comment by sigzegv** [comment]
Do you think it's better (and quicker) to maintain a Surface at same time and then push it to a new texture when needed to ?

**Comment by gen2brain** [comment]
Depends on what you want to do, check migration guide https://wiki.libsdl.org/MigrationGuide, and `If your game wants to blit surfaces to the screen/If your game wants to do both`, but yes, that is the recommended method for what you want.

**Comment by sigzegv** [comment]
thank you very much it's clear now.
