### ISSUE TITLE
ttf does not offer `TTF_RenderGlyph_Solid`

### ISSUE THREAD

**Issue by GXTX** [veandco/go-sdl2#488]
As the title states currently in `v0.4.x` the TTF package does not offer a RenderGlyphSolid (`TTF_RenderGlyph_Solid`), instead opting to offer RenderUTF8Solid.

In a project I'm working on UTF8 causes problems for me and I just need base ASCII glyphs.

**Comment by GXTX** [comment]
You can ignore this. The UTF8 render is suitable.

**Comment by veeableful** [comment]
Hi @GXTX, thanks for reporting the missing methods! I have added them to `v0.4.x` should you be interested in using them. I haven't tested them myself but once I do, I will tag it as `v0.4.8`.
