### ISSUE TITLE
events.go Compilation Error

### ISSUE THREAD

**Issue by gusbin** [veandco/go-sdl2#49]
Hi all. I'm trying to install the SDL2 bindings and followed the instructions. However the compilation terminates at the events.go file, which the following:

D:\gocode\src\github.com\veandco\go-sdl2\sdl\events.go:5:20: fatal error: events
.h: No such file or directory
 #include "events.h"
                    ^
compilation terminated.

Looking at the events.go source I'm missing the events.h header file. It's not included in the SDL distrubtion and not in the repo. Where can I find "events.h" and "events.c"?

I run Windows 7 64bit. SDL2 download was SDL2-devel-2.0.3-mingw and a working Mingw-64 compiler.

Thanks in advance folks!

Gusbin

**Comment by paytonrules** [comment]
I am getting this again with the latest build. 

Erics-MacBook-Pro:CubicleWars paytonrules$ go test ./...
ok  	github.com/paytonrules/CubicleWars	0.004s
# github.com/veandco/go-sdl2/sdl
../../veandco/go-sdl2/sdl/events.go:5:10: fatal error: 'events.h' file not found
#include "events.h"
