### ISSUE TITLE
Using depracated function SDL_GetRevisionNumber()

### ISSUE THREAD

**Issue by MightyPancake** [veandco/go-sdl2#490]
Please correct me if I'm wrong, but I think SDL_GetRevisionNumber() is being used and SDL2 outputs a warning about it being a deprecated thing.
Although the binding still works, it outputs this nasty warning
`# github.com/veandco/go-sdl2/sdl
cgo-gcc-prolog: In function '_cgo_a4414542972c_Cfunc_SDL_GetRevisionNumber':`
From what I found replacing the call with SDL_GetRevision() should do the trick, I'm just having a hard time finding it.

Thanks in advance!

**Comment by veeableful** [comment]
Hi @MightyPancake, thanks for reporting this issue! I pushed a commit that should show the deprecation warning on staticcheck (also on VS Code using the plugin) only when users use `sdl.GetRevisionNumber()`.

**Comment by MightyPancake** [comment]
> Hi @MightyPancake, thanks for reporting this issue! I pushed a commit that should show the deprecation warning on staticcheck (also on VS Code using the plugin) only when users use `sdl.GetRevisionNumber()`.

Everything works after this commit got released! Thanks for the great response time.
Cheers!
