### ISSUE TITLE
error while getting SDL with go

### ISSUE THREAD

**Issue by ConnorHQ** [veandco/go-sdl2#503]
./sdl_wrapper.h:2:11: fatal error: SDL2/SDL.h: No such file or directory
  #include <SDL2/SDL.h>
           ^~~~~~~~~~~~
compilation terminated.

**Comment by veeableful** [comment]
Hi @ConnorHQ, could you share more information? Did you install the SDL2 library? Which OS are you running it on? What's your SDL2 and go-sdl2 version?

**Comment by Semj0n** [comment]
Hi, i'm having the same issue. While installing:

In file included from ..\..\go\pkg\mod\github.com\veandco\go-sdl2@v0.4.12\sdl\audio.go:4:0:
./sdl_wrapper.h:2:11: fatal error: SDL2/SDL.h: No such file or directory
  #include <SDL2/SDL.h>
           ^~~~~~~~~~~~
compilation terminated.

OS  = Windows 10
I've installed mingw and put the SDL files into C:\Program Files\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\
I also added this to PATH

How to tell go to look for .h files in a specific folder?

Anyone running this on Windows 10?

**Comment by veeableful** [comment]
Hi @Semj0n, did you copy SDL2's `i686-w64-mingw32` and / or `x86_64-w64-mingw32` directories into `C:\Program Files\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64`? Can your shell find `gcc`?

**Comment by Semj0n** [comment]
Hi @veeableful, i've copied x86_64-w64-mingw32 and yes, i can find gcc. 
Any ideas ?

**Comment by Semj0n** [comment]
@veeableful , @ConnorHQ 

I found another dir C:\Program Files\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\x86_64-w64-mingw32

copied the SDL files to this dir solves the problem!

Thanks @veeableful

**Comment by veeableful** [comment]
Nice @Semj0n! Don’t mention it 🙂

**Comment by ConnorHQ** [comment]
thanks!
