### ISSUE TITLE
install/ build SDL2_gfx

### ISSUE THREAD

**Issue by Semj0n** [veandco/go-sdl2#505]
Hi, 

i'd ilke to make use of functions provided in the gfx package. 
when i try to install it with: > go get github.com/veandco/go-sdl2/gfx

i get
C:/Program Files/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lSDL2_gfx
collect2.exe: error: ld returned 1 exit status

I'm able to build SDL2 and SDL2_gfx lib with VStudio for win32 x64 but the bindings seems only to acceppt .a files..

How to compile and run the lib on windows x64? 

Regards,
Sam

**Comment by veeableful** [comment]
Hi Semj0n, I don't have Windows with me at the moment but perhaps it would be easier for you to use MSYS2 and install SDL2 and SDL2_gfx using the following command:
```
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2{,_gfx}
```

Then I think you need to add something like `C:\mingw\bin` to the PATH environment variable. You might also need to remove previous MinGW paths from it so you will only use the ones installed by MSYS2.

I'm not sure if my instructions are correct but I'll test it myself once I have Windows with me!

**Comment by veeableful** [comment]
Hi @Semj0n, I corrected the MSYS2 path for environment variable in my previous comment. It seems to work on my Windows installation so please let me know if it works for you too!
