### ISSUE TITLE
Add support for SDL_GetTicks64

### ISSUE THREAD

**Issue by kbolino** [veandco/go-sdl2#509]
SDL 2.0.18 added [`SDL_GetTicks64`](https://wiki.libsdl.org/SDL_GetTicks64) which returns a `Uint64` instead of the `Uint32` returned by [`SDL_GetTicks`](https://wiki.libsdl.org/SDL_GetTicks), removing the need to use tricks to handle rollover after 49 days. It would be nice to have this available in Go, e.g. as `sdl.GetTicks64()`.

I can submit a PR if desired.

**Comment by veeableful** [comment]
Hi @kbolino, thanks for reporting this! I have added it and tagged `v0.4.15`.
