### ISSUE TITLE
Can't get sdl

### ISSUE THREAD

**Issue by Jonathan0827** [veandco/go-sdl2#514]
How can I fix this
<img width="3008" alt="스크린샷 2022-03-29 오후 6 46 06" src="https://user-images.githubusercontent.com/74815888/160584012-710b4af0-6ca6-41bf-b8b5-08c89bf12d1a.png">
?

**Comment by veeableful** [comment]
Hi @Jonathan0827! You can first create a Go module in your current directory by running `go mod init [name]` (replace [name] with your project name). Then you can run the `go get -v github.com/veandco/go-sdl2/gfx` command like what you did earlier.

**Comment by Jonathan0827** [comment]
Thanks a lot! It worked like a magic
