### ISSUE TITLE
Build error during docker container build of retro-cs

### ISSUE THREAD

**Issue by cvermazen** [veandco/go-sdl2#530]
During the build of a Docker container build: Dockerfile contents:

FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y \
    golang \
    git \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libsdl2-gfx-dev

RUN mkdir -p /root/go/src/github.com/blackchip-org/retro-cs
RUN go get github.com/veandco/go-sdl2/sdl
RUN go get github.com/chzyer/readline

During the step 5: RUN go get github.com/veandco/go-sdl2/sdl

I get the error:

root/go/src/github.com/veandco/go-sdl2/sdl/log.go:55:18: could not determine kind of name for C.SDL_LogCategory
The command '/bin/sh -c go get github.com/veandco/go-sdl2/sdl' returned a non-zero code: 2

Can anybody help me with this error, I don't know a solution for it.
Thanks in advance.

**Comment by veeableful** [comment]
Hi @cvermazen , it seems like the container is using Go provided by Ubuntu 18.04 which is relatively old at `v1.10`. Could you use newer Go, at least `v1.13`? Since we are using Go modules now, the minimum Go version has been bumped to `v1.13`.

**Comment by cvermazen** [comment]
Thanks for the fast update. I will give it a try.
Thanks

**Comment by veeableful** [comment]
@cvermazen Oh and be sure to use go-sdl2 `0.4.24` as I think that error comes from using the go-sdl2's `master` branch which is what Go older than `v1.13` would use by default.

**Comment by cvermazen** [comment]
Thanks for the reply's
