### ISSUE TITLE
16-bit textures?

### ISSUE THREAD

**Issue by marethyu** [veandco/go-sdl2#533]
I have a 16-bit frame buffer: `buffer [WIDTH * HEIGHT]uint16`. Each pixel follows the following format: `MBBBBBGGGGGRRRRR` (M is either 0 or 1). I am wondering whether Go's SDL2 package support rendering 16-bit textures like this. It seems to support pixel format `SDL_PIXELFORMAT_BGR555` so I can create a texture like this
```
texture, err = renderer.CreateTexture(sdl.PIXELFORMAT_BGR555, sdl.TEXTUREACCESS_STREAMING, WIDTH, HEIGHT)
```
but how to update texture with 16-bit framebuffer? `texture.Update(...)` only works for byte arrays not array of u16s.

**Comment by veeableful** [comment]
Hi @marethyu, thanks for reporting this issue! It does seem to be quite troublesome if you have an array of uint16. Do you think it's acceptable if I change the type from `[]byte` to `unsafe.Pointer`? That way, you can use array of any type as the data by passing it like this full example if you use []uint16:
```package main

import (
	"unsafe"

	"github.com/veandco/go-sdl2/sdl"
)

const (
	WIDTH = 800
	HEIGHT = 600
)

func buildPixels(width, height int) (pixels []uint16) {
	pixels = make([]uint16, width * height)
	for i := 0; i < width * height; i++ {
		pixels[i] = 0b1111110000000000 // blue
	}
	return
}

func main() {
	sdl.Init(sdl.INIT_VIDEO)
	win, renderer, _ := sdl.CreateWindowAndRenderer(WIDTH, HEIGHT, sdl.WINDOW_SHOWN)
	texture, _ := renderer.CreateTexture(sdl.PIXELFORMAT_BGR555, sdl.TEXTUREACCESS_STREAMING, WIDTH, HEIGHT)
	defer texture.Destroy()
	defer renderer.Destroy()
	defer win.Destroy()
	defer sdl.Quit()

	textureWidth, textureHeight := int32(100), int32(100)
	pixels := buildPixels(int(textureWidth), int(textureHeight))
	rect := sdl.Rect{0, 0, textureWidth, textureHeight}
	pitch := int(textureWidth * 2)
	texture.Update(&rect, unsafe.Pointer(&pixels[0]), pitch)

	running := true
	for running {
		for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
			switch event.(type) {
			case *sdl.QuitEvent:
				running = false
			}
		}

		renderer.Copy(texture, nil, nil)
		renderer.Present()

		sdl.Delay(33)
	}
}
```

**Comment by marethyu** [comment]
@veeableful Thank you for providing an example! But what version did you use? My compiler is complaining that unsafe doesn't work with byte array
```
cannot use unsafe.Pointer(&pixels[0]) (value of type unsafe.Pointer) as []byte value in argument to texture.Updatecompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#IncompatibleAssign)
```

**Comment by veeableful** [comment]
Oh sorry @marethyu, I was only proposing to change the API so that example would work and wondered if you'd think it's acceptable. I have pushed it to Github as `v0.4.25` now if you'd like to try the example again.

**Comment by marethyu** [comment]
@veeableful Perfect, it is working well! Thank you for all the support!
