### ISSUE TITLE
TextInputEvent missing GetText()

### ISSUE THREAD

**Issue by kazzmir** [veandco/go-sdl2#535]
Commit 1aaca478b312bea92192d243d7f2c19a1369fc14 removed the GetText() function from TextInputEvent and TextEditingEvent. It looks like this is an oversight, as the other functions for those events remain (GetTimestamp(), GetType(), ...).

GetText() can trivially be implemented as
```
func (e TextEditingEvent) GetText() string {
  return e.Text
}
```
and the same for TextInputEvent.

I think GetText() should remain to keep API compatability.

**Comment by veeableful** [comment]
Hi @kazzmir, thanks for reporting this! I have added them back in the `master` branch.

**Comment by kazzmir** [comment]
:+1:
