### ISSUE TITLE
build error with windows in top-of-tree

### ISSUE THREAD

**Issue by mmp** [veandco/go-sdl2#537]
With top-of-tree (aka 0696db96700f2b8) I'm seeing this error with Windows builds. (I assume it's just a matter of a missing cast.)

```
Error: C:\Users\runneradmin\go\pkg\mod\github.com\veandco\go-sdl2@v0.5.0-alpha.3.0.20220912155024-0696db96700f\sdl\guid.go:38:33: cannot use _cap (variable of type _Ctype_ulong) as type _Ctype_ulonglong in argument to (_Cfunc_SDL_malloc)
```

**Comment by veeableful** [comment]
Hi @mmp, thanks for the reporting of issues again! It should be fixed in the `master` branch now.

**Comment by mmp** [comment]
Looks good now--thank you!
