### ISSUE TITLE
SDL2_gfx linker error cross compiling from Linux to Windows

### ISSUE THREAD

**Issue by smagrath** [veandco/go-sdl2#547]
Go version:  go1.19.3 linux/amd64
Go-SDL2 version: 2.26.1
OS: Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Architecture: AMD64

I'm am trying to cross compile my project from Linux to Windows. I have followed the main instructions plus the extra advice for compiling for SDL2_gfx  #427  so I have the gfx headers in my mingw include directories etc

I get a linker error:
`/usr/bin/x86_64-w64-mingw32-ld: cannot find -lSDL2_gfx: No such file or directory`

My build command is :

```
env CGO_ENABLED="1" CC="/usr/bin/x86_64-w64-mingw32-gcc" GOOS="windows" CGO_LDFLAGS="-lmingw32 -lSDL2" CGO_CFLAGS="-D_REENTRANT" go build -x ./examples/test_examples.go
```

Which kind of makes sense because I haven't compiled `SDL2_gfx `-  (this being provided by the DLL I sourced from #427) - but I don't understand the workings of mingw to put it all together. Do I need to build SDL2_gfx using mingw first somehow?

**Comment by veeableful** [comment]
Hi @smagrath, thanks for opening an issue! Could you try copying the `SDL2_gfx.dll` file into the MinGW `lib` directory (that contains `libSDL2.dll.a`) as `libSDL2_gfx.dll.a`? Then the header files `SDL2_*.h` of SDL2_gfx will also need to be copied to the `include/SDL2` directory. After that, could you try to compile again?

For example, on my Fedora Linux machine I copied the files like this:
```
sudo cp ~/Downloads/SDL2_gfx.dll /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libSDL2_gfx.dll.a
sudo cp ~/Downloads/Source/SDL2_gfx-1.0.4/*.h /usr/x86_64-w64-mingw32/sys-root/mingw/include/SDL2/
```

**Comment by smagrath** [comment]
Yes thank you - that helps. It now compiles :-)

**Comment by smagrath** [comment]
Yes thank you - that helps. It now compiles :-)
