### ISSUE TITLE
Workaround for static libraries breaks `go get -u`

### ISSUE THREAD

**Issue by ptxmac** [veandco/go-sdl2#557]
After 9515279986a1fc8d043e301522c565a0b8b56480 it's no longer possible to update _all_ dependencies in a project that use go-sdl2.

Normally this would be done by running `go get -u ./...`, but after the dummy package was added the go command fails:
```
go: malformed module path "github.com/veandco/go-sdl2/.go-sdl2-libs": leading dot in path element
go: malformed module path "github.com/veandco/go-sdl2/.go-sdl2-libs/include/SDL2": leading dot in path element
```

Go version: 1.20.2
Go-SDL2 version: 0.4.33
OS: macos
Architecture: arm64

**Comment by veeableful** [comment]
Hi @ptxmac, thanks for reporting this issue! Sorry for taking so long to reply as I'm out of town. I will try to implement a solution around end of next week once I'm back, perhaps by renaming the directories. Will post an update here then!

**Comment by ptxmac** [comment]
Any update? I think it would be fine if we just replace the `.` with `_`

**Comment by veeableful** [comment]
Hi @ptxmac, sorry I was actually just starting to work on this! Could you let me know how I can reproduce the issue? I might just end up following your suggestion in order to fix it.

**Comment by ptxmac** [comment]
Sure, create a new project that use go modules. E.g.

`main.go`:
```golang
package main

import "github.com/veandco/go-sdl2/sdl"

func main() {
	sdl.GetRevision()
}
```

and `go.mod`:
```
module github.com/ptxmac/go-sdl2-get-bug

go 1.20

require github.com/veandco/go-sdl2 v0.4.33
```

Then run `go get -u`

**Comment by veeableful** [comment]
That's strange.. `go get -u` succeeded for me using the same configuration as yours. Is there something else that I should do?

**Comment by ptxmac** [comment]
Perhaps you're using a different version of go?
This bug appears on go1.20

I've created a quick sample project here: https://github.com/ptxmac/go-sdl2-get-bug

**Comment by veeableful** [comment]
My Go version is `go version go1.20.2 darwin/arm64`. I cloned the sample project and ran `go get -u` there as well but it didn't produce any error.

**Comment by ptxmac** [comment]
Very strange, I'm using `go version go1.20.3 darwin/arm64` But I also saw it on v1.20.2

Maybe if you use `go get -u ./...` instead?

**Comment by veeableful** [comment]
I tried with `go get -u ./...` but the error doesn't show up. I will keep trying to see if I can reproduce it.

**Comment by ptxmac** [comment]
Very strange... perhaps try removing go-sdl from the mod cache in `go env GOMODCACHE`

**Comment by veeableful** [comment]
It still runs fine...I also tried with a new macOS user with an empty home directory.

**Comment by ptxmac** [comment]
So apparently it's something with my setup - I just tried an empty user, and there it works fine... 🙃

**Comment by veeableful** [comment]
Oh... if you happen to find the cause, please let me know! I would be interested to know why that error happened and perhaps add that information to the README.

**Comment by ptxmac** [comment]
I figured it out!

I had to step through `go get` in a debugger, but finally discovered the difference. I have `GONOPROXY` configured!

From my understanding the `go get` command will look up modules on a proxy server to avoid putting too much load on the repository. If `GONOPROXY` is set it will go directly to the repository instead.

I guess the proxy server ignores files starting with a dot when it indexes a repository.

You can test it out with `GONOPROXY=test go get -u`

**Comment by ptxmac** [comment]
It also happens if `GONOSUMDB` is set. BAsically if you have a project that depends on private packages, then it will break

**Comment by veeableful** [comment]
Hi @ptxmac, thank you very much for finding the way to reproduce it! I renamed the `.go-sdl2-libs` directory to `_libs` and pushed that change to the `test` branch. It seems to work for me so let me know if it works for you too. I will tag a new version once it's confirmed to fix it 🙂

**Comment by ptxmac** [comment]
Works perfect for me too!

**Comment by veeableful** [comment]
Okay, I have pushed the tag `v0.4.34`!
