### ISSUE TITLE
Instructions in the 'ReadMe' file are outdated.

### ISSUE THREAD

**Issue by vault-thirteen** [veandco/go-sdl2#558]
I fail to complete the first step of the instructions.

> 1. Install mingw-w64 from Mingw-builds

The link leads to a non-existent URL.

OS is Windows 10.

**Comment by veeableful** [comment]
Hi @vault-thirteen, thanks for reporting this issue. I have updated the README file with newer information. Please try again!

**Comment by vault-thirteen** [comment]
It works :)
