### ISSUE TITLE
SDL_AudioStreamAvailable not correctly wrapped

### ISSUE THREAD

**Issue by stringflow** [veandco/go-sdl2#587]
Go version: 1.21.5
Go-SDL2 version: master
SDL2 version: 2.28.5
OS: windows
Architecture: amd64

The `SDL_AudioStreamAvailable` function appears not to be wrapped correctly, giving back an error value and not the expected number of bytes available.
https://wiki.libsdl.org/SDL2/SDL_AudioStreamAvailable

**Comment by veeableful** [comment]
Hi @stringflow, thanks for reporting this issue! I have pushed a fix to `master` and `v0.4.37` branches. Let me know if it works for you.

**Comment by stringflow** [comment]
Thank you for the quick fix, it works as expected now.
