### ISSUE TITLE
Readme Example Fix typo

### ISSUE THREAD

**Issue by horw** [veandco/go-sdl2#592]
Go version: 1.21.3
Go-SDL2 version: v0.4.38
SDL2 version:
OS:
Architecture:

**Hello!**

It seems like there are some typos in the example you provided in README.md.
```golang
      for running {
		for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
			switch event.(type) {
			case sdl.QuitEvent:
				println("Quit")
				running = false
				break
			}
		}
	}
```
In the corrected code, I changed sdl.QuitEvent to *sdl.QuitEvent in the case statement to match the correct type.
I hope this helps!

**Comment by veeableful** [comment]
Hi @horw, the example without asterisk in the event type is for the `master` branch which is bound for `v0.5.x`. It seems like you're using `v0.4.x` which uses asterisk. I will add a comment to the example in the README to make it clear.

**Comment by horw** [comment]
I see! @veeableful, Thank you!
