### ISSUE TITLE
SdlSetTextureScaleMode

### ISSUE THREAD

**Issue by clseibold** [veandco/go-sdl2#597]
SdlSetTextureScaleMode seems to be missing.

**Comment by veeableful** [comment]
Hi @clseibold, it should be available under `sdl.Texture.SetScaleMode()`.

**Comment by clseibold** [comment]
Oh, ok. Thanks. I didn't check that. I guess I expected it as a method on the texture itself, or at `sdl.SetTextureScaleMode()`.

**Comment by clseibold** [comment]
@veeableful I'm using the latest release of the library (0.4.38) and I am not getting any method for SetScaleMode().

**Comment by clseibold** [comment]
Looks like it's only in the alpha versions. I'm getting other problems with the alpha versions so I'll just wait until 0.5 is officially released.

**Comment by veeableful** [comment]
Sorry about that @clseibold, would you be able to report the problems in `v0.5.x`?

**Comment by clseibold** [comment]
@veeableful Thanks.

It was mostly breaking API changes, some of which were a little unexpected. I think there was a problem with the Keyboard Events types that got fixed in the main branch, but it handn't been included in an alpha version yet.

**Comment by veeableful** [comment]
Hi @clseibold, I see. I have tagged the latest commit with `v0.5.0-alpha.5` in case you would like to try it out!
