### ISSUE TITLE
Example of go-sdl2 using go routines

### ISSUE THREAD

**Issue by AuroreDupont** [veandco/go-sdl2#75]
SDL2 has threading requirements. For instance, it would seem that the thread creating the main window needs also to be the same thread for manipulating the renderer and for pooling events. 

Is it possible to use go routines with go-sdl2?

**Comment by Decker108** [comment]
Seconding the wish for a go-sdl2 example with goroutines. This issue isn't very obvious to beginners of go or sdl.

**Comment by krux02** [comment]
I would suggest here, that sdl.Init() calls runtime.LockOSThread() internally, so that users of SDL do not need to worry about this anymore.

**Comment by THUNDERGROOVE** [comment]
I recently wrote something that uses a Goroutine that calls `runtime.LockOSThread()` to poll events into a channel in a select statement as to not block.  Everything else related to SDL is ran outside of any Goroutines.

It works very well and I no longer get any `program.exe is not responding` pop-ups from Windows.

All of my drawing code is actually come from a struct `Screen` that has a slice of interfaces named `Component` that have:

`OnEvent(e sdl.Event) error`
`Draw(w *sdl.Window, r *sdl.Renderer) error`

Almost every single `Component` that I have has a constructor function.  Most of them ask for an x, y.  Some need a *ttf.Font etc.

`Screen` has a `Start()` method which starts a for loop that looks kinda like this.

```
tick := time.NewTicker(time.Millisecond*33) //~30fps
for s.running {
    select {
        case <-s.stopChan:
            break
        case e := <-events.Events:
            // Call OnEvent(e) on all of our components
        case <-tick.C:
            // Call Draw(w, r) on all of our components
    }
}
```

I just have a `Screen` for anything I want to show.  If I want to switch to a new `Screen` I just call for example 
```
ExampleScreen.Stop()
NewScreen.Start()
```

So far this method isn't giving me any problems so I'll likely stick with it.

**Comment by charneykaye** [comment]
Here's an example I made, of go-sdl2 working with a goroutine. However, I'm noticing that the performance of this program is extremely choppy. https://github.com/charneykaye/go-SDL-experiements/blob/master/stars_goroutine.go

**Comment by aqiank** [comment]
I've added a new `render_goroutines` example which uses a global channel where you can put your thread-sensitive calls like SDL's render functions. It's called `sdl.CallQueue` for now but if you guys have suggestions, go ahead.

The example code looks something like this:

    // Set a WaitGroup to wait until all pixels are drawn
    var wg sync.WaitGroup

    for y := 0; y < winHeight; y++ {
        for x := 0; x < winWidth; x++ {
            wg.Add(1) 

            go func(x, y int) {
                // Do some fake processing before rendering
                r := byte(rand.Int())
                g := byte(rand.Int())
                b := byte(rand.Int())

                sdl.CallQueue <- func() {
                    renderer.SetDrawColor(r, g, b, 255)
                    renderer.DrawPoint(x, y)
                    wg.Done()
                }
            }(x, y)
        }
    }

    // Wait until all pixels are drawn
    wg.Wait()

Let me know what you guys think.
