### ISSUE TITLE
SDL.h: No such file or directory (Win7, no pkg-config installed)

### ISSUE THREAD

**Issue by Decker108** [veandco/go-sdl2#88]
Another unlucky Windows user here.
Is there a way to solve this without using pkg-config? I'm still getting the "fatal error: SDL.h: No such file or directory  // #include <SDL.h>".

Do I have to put the SDL.h file in one of the go-sdl2 folders?
Do I need to put in on the path?
I've tried experimenting with putting SDL.h in various go-sdl2 folders and running make.bat, but no luck.

Using x86_64-w64-mingw32's GCC, Go 1.4.1, Win 7.

(I kind of don't even know why I bother... everything just works on Linux...)

**Comment by akovaski** [comment]
SDL.h would have to been in your mingw's include directory, specifically (your include directory)\SDL2\SDL.h

Also, don't forget to put SDL's lib files in your lib folder.

**Comment by Decker108** [comment]
I put the source files in the mingw include\SDL2\SDL.h and the .dll's in the lib folder. Still getting the same error.

**Comment by Decker108** [comment]
The strange thing is that according to the GCC -v printout, it is looking in the include dirs and lib dirs that I have put the SDL2 files in:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Program\ Files/mingw-w64/x86_64-4.9.2-posix-seh-rt_v3-rev
1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.2/configure --host=x86_64-w64-mingw32 --bu
ild=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysr
oot=/c/mingw492/x86_64-492-posix-seh-rt_v3-rev1/mingw64 --with-gxx-include-dir=/
mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable
-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdc
xx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-
lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --
enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog
-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootst
rap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --di
sable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 -
-with-libiconv --with-system-zlib --with-gmp=/c/mingw492/prerequisites/x86_64-w6
4-mingw32-static --with-mpfr=/c/mingw492/prerequisites/x86_64-w64-mingw32-static
 --with-mpc=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mi
ngw492/prerequisites/x86_64-w64-mingw32-static --with-cloog=/c/mingw492/prerequi
sites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x8
6_64-posix-seh-rev1, Built by MinGW-W64 project' --with-bugurl=http://sourceforg
e.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw492/x86_64-492-posix-seh-rt
_v3-rev1/mingw64/opt/include -I/c/mingw492/prerequisites/x86_64-zlib-static/incl
ude -I/c/mingw492/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2
 -pipe -I/c/mingw492/x86_64-492-posix-seh-rt_v3-rev1/mingw64/opt/include -I/c/mi
ngw492/prerequisites/x86_64-zlib-static/include -I/c/mingw492/prerequisites/x86_
64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw492/x86_64-492
-posix-seh-rt_v3-rev1/mingw64/opt/lib -L/c/mingw492/prerequisites/x86_64-zlib-st
atic/lib -L/c/mingw492/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.2 (x86_64-posix-seh-rev1, Built by MinGW-W64 project)

Is the make.bat in go-sdl2 defaulting to some other settings?

**Comment by Decker108** [comment]
Okay, seems this is not a problem with go-sdl2 but rather with my SDL2 installation. I can't get hello-world with SDL in C/C++ to compile, so I'm closing this and going down that troubleshooting route.

**Comment by Decker108** [comment]
In case anyone finds this in the future, I put together a tested and working step-by-step guide here: https://gist.github.com/Decker108/7df1726192433a3bdb32
